/*      */ package mzm.gsp;
/*      */ 
/*      */ import com.goldhuman.Common.Marshal.OctetsStream;
/*      */ 
/*      */ public class BeanImport extends __BeanImport__ {
/*      */   public static final int PROTOCOL_TYPE = 12590091;
/*      */   public mzm.gsp.online.OnlineStatus _onlinestatus;
/*      */   public mzm.gsp.fight.FighterStatus _fighterstatus;
/*      */   public mzm.gsp.task.TaskConsts _taskconsts;
/*      */   public mzm.gsp.chat.ChatConsts _chatconsts;
/*      */   public mzm.gsp.friend.FriendConsts _friendconsts;
/*      */   public mzm.gsp.mail.MailConsts _mailconsts;
/*      */   public mzm.gsp.item.ItemXStoreType _itemxstoretype;
/*      */   public mzm.gsp.item.ItemSourceEnum _itemsourceenum;
/*      */   public mzm.gsp.grow.GrowConsts _growconsts;
/*      */   public mzm.gsp.status.ErrorCode _status_errorcode;
/*      */   public mzm.gsp.status.StatusEnum _statusenum;
/*      */   public mzm.gsp.fight.FightConsts _fightconsts;
/*      */   public mzm.gsp.fight.OpSkill _opskill;
/*      */   public mzm.gsp.fight.OpItem _opitem;
/*      */   public mzm.gsp.fight.OpCapture _opcapture;
/*      */   
/*      */   protected void process() {}
/*      */   
/*   25 */   public int getType() { return 12590091; }
/*      */   
/*      */ 
/*      */   public mzm.gsp.fight.OpProtect _opprotect;
/*      */   
/*      */   public mzm.gsp.fight.OpSummonPet _opsummonpet;
/*      */   
/*      */   public mzm.gsp.fight.OpSummonChild _opsummonchild;
/*      */   
/*      */   public mzm.gsp.fight.OpSummonMonster _opsummonmonster;
/*      */   
/*      */   public mzm.gsp.fight.PlayType _playtype;
/*      */   
/*      */   public mzm.gsp.fight.PlaySkill _playskill;
/*      */   
/*      */   public mzm.gsp.fight.PlayTip _playtip;
/*      */   
/*      */   public mzm.gsp.fight.PlayEscape _playescape;
/*      */   
/*      */   public mzm.gsp.fight.PlayUseItem _playuseitem;
/*      */   
/*      */   public mzm.gsp.fight.PlayCapture _playcapture;
/*      */   
/*      */   public mzm.gsp.fight.PlaySummon _playsummon;
/*      */   
/*      */   public mzm.gsp.fight.PlayTalk _playtalk;
/*      */   
/*      */   public mzm.gsp.fight.PlayChangeFightMap _playchangefightmap;
/*      */   
/*      */   public mzm.gsp.fight.PlayFighterStatus _playfighterstatus;
/*      */   
/*      */   public mzm.gsp.fight.PlayChangeFighter _playchangefighter;
/*      */   
/*      */   public mzm.gsp.fight.PlayChangeModel _playchangemodel;
/*      */   public mzm.gsp.bulletin.BulletinParamKey _bulletinparamkey;
/*      */   public mzm.gsp.pet.PetConsts _petconsts;
/*      */   public mzm.gsp.systemsetting.SystemSetting _systemsetting;
/*      */   public RoleDeleteStatus _roledeletestatus;
/*      */   public mzm.gsp.gang.GangBuildingEnum _gangbuildingenum;
/*      */   public mzm.gsp.instance.InstanceConst _instanceconst;
/*      */   public mzm.gsp.jiuxiao.JiuXiaoConsts _jiuxiaoconsts;
/*      */   public mzm.gsp.menpaipvp.NpcService _menpaipvp_npcservice;
/*      */   public mzm.gsp.arena.NpcService _arena_npcservice;
/*      */   public mzm.gsp.competition.NpcService _competition_npcservice;
/*      */   public Const _const;
/*      */   public mzm.gsp.pet.PetAptConsts _petaptconst;
/*      */   public mzm.gsp.idip.IdipRet _idip;
/*      */   public mzm.gsp.marriage.MarriageConsts _marriageconst;
/*      */   public mzm.gsp.guide.GuideConsts _guideconst;
/*      */   public mzm.gsp.map.MapModelInfo _mapmodelinfo;
/*      */   public mzm.gsp.map.NPCModelInfo _npcmodelinfo;
/*      */   public mzm.gsp.market.MarketState _marketstate;
/*      */   public mzm.gsp.map.MapGroupType _mapgrouptype;
/*      */   public mzm.gsp.map.MapEntityType _mapentitytype;
/*      */   public mzm.gsp.map.MapEntityExtraInfoType _mapentityextrainfotype;
/*      */   public mzm.gsp.qmhw.QMHWConsts _qmhwconsts;
/*      */   public mzm.gsp.map.MapGroupExtraInfoType _mapgroupextrainfotype;
/*      */   public mzm.gsp.grc.ErrorCodes _grc_errorcodes;
/*      */   public mzm.gsp.grc.RecallRet _grc_recallret;
/*      */   public mzm.gsp.grc.QQVipFlag _qqvipflag;
/*      */   public mzm.gsp.shitu.ShiTuConst _shituconst;
/*      */   public mzm.gsp.gangrace.RaceConsts _raceconsts;
/*      */   public mzm.gsp.coupledaily.CoupleDailyConst _coupledailyconst;
/*      */   public mzm.gsp.idip.IdipNTimesOperator _idipntimesoperator;
/*      */   public mzm.gsp.apollo.ErrorCodes _apollo_errorcodes;
/*      */   public mzm.gsp.apollo.ApolloLargeRoomType _apollolargeroomtype;
/*      */   public mzm.gsp.apollo.ApolloGlobalRoomType _apolloglobalroomtype;
/*      */   public mzm.gsp.question.QyxtHelpStatus _qyxthelpstatus;
/*      */   public mzm.gsp.fashiondress.FashionDressConst _fashiondressconst;
/*      */   public mzm.gsp.fabao.FaBaoConst _fabaoconst;
/*      */   public mzm.gsp.market.ConditionState _conditionstate;
/*      */   public mzm.gsp.achievement.AchievementConst _achievementconst;
/*      */   public mzm.gsp.backgame.BackGameConst _backgameconst;
/*      */   public mzm.gsp.personal.PersonalRet _personal;
/*      */   public mzm.gsp.activity.ActivityConst _activityconst;
/*      */   public mzm.gsp.personal.AdvertRet _advert;
/*      */   public mzm.gsp.qingyuan.QingYuanConst _qingyuanconst;
/*      */   public mzm.gsp.loginaward.LoginActivityRet _loginawardconst;
/*      */   public mzm.gsp.masswedding.MassWeddingConst _massweddingconst;
/*      */   public mzm.gsp.cat.CatRet _catconst;
/*      */   public mzm.gsp.mounts.MountsConst _mountsconst;
/*      */   public mzm.gsp.guaji.SwitchType _doublepointswitchtype;
/*      */   public mzm.gsp.luckybag.LuckyBagRet _luckybagconst;
/*      */   public mzm.gsp.grc.RecallFriendConst _recallfriendconst;
/*      */   public mzm.gsp.apollo.VoipRoomType _apollo_voiproomtype;
/*      */   public mzm.gsp.apollo.VoipRoomAction _apollo_voiproomaction;
/*      */   public mzm.gsp.addiction.PopupType _popuptype;
/*      */   public mzm.gsp.massexp.MassExpRet _massexpret;
/*      */   public mzm.gsp.hula.MonsterState _monsterstate;
/*      */   public mzm.gsp.hula.HulaActivityPhase _hulaactivityphase;
/*      */   public mzm.gsp.ladder.LadderConsts _ladderconst;
/*      */   public mzm.gsp.children.BabyPeriodInfo _babyperiodinfo;
/*      */   public mzm.gsp.children.ChildHoodInfo _childhoodinfo;
/*      */   public mzm.gsp.children.AdulthoodInfo _adulthoodinfo;
/*      */   public mzm.gsp.children.ChildhoodRet _childhoodret;
/*      */   public mzm.gsp.children.ChildFashionRet _childfashionret;
/*      */   public mzm.gsp.children.GrowthType _childgrowthtype;
/*      */   public mzm.gsp.children.GrowthSubType _childgrowthsubtype;
/*      */   public mzm.gsp.watchmoon.WatchmoonErrorCode _watchmoonerrorcode;
/*      */   public mzm.gsp.item.QiLinMode _qilinmode;
/*      */   public mzm.gsp.memorycompetition.MemoryCompetitionConst _memorycompetitionconst;
/*      */   public mzm.gsp.menpaistar.MenPaiStarRet _menpaistarret;
/*      */   public mzm.gsp.genius.GeniusRet _geniusret;
/*      */   public mzm.gsp.bless.BlessRet _blessret;
/*      */   public mzm.gsp.exploit.ExploitConsts _exploitconsts;
/*      */   public mzm.gsp.zoo.ZooRet _zooret;
/*      */   public mzm.gsp.zoo.EmbryoStageInfo _embryostageinfo;
/*      */   public mzm.gsp.zoo.AdultStageInfo _adultstageinfo;
/*      */   public mzm.gsp.drawandguess.DrawAndGuessConst _drawandguessconst;
/*      */   public mzm.gsp.crossbattle.CrossBattleActivityStage _crossbattleactivitystage;
/*      */   public mzm.gsp.crossbattle.CrossBattleVoteRankType _crossbattlevoteranktype;
/*      */   public mzm.gsp.crossbattle.RoundRobinRoundStage _roundrobinroundstage;
/*      */   public mzm.gsp.crossbattle.CrossBattleOwnErrorCode _crossbattleownerrorcode;
/*      */   public mzm.gsp.crossbattle.CrossBattlePointConst _crossbattlepointconst;
/*      */   public mzm.gsp.crossbattle.CrossBattleBetErrorCode _crossbattlebeterrorcode;
/*      */   public mzm.gsp.crossbattle.CrossBattleSelectionConsts _crossbattleselectionconsts;
/*      */   public mzm.gsp.crossbattle.GetKnockoutStageBetInfoReason _getknockoutstagebetinforeason;
/*      */   public mzm.gsp.crossbattle.CrossBattleFinalConsts _crossbattlefinalconsts;
/*      */   public mzm.gsp.crossfield.CrossFieldImportBean _crossfieldimportbean;
/*      */   public mzm.gsp.prison.JailAction _jailaction;
/*      */   public mzm.gsp.questionvoice.QuestionVoiceConst _questionvoiceconst;
/*      */   public mzm.gsp.friendscircle.SSPReqType _sspreqtype;
/*      */   public mzm.gsp.crossbattle.CrossBattleBetImportBean _crossbattlebetimportbean;
/*      */   public mzm.gsp.aircraft.AircraftDataInfo _aircraftdatainfo;
/*      */   public mzm.gsp.indiana.IndianaImportBean _indianaimportbean;
/*      */   public mzm.gsp.alllotto.AllLottoImportBean _alllottoimportbean;
/*      */   public mzm.gsp.cake.CakeConsts _cakeconsts;
/*      */   public mzm.gsp.firework.FireWorkConsts _fireworkconsts;
/*      */   public mzm.gsp.petarena.PetArenaRet _petarenaret;
/*      */   public mzm.gsp.bigboss.BigBossImportBean _bigbossimportbean;
/*      */   public mzm.gsp.ballbattle.PlayerStateEnum _ballbattleplayerstateenum;
/*      */   public BeanImport()
/*      */   {
/*  158 */     this._onlinestatus = new mzm.gsp.online.OnlineStatus();
/*  159 */     this._fighterstatus = new mzm.gsp.fight.FighterStatus();
/*  160 */     this._taskconsts = new mzm.gsp.task.TaskConsts();
/*  161 */     this._chatconsts = new mzm.gsp.chat.ChatConsts();
/*  162 */     this._friendconsts = new mzm.gsp.friend.FriendConsts();
/*  163 */     this._mailconsts = new mzm.gsp.mail.MailConsts();
/*  164 */     this._itemxstoretype = new mzm.gsp.item.ItemXStoreType();
/*  165 */     this._itemsourceenum = new mzm.gsp.item.ItemSourceEnum();
/*  166 */     this._growconsts = new mzm.gsp.grow.GrowConsts();
/*  167 */     this._status_errorcode = new mzm.gsp.status.ErrorCode();
/*  168 */     this._statusenum = new mzm.gsp.status.StatusEnum();
/*  169 */     this._fightconsts = new mzm.gsp.fight.FightConsts();
/*  170 */     this._opskill = new mzm.gsp.fight.OpSkill();
/*  171 */     this._opitem = new mzm.gsp.fight.OpItem();
/*  172 */     this._opcapture = new mzm.gsp.fight.OpCapture();
/*  173 */     this._opprotect = new mzm.gsp.fight.OpProtect();
/*  174 */     this._opsummonpet = new mzm.gsp.fight.OpSummonPet();
/*  175 */     this._opsummonchild = new mzm.gsp.fight.OpSummonChild();
/*  176 */     this._opsummonmonster = new mzm.gsp.fight.OpSummonMonster();
/*  177 */     this._playtype = new mzm.gsp.fight.PlayType();
/*  178 */     this._playskill = new mzm.gsp.fight.PlaySkill();
/*  179 */     this._playtip = new mzm.gsp.fight.PlayTip();
/*  180 */     this._playescape = new mzm.gsp.fight.PlayEscape();
/*  181 */     this._playuseitem = new mzm.gsp.fight.PlayUseItem();
/*  182 */     this._playcapture = new mzm.gsp.fight.PlayCapture();
/*  183 */     this._playsummon = new mzm.gsp.fight.PlaySummon();
/*  184 */     this._playtalk = new mzm.gsp.fight.PlayTalk();
/*  185 */     this._playchangefightmap = new mzm.gsp.fight.PlayChangeFightMap();
/*  186 */     this._playfighterstatus = new mzm.gsp.fight.PlayFighterStatus();
/*  187 */     this._playchangefighter = new mzm.gsp.fight.PlayChangeFighter();
/*  188 */     this._playchangemodel = new mzm.gsp.fight.PlayChangeModel();
/*  189 */     this._bulletinparamkey = new mzm.gsp.bulletin.BulletinParamKey();
/*  190 */     this._petconsts = new mzm.gsp.pet.PetConsts();
/*  191 */     this._systemsetting = new mzm.gsp.systemsetting.SystemSetting();
/*  192 */     this._roledeletestatus = new RoleDeleteStatus();
/*  193 */     this._gangbuildingenum = new mzm.gsp.gang.GangBuildingEnum();
/*  194 */     this._instanceconst = new mzm.gsp.instance.InstanceConst();
/*  195 */     this._jiuxiaoconsts = new mzm.gsp.jiuxiao.JiuXiaoConsts();
/*  196 */     this._menpaipvp_npcservice = new mzm.gsp.menpaipvp.NpcService();
/*  197 */     this._arena_npcservice = new mzm.gsp.arena.NpcService();
/*  198 */     this._competition_npcservice = new mzm.gsp.competition.NpcService();
/*  199 */     this._const = new Const();
/*  200 */     this._petaptconst = new mzm.gsp.pet.PetAptConsts();
/*  201 */     this._idip = new mzm.gsp.idip.IdipRet();
/*  202 */     this._marriageconst = new mzm.gsp.marriage.MarriageConsts();
/*  203 */     this._guideconst = new mzm.gsp.guide.GuideConsts();
/*  204 */     this._mapmodelinfo = new mzm.gsp.map.MapModelInfo();
/*  205 */     this._npcmodelinfo = new mzm.gsp.map.NPCModelInfo();
/*  206 */     this._marketstate = new mzm.gsp.market.MarketState();
/*  207 */     this._mapgrouptype = new mzm.gsp.map.MapGroupType();
/*  208 */     this._mapentitytype = new mzm.gsp.map.MapEntityType();
/*  209 */     this._mapentityextrainfotype = new mzm.gsp.map.MapEntityExtraInfoType();
/*  210 */     this._qmhwconsts = new mzm.gsp.qmhw.QMHWConsts();
/*  211 */     this._mapgroupextrainfotype = new mzm.gsp.map.MapGroupExtraInfoType();
/*  212 */     this._grc_errorcodes = new mzm.gsp.grc.ErrorCodes();
/*  213 */     this._grc_recallret = new mzm.gsp.grc.RecallRet();
/*  214 */     this._qqvipflag = new mzm.gsp.grc.QQVipFlag();
/*  215 */     this._shituconst = new mzm.gsp.shitu.ShiTuConst();
/*  216 */     this._raceconsts = new mzm.gsp.gangrace.RaceConsts();
/*  217 */     this._coupledailyconst = new mzm.gsp.coupledaily.CoupleDailyConst();
/*  218 */     this._idipntimesoperator = new mzm.gsp.idip.IdipNTimesOperator();
/*  219 */     this._apollo_errorcodes = new mzm.gsp.apollo.ErrorCodes();
/*  220 */     this._apollolargeroomtype = new mzm.gsp.apollo.ApolloLargeRoomType();
/*  221 */     this._apolloglobalroomtype = new mzm.gsp.apollo.ApolloGlobalRoomType();
/*  222 */     this._qyxthelpstatus = new mzm.gsp.question.QyxtHelpStatus();
/*  223 */     this._fashiondressconst = new mzm.gsp.fashiondress.FashionDressConst();
/*  224 */     this._fabaoconst = new mzm.gsp.fabao.FaBaoConst();
/*  225 */     this._conditionstate = new mzm.gsp.market.ConditionState();
/*  226 */     this._achievementconst = new mzm.gsp.achievement.AchievementConst();
/*  227 */     this._backgameconst = new mzm.gsp.backgame.BackGameConst();
/*  228 */     this._personal = new mzm.gsp.personal.PersonalRet();
/*  229 */     this._activityconst = new mzm.gsp.activity.ActivityConst();
/*  230 */     this._advert = new mzm.gsp.personal.AdvertRet();
/*  231 */     this._qingyuanconst = new mzm.gsp.qingyuan.QingYuanConst();
/*  232 */     this._loginawardconst = new mzm.gsp.loginaward.LoginActivityRet();
/*  233 */     this._massweddingconst = new mzm.gsp.masswedding.MassWeddingConst();
/*  234 */     this._catconst = new mzm.gsp.cat.CatRet();
/*  235 */     this._mountsconst = new mzm.gsp.mounts.MountsConst();
/*  236 */     this._doublepointswitchtype = new mzm.gsp.guaji.SwitchType();
/*  237 */     this._luckybagconst = new mzm.gsp.luckybag.LuckyBagRet();
/*  238 */     this._recallfriendconst = new mzm.gsp.grc.RecallFriendConst();
/*  239 */     this._apollo_voiproomtype = new mzm.gsp.apollo.VoipRoomType();
/*  240 */     this._apollo_voiproomaction = new mzm.gsp.apollo.VoipRoomAction();
/*  241 */     this._popuptype = new mzm.gsp.addiction.PopupType();
/*  242 */     this._massexpret = new mzm.gsp.massexp.MassExpRet();
/*  243 */     this._monsterstate = new mzm.gsp.hula.MonsterState();
/*  244 */     this._hulaactivityphase = new mzm.gsp.hula.HulaActivityPhase();
/*  245 */     this._ladderconst = new mzm.gsp.ladder.LadderConsts();
/*  246 */     this._babyperiodinfo = new mzm.gsp.children.BabyPeriodInfo();
/*  247 */     this._childhoodinfo = new mzm.gsp.children.ChildHoodInfo();
/*  248 */     this._adulthoodinfo = new mzm.gsp.children.AdulthoodInfo();
/*  249 */     this._childhoodret = new mzm.gsp.children.ChildhoodRet();
/*  250 */     this._childfashionret = new mzm.gsp.children.ChildFashionRet();
/*  251 */     this._childgrowthtype = new mzm.gsp.children.GrowthType();
/*  252 */     this._childgrowthsubtype = new mzm.gsp.children.GrowthSubType();
/*  253 */     this._watchmoonerrorcode = new mzm.gsp.watchmoon.WatchmoonErrorCode();
/*  254 */     this._qilinmode = new mzm.gsp.item.QiLinMode();
/*  255 */     this._memorycompetitionconst = new mzm.gsp.memorycompetition.MemoryCompetitionConst();
/*  256 */     this._menpaistarret = new mzm.gsp.menpaistar.MenPaiStarRet();
/*  257 */     this._geniusret = new mzm.gsp.genius.GeniusRet();
/*  258 */     this._blessret = new mzm.gsp.bless.BlessRet();
/*  259 */     this._exploitconsts = new mzm.gsp.exploit.ExploitConsts();
/*  260 */     this._zooret = new mzm.gsp.zoo.ZooRet();
/*  261 */     this._embryostageinfo = new mzm.gsp.zoo.EmbryoStageInfo();
/*  262 */     this._adultstageinfo = new mzm.gsp.zoo.AdultStageInfo();
/*  263 */     this._drawandguessconst = new mzm.gsp.drawandguess.DrawAndGuessConst();
/*  264 */     this._crossbattleactivitystage = new mzm.gsp.crossbattle.CrossBattleActivityStage();
/*  265 */     this._crossbattlevoteranktype = new mzm.gsp.crossbattle.CrossBattleVoteRankType();
/*  266 */     this._roundrobinroundstage = new mzm.gsp.crossbattle.RoundRobinRoundStage();
/*  267 */     this._crossbattleownerrorcode = new mzm.gsp.crossbattle.CrossBattleOwnErrorCode();
/*  268 */     this._crossbattlepointconst = new mzm.gsp.crossbattle.CrossBattlePointConst();
/*  269 */     this._crossbattlebeterrorcode = new mzm.gsp.crossbattle.CrossBattleBetErrorCode();
/*  270 */     this._crossbattleselectionconsts = new mzm.gsp.crossbattle.CrossBattleSelectionConsts();
/*  271 */     this._getknockoutstagebetinforeason = new mzm.gsp.crossbattle.GetKnockoutStageBetInfoReason();
/*  272 */     this._crossbattlefinalconsts = new mzm.gsp.crossbattle.CrossBattleFinalConsts();
/*  273 */     this._crossfieldimportbean = new mzm.gsp.crossfield.CrossFieldImportBean();
/*  274 */     this._jailaction = new mzm.gsp.prison.JailAction();
/*  275 */     this._questionvoiceconst = new mzm.gsp.questionvoice.QuestionVoiceConst();
/*  276 */     this._sspreqtype = new mzm.gsp.friendscircle.SSPReqType();
/*  277 */     this._crossbattlebetimportbean = new mzm.gsp.crossbattle.CrossBattleBetImportBean();
/*  278 */     this._aircraftdatainfo = new mzm.gsp.aircraft.AircraftDataInfo();
/*  279 */     this._indianaimportbean = new mzm.gsp.indiana.IndianaImportBean();
/*  280 */     this._alllottoimportbean = new mzm.gsp.alllotto.AllLottoImportBean();
/*  281 */     this._cakeconsts = new mzm.gsp.cake.CakeConsts();
/*  282 */     this._fireworkconsts = new mzm.gsp.firework.FireWorkConsts();
/*  283 */     this._petarenaret = new mzm.gsp.petarena.PetArenaRet();
/*  284 */     this._bigbossimportbean = new mzm.gsp.bigboss.BigBossImportBean();
/*  285 */     this._ballbattleplayerstateenum = new mzm.gsp.ballbattle.PlayerStateEnum();
/*      */   }
/*      */   
/*      */   public BeanImport(mzm.gsp.online.OnlineStatus __onlinestatus_, mzm.gsp.fight.FighterStatus __fighterstatus_, mzm.gsp.task.TaskConsts __taskconsts_, mzm.gsp.chat.ChatConsts __chatconsts_, mzm.gsp.friend.FriendConsts __friendconsts_, mzm.gsp.mail.MailConsts __mailconsts_, mzm.gsp.item.ItemXStoreType __itemxstoretype_, mzm.gsp.item.ItemSourceEnum __itemsourceenum_, mzm.gsp.grow.GrowConsts __growconsts_, mzm.gsp.status.ErrorCode __status_errorcode_, mzm.gsp.status.StatusEnum __statusenum_, mzm.gsp.fight.FightConsts __fightconsts_, mzm.gsp.fight.OpSkill __opskill_, mzm.gsp.fight.OpItem __opitem_, mzm.gsp.fight.OpCapture __opcapture_, mzm.gsp.fight.OpProtect __opprotect_, mzm.gsp.fight.OpSummonPet __opsummonpet_, mzm.gsp.fight.OpSummonChild __opsummonchild_, mzm.gsp.fight.OpSummonMonster __opsummonmonster_, mzm.gsp.fight.PlayType __playtype_, mzm.gsp.fight.PlaySkill __playskill_, mzm.gsp.fight.PlayTip __playtip_, mzm.gsp.fight.PlayEscape __playescape_, mzm.gsp.fight.PlayUseItem __playuseitem_, mzm.gsp.fight.PlayCapture __playcapture_, mzm.gsp.fight.PlaySummon __playsummon_, mzm.gsp.fight.PlayTalk __playtalk_, mzm.gsp.fight.PlayChangeFightMap __playchangefightmap_, mzm.gsp.fight.PlayFighterStatus __playfighterstatus_, mzm.gsp.fight.PlayChangeFighter __playchangefighter_, mzm.gsp.fight.PlayChangeModel __playchangemodel_, mzm.gsp.bulletin.BulletinParamKey __bulletinparamkey_, mzm.gsp.pet.PetConsts __petconsts_, mzm.gsp.systemsetting.SystemSetting __systemsetting_, RoleDeleteStatus __roledeletestatus_, mzm.gsp.gang.GangBuildingEnum __gangbuildingenum_, mzm.gsp.instance.InstanceConst __instanceconst_, mzm.gsp.jiuxiao.JiuXiaoConsts __jiuxiaoconsts_, mzm.gsp.menpaipvp.NpcService __menpaipvp_npcservice_, mzm.gsp.arena.NpcService __arena_npcservice_, mzm.gsp.competition.NpcService __competition_npcservice_, Const __const_, mzm.gsp.pet.PetAptConsts __petaptconst_, mzm.gsp.idip.IdipRet __idip_, mzm.gsp.marriage.MarriageConsts __marriageconst_, mzm.gsp.guide.GuideConsts __guideconst_, mzm.gsp.map.MapModelInfo __mapmodelinfo_, mzm.gsp.map.NPCModelInfo __npcmodelinfo_, mzm.gsp.market.MarketState __marketstate_, mzm.gsp.map.MapGroupType __mapgrouptype_, mzm.gsp.map.MapEntityType __mapentitytype_, mzm.gsp.map.MapEntityExtraInfoType __mapentityextrainfotype_, mzm.gsp.qmhw.QMHWConsts __qmhwconsts_, mzm.gsp.map.MapGroupExtraInfoType __mapgroupextrainfotype_, mzm.gsp.grc.ErrorCodes __grc_errorcodes_, mzm.gsp.grc.RecallRet __grc_recallret_, mzm.gsp.grc.QQVipFlag __qqvipflag_, mzm.gsp.shitu.ShiTuConst __shituconst_, mzm.gsp.gangrace.RaceConsts __raceconsts_, mzm.gsp.coupledaily.CoupleDailyConst __coupledailyconst_, mzm.gsp.idip.IdipNTimesOperator __idipntimesoperator_, mzm.gsp.apollo.ErrorCodes __apollo_errorcodes_, mzm.gsp.apollo.ApolloLargeRoomType __apollolargeroomtype_, mzm.gsp.apollo.ApolloGlobalRoomType __apolloglobalroomtype_, mzm.gsp.question.QyxtHelpStatus __qyxthelpstatus_, mzm.gsp.fashiondress.FashionDressConst __fashiondressconst_, mzm.gsp.fabao.FaBaoConst __fabaoconst_, mzm.gsp.market.ConditionState __conditionstate_, mzm.gsp.achievement.AchievementConst __achievementconst_, mzm.gsp.backgame.BackGameConst __backgameconst_, mzm.gsp.personal.PersonalRet __personal_, mzm.gsp.activity.ActivityConst __activityconst_, mzm.gsp.personal.AdvertRet __advert_, mzm.gsp.qingyuan.QingYuanConst __qingyuanconst_, mzm.gsp.loginaward.LoginActivityRet __loginawardconst_, mzm.gsp.masswedding.MassWeddingConst __massweddingconst_, mzm.gsp.cat.CatRet __catconst_, mzm.gsp.mounts.MountsConst __mountsconst_, mzm.gsp.guaji.SwitchType __doublepointswitchtype_, mzm.gsp.luckybag.LuckyBagRet __luckybagconst_, mzm.gsp.grc.RecallFriendConst __recallfriendconst_, mzm.gsp.apollo.VoipRoomType __apollo_voiproomtype_, mzm.gsp.apollo.VoipRoomAction __apollo_voiproomaction_, mzm.gsp.addiction.PopupType __popuptype_, mzm.gsp.massexp.MassExpRet __massexpret_, mzm.gsp.hula.MonsterState __monsterstate_, mzm.gsp.hula.HulaActivityPhase __hulaactivityphase_, mzm.gsp.ladder.LadderConsts __ladderconst_, mzm.gsp.children.BabyPeriodInfo __babyperiodinfo_, mzm.gsp.children.ChildHoodInfo __childhoodinfo_, mzm.gsp.children.AdulthoodInfo __adulthoodinfo_, mzm.gsp.children.ChildhoodRet __childhoodret_, mzm.gsp.children.ChildFashionRet __childfashionret_, mzm.gsp.children.GrowthType __childgrowthtype_, mzm.gsp.children.GrowthSubType __childgrowthsubtype_, mzm.gsp.watchmoon.WatchmoonErrorCode __watchmoonerrorcode_, mzm.gsp.item.QiLinMode __qilinmode_, mzm.gsp.memorycompetition.MemoryCompetitionConst __memorycompetitionconst_, mzm.gsp.menpaistar.MenPaiStarRet __menpaistarret_, mzm.gsp.genius.GeniusRet __geniusret_, mzm.gsp.bless.BlessRet __blessret_, mzm.gsp.exploit.ExploitConsts __exploitconsts_, mzm.gsp.zoo.ZooRet __zooret_, mzm.gsp.zoo.EmbryoStageInfo __embryostageinfo_, mzm.gsp.zoo.AdultStageInfo __adultstageinfo_, mzm.gsp.drawandguess.DrawAndGuessConst __drawandguessconst_, mzm.gsp.crossbattle.CrossBattleActivityStage __crossbattleactivitystage_, mzm.gsp.crossbattle.CrossBattleVoteRankType __crossbattlevoteranktype_, mzm.gsp.crossbattle.RoundRobinRoundStage __roundrobinroundstage_, mzm.gsp.crossbattle.CrossBattleOwnErrorCode __crossbattleownerrorcode_, mzm.gsp.crossbattle.CrossBattlePointConst __crossbattlepointconst_, mzm.gsp.crossbattle.CrossBattleBetErrorCode __crossbattlebeterrorcode_, mzm.gsp.crossbattle.CrossBattleSelectionConsts __crossbattleselectionconsts_, mzm.gsp.crossbattle.GetKnockoutStageBetInfoReason __getknockoutstagebetinforeason_, mzm.gsp.crossbattle.CrossBattleFinalConsts __crossbattlefinalconsts_, mzm.gsp.crossfield.CrossFieldImportBean __crossfieldimportbean_, mzm.gsp.prison.JailAction __jailaction_, mzm.gsp.questionvoice.QuestionVoiceConst __questionvoiceconst_, mzm.gsp.friendscircle.SSPReqType __sspreqtype_, mzm.gsp.crossbattle.CrossBattleBetImportBean __crossbattlebetimportbean_, mzm.gsp.aircraft.AircraftDataInfo __aircraftdatainfo_, mzm.gsp.indiana.IndianaImportBean __indianaimportbean_, mzm.gsp.alllotto.AllLottoImportBean __alllottoimportbean_, mzm.gsp.cake.CakeConsts __cakeconsts_, mzm.gsp.firework.FireWorkConsts __fireworkconsts_, mzm.gsp.petarena.PetArenaRet __petarenaret_, mzm.gsp.bigboss.BigBossImportBean __bigbossimportbean_, mzm.gsp.ballbattle.PlayerStateEnum __ballbattleplayerstateenum_) {
/*  289 */     this._onlinestatus = __onlinestatus_;
/*  290 */     this._fighterstatus = __fighterstatus_;
/*  291 */     this._taskconsts = __taskconsts_;
/*  292 */     this._chatconsts = __chatconsts_;
/*  293 */     this._friendconsts = __friendconsts_;
/*  294 */     this._mailconsts = __mailconsts_;
/*  295 */     this._itemxstoretype = __itemxstoretype_;
/*  296 */     this._itemsourceenum = __itemsourceenum_;
/*  297 */     this._growconsts = __growconsts_;
/*  298 */     this._status_errorcode = __status_errorcode_;
/*  299 */     this._statusenum = __statusenum_;
/*  300 */     this._fightconsts = __fightconsts_;
/*  301 */     this._opskill = __opskill_;
/*  302 */     this._opitem = __opitem_;
/*  303 */     this._opcapture = __opcapture_;
/*  304 */     this._opprotect = __opprotect_;
/*  305 */     this._opsummonpet = __opsummonpet_;
/*  306 */     this._opsummonchild = __opsummonchild_;
/*  307 */     this._opsummonmonster = __opsummonmonster_;
/*  308 */     this._playtype = __playtype_;
/*  309 */     this._playskill = __playskill_;
/*  310 */     this._playtip = __playtip_;
/*  311 */     this._playescape = __playescape_;
/*  312 */     this._playuseitem = __playuseitem_;
/*  313 */     this._playcapture = __playcapture_;
/*  314 */     this._playsummon = __playsummon_;
/*  315 */     this._playtalk = __playtalk_;
/*  316 */     this._playchangefightmap = __playchangefightmap_;
/*  317 */     this._playfighterstatus = __playfighterstatus_;
/*  318 */     this._playchangefighter = __playchangefighter_;
/*  319 */     this._playchangemodel = __playchangemodel_;
/*  320 */     this._bulletinparamkey = __bulletinparamkey_;
/*  321 */     this._petconsts = __petconsts_;
/*  322 */     this._systemsetting = __systemsetting_;
/*  323 */     this._roledeletestatus = __roledeletestatus_;
/*  324 */     this._gangbuildingenum = __gangbuildingenum_;
/*  325 */     this._instanceconst = __instanceconst_;
/*  326 */     this._jiuxiaoconsts = __jiuxiaoconsts_;
/*  327 */     this._menpaipvp_npcservice = __menpaipvp_npcservice_;
/*  328 */     this._arena_npcservice = __arena_npcservice_;
/*  329 */     this._competition_npcservice = __competition_npcservice_;
/*  330 */     this._const = __const_;
/*  331 */     this._petaptconst = __petaptconst_;
/*  332 */     this._idip = __idip_;
/*  333 */     this._marriageconst = __marriageconst_;
/*  334 */     this._guideconst = __guideconst_;
/*  335 */     this._mapmodelinfo = __mapmodelinfo_;
/*  336 */     this._npcmodelinfo = __npcmodelinfo_;
/*  337 */     this._marketstate = __marketstate_;
/*  338 */     this._mapgrouptype = __mapgrouptype_;
/*  339 */     this._mapentitytype = __mapentitytype_;
/*  340 */     this._mapentityextrainfotype = __mapentityextrainfotype_;
/*  341 */     this._qmhwconsts = __qmhwconsts_;
/*  342 */     this._mapgroupextrainfotype = __mapgroupextrainfotype_;
/*  343 */     this._grc_errorcodes = __grc_errorcodes_;
/*  344 */     this._grc_recallret = __grc_recallret_;
/*  345 */     this._qqvipflag = __qqvipflag_;
/*  346 */     this._shituconst = __shituconst_;
/*  347 */     this._raceconsts = __raceconsts_;
/*  348 */     this._coupledailyconst = __coupledailyconst_;
/*  349 */     this._idipntimesoperator = __idipntimesoperator_;
/*  350 */     this._apollo_errorcodes = __apollo_errorcodes_;
/*  351 */     this._apollolargeroomtype = __apollolargeroomtype_;
/*  352 */     this._apolloglobalroomtype = __apolloglobalroomtype_;
/*  353 */     this._qyxthelpstatus = __qyxthelpstatus_;
/*  354 */     this._fashiondressconst = __fashiondressconst_;
/*  355 */     this._fabaoconst = __fabaoconst_;
/*  356 */     this._conditionstate = __conditionstate_;
/*  357 */     this._achievementconst = __achievementconst_;
/*  358 */     this._backgameconst = __backgameconst_;
/*  359 */     this._personal = __personal_;
/*  360 */     this._activityconst = __activityconst_;
/*  361 */     this._advert = __advert_;
/*  362 */     this._qingyuanconst = __qingyuanconst_;
/*  363 */     this._loginawardconst = __loginawardconst_;
/*  364 */     this._massweddingconst = __massweddingconst_;
/*  365 */     this._catconst = __catconst_;
/*  366 */     this._mountsconst = __mountsconst_;
/*  367 */     this._doublepointswitchtype = __doublepointswitchtype_;
/*  368 */     this._luckybagconst = __luckybagconst_;
/*  369 */     this._recallfriendconst = __recallfriendconst_;
/*  370 */     this._apollo_voiproomtype = __apollo_voiproomtype_;
/*  371 */     this._apollo_voiproomaction = __apollo_voiproomaction_;
/*  372 */     this._popuptype = __popuptype_;
/*  373 */     this._massexpret = __massexpret_;
/*  374 */     this._monsterstate = __monsterstate_;
/*  375 */     this._hulaactivityphase = __hulaactivityphase_;
/*  376 */     this._ladderconst = __ladderconst_;
/*  377 */     this._babyperiodinfo = __babyperiodinfo_;
/*  378 */     this._childhoodinfo = __childhoodinfo_;
/*  379 */     this._adulthoodinfo = __adulthoodinfo_;
/*  380 */     this._childhoodret = __childhoodret_;
/*  381 */     this._childfashionret = __childfashionret_;
/*  382 */     this._childgrowthtype = __childgrowthtype_;
/*  383 */     this._childgrowthsubtype = __childgrowthsubtype_;
/*  384 */     this._watchmoonerrorcode = __watchmoonerrorcode_;
/*  385 */     this._qilinmode = __qilinmode_;
/*  386 */     this._memorycompetitionconst = __memorycompetitionconst_;
/*  387 */     this._menpaistarret = __menpaistarret_;
/*  388 */     this._geniusret = __geniusret_;
/*  389 */     this._blessret = __blessret_;
/*  390 */     this._exploitconsts = __exploitconsts_;
/*  391 */     this._zooret = __zooret_;
/*  392 */     this._embryostageinfo = __embryostageinfo_;
/*  393 */     this._adultstageinfo = __adultstageinfo_;
/*  394 */     this._drawandguessconst = __drawandguessconst_;
/*  395 */     this._crossbattleactivitystage = __crossbattleactivitystage_;
/*  396 */     this._crossbattlevoteranktype = __crossbattlevoteranktype_;
/*  397 */     this._roundrobinroundstage = __roundrobinroundstage_;
/*  398 */     this._crossbattleownerrorcode = __crossbattleownerrorcode_;
/*  399 */     this._crossbattlepointconst = __crossbattlepointconst_;
/*  400 */     this._crossbattlebeterrorcode = __crossbattlebeterrorcode_;
/*  401 */     this._crossbattleselectionconsts = __crossbattleselectionconsts_;
/*  402 */     this._getknockoutstagebetinforeason = __getknockoutstagebetinforeason_;
/*  403 */     this._crossbattlefinalconsts = __crossbattlefinalconsts_;
/*  404 */     this._crossfieldimportbean = __crossfieldimportbean_;
/*  405 */     this._jailaction = __jailaction_;
/*  406 */     this._questionvoiceconst = __questionvoiceconst_;
/*  407 */     this._sspreqtype = __sspreqtype_;
/*  408 */     this._crossbattlebetimportbean = __crossbattlebetimportbean_;
/*  409 */     this._aircraftdatainfo = __aircraftdatainfo_;
/*  410 */     this._indianaimportbean = __indianaimportbean_;
/*  411 */     this._alllottoimportbean = __alllottoimportbean_;
/*  412 */     this._cakeconsts = __cakeconsts_;
/*  413 */     this._fireworkconsts = __fireworkconsts_;
/*  414 */     this._petarenaret = __petarenaret_;
/*  415 */     this._bigbossimportbean = __bigbossimportbean_;
/*  416 */     this._ballbattleplayerstateenum = __ballbattleplayerstateenum_;
/*      */   }
/*      */   
/*      */   public final boolean _validator_() {
/*  420 */     if (!this._onlinestatus._validator_()) return false;
/*  421 */     if (!this._fighterstatus._validator_()) return false;
/*  422 */     if (!this._taskconsts._validator_()) return false;
/*  423 */     if (!this._chatconsts._validator_()) return false;
/*  424 */     if (!this._friendconsts._validator_()) return false;
/*  425 */     if (!this._mailconsts._validator_()) return false;
/*  426 */     if (!this._itemxstoretype._validator_()) return false;
/*  427 */     if (!this._itemsourceenum._validator_()) return false;
/*  428 */     if (!this._growconsts._validator_()) return false;
/*  429 */     if (!this._status_errorcode._validator_()) return false;
/*  430 */     if (!this._statusenum._validator_()) return false;
/*  431 */     if (!this._fightconsts._validator_()) return false;
/*  432 */     if (!this._opskill._validator_()) return false;
/*  433 */     if (!this._opitem._validator_()) return false;
/*  434 */     if (!this._opcapture._validator_()) return false;
/*  435 */     if (!this._opprotect._validator_()) return false;
/*  436 */     if (!this._opsummonpet._validator_()) return false;
/*  437 */     if (!this._opsummonchild._validator_()) return false;
/*  438 */     if (!this._opsummonmonster._validator_()) return false;
/*  439 */     if (!this._playtype._validator_()) return false;
/*  440 */     if (!this._playskill._validator_()) return false;
/*  441 */     if (!this._playtip._validator_()) return false;
/*  442 */     if (!this._playescape._validator_()) return false;
/*  443 */     if (!this._playuseitem._validator_()) return false;
/*  444 */     if (!this._playcapture._validator_()) return false;
/*  445 */     if (!this._playsummon._validator_()) return false;
/*  446 */     if (!this._playtalk._validator_()) return false;
/*  447 */     if (!this._playchangefightmap._validator_()) return false;
/*  448 */     if (!this._playfighterstatus._validator_()) return false;
/*  449 */     if (!this._playchangefighter._validator_()) return false;
/*  450 */     if (!this._playchangemodel._validator_()) return false;
/*  451 */     if (!this._bulletinparamkey._validator_()) return false;
/*  452 */     if (!this._petconsts._validator_()) return false;
/*  453 */     if (!this._systemsetting._validator_()) return false;
/*  454 */     if (!this._roledeletestatus._validator_()) return false;
/*  455 */     if (!this._gangbuildingenum._validator_()) return false;
/*  456 */     if (!this._instanceconst._validator_()) return false;
/*  457 */     if (!this._jiuxiaoconsts._validator_()) return false;
/*  458 */     if (!this._menpaipvp_npcservice._validator_()) return false;
/*  459 */     if (!this._arena_npcservice._validator_()) return false;
/*  460 */     if (!this._competition_npcservice._validator_()) return false;
/*  461 */     if (!this._const._validator_()) return false;
/*  462 */     if (!this._petaptconst._validator_()) return false;
/*  463 */     if (!this._idip._validator_()) return false;
/*  464 */     if (!this._marriageconst._validator_()) return false;
/*  465 */     if (!this._guideconst._validator_()) return false;
/*  466 */     if (!this._mapmodelinfo._validator_()) return false;
/*  467 */     if (!this._npcmodelinfo._validator_()) return false;
/*  468 */     if (!this._marketstate._validator_()) return false;
/*  469 */     if (!this._mapgrouptype._validator_()) return false;
/*  470 */     if (!this._mapentitytype._validator_()) return false;
/*  471 */     if (!this._mapentityextrainfotype._validator_()) return false;
/*  472 */     if (!this._qmhwconsts._validator_()) return false;
/*  473 */     if (!this._mapgroupextrainfotype._validator_()) return false;
/*  474 */     if (!this._grc_errorcodes._validator_()) return false;
/*  475 */     if (!this._grc_recallret._validator_()) return false;
/*  476 */     if (!this._qqvipflag._validator_()) return false;
/*  477 */     if (!this._shituconst._validator_()) return false;
/*  478 */     if (!this._raceconsts._validator_()) return false;
/*  479 */     if (!this._coupledailyconst._validator_()) return false;
/*  480 */     if (!this._idipntimesoperator._validator_()) return false;
/*  481 */     if (!this._apollo_errorcodes._validator_()) return false;
/*  482 */     if (!this._apollolargeroomtype._validator_()) return false;
/*  483 */     if (!this._apolloglobalroomtype._validator_()) return false;
/*  484 */     if (!this._qyxthelpstatus._validator_()) return false;
/*  485 */     if (!this._fashiondressconst._validator_()) return false;
/*  486 */     if (!this._fabaoconst._validator_()) return false;
/*  487 */     if (!this._conditionstate._validator_()) return false;
/*  488 */     if (!this._achievementconst._validator_()) return false;
/*  489 */     if (!this._backgameconst._validator_()) return false;
/*  490 */     if (!this._personal._validator_()) return false;
/*  491 */     if (!this._activityconst._validator_()) return false;
/*  492 */     if (!this._advert._validator_()) return false;
/*  493 */     if (!this._qingyuanconst._validator_()) return false;
/*  494 */     if (!this._loginawardconst._validator_()) return false;
/*  495 */     if (!this._massweddingconst._validator_()) return false;
/*  496 */     if (!this._catconst._validator_()) return false;
/*  497 */     if (!this._mountsconst._validator_()) return false;
/*  498 */     if (!this._doublepointswitchtype._validator_()) return false;
/*  499 */     if (!this._luckybagconst._validator_()) return false;
/*  500 */     if (!this._recallfriendconst._validator_()) return false;
/*  501 */     if (!this._apollo_voiproomtype._validator_()) return false;
/*  502 */     if (!this._apollo_voiproomaction._validator_()) return false;
/*  503 */     if (!this._popuptype._validator_()) return false;
/*  504 */     if (!this._massexpret._validator_()) return false;
/*  505 */     if (!this._monsterstate._validator_()) return false;
/*  506 */     if (!this._hulaactivityphase._validator_()) return false;
/*  507 */     if (!this._ladderconst._validator_()) return false;
/*  508 */     if (!this._babyperiodinfo._validator_()) return false;
/*  509 */     if (!this._childhoodinfo._validator_()) return false;
/*  510 */     if (!this._adulthoodinfo._validator_()) return false;
/*  511 */     if (!this._childhoodret._validator_()) return false;
/*  512 */     if (!this._childfashionret._validator_()) return false;
/*  513 */     if (!this._childgrowthtype._validator_()) return false;
/*  514 */     if (!this._childgrowthsubtype._validator_()) return false;
/*  515 */     if (!this._watchmoonerrorcode._validator_()) return false;
/*  516 */     if (!this._qilinmode._validator_()) return false;
/*  517 */     if (!this._memorycompetitionconst._validator_()) return false;
/*  518 */     if (!this._menpaistarret._validator_()) return false;
/*  519 */     if (!this._geniusret._validator_()) return false;
/*  520 */     if (!this._blessret._validator_()) return false;
/*  521 */     if (!this._exploitconsts._validator_()) return false;
/*  522 */     if (!this._zooret._validator_()) return false;
/*  523 */     if (!this._embryostageinfo._validator_()) return false;
/*  524 */     if (!this._adultstageinfo._validator_()) return false;
/*  525 */     if (!this._drawandguessconst._validator_()) return false;
/*  526 */     if (!this._crossbattleactivitystage._validator_()) return false;
/*  527 */     if (!this._crossbattlevoteranktype._validator_()) return false;
/*  528 */     if (!this._roundrobinroundstage._validator_()) return false;
/*  529 */     if (!this._crossbattleownerrorcode._validator_()) return false;
/*  530 */     if (!this._crossbattlepointconst._validator_()) return false;
/*  531 */     if (!this._crossbattlebeterrorcode._validator_()) return false;
/*  532 */     if (!this._crossbattleselectionconsts._validator_()) return false;
/*  533 */     if (!this._getknockoutstagebetinforeason._validator_()) return false;
/*  534 */     if (!this._crossbattlefinalconsts._validator_()) return false;
/*  535 */     if (!this._crossfieldimportbean._validator_()) return false;
/*  536 */     if (!this._jailaction._validator_()) return false;
/*  537 */     if (!this._questionvoiceconst._validator_()) return false;
/*  538 */     if (!this._sspreqtype._validator_()) return false;
/*  539 */     if (!this._crossbattlebetimportbean._validator_()) return false;
/*  540 */     if (!this._aircraftdatainfo._validator_()) return false;
/*  541 */     if (!this._indianaimportbean._validator_()) return false;
/*  542 */     if (!this._alllottoimportbean._validator_()) return false;
/*  543 */     if (!this._cakeconsts._validator_()) return false;
/*  544 */     if (!this._fireworkconsts._validator_()) return false;
/*  545 */     if (!this._petarenaret._validator_()) return false;
/*  546 */     if (!this._bigbossimportbean._validator_()) return false;
/*  547 */     if (!this._ballbattleplayerstateenum._validator_()) return false;
/*  548 */     return true;
/*      */   }
/*      */   
/*      */   public OctetsStream marshal(OctetsStream _os_) {
/*  552 */     _os_.marshal(this._onlinestatus);
/*  553 */     _os_.marshal(this._fighterstatus);
/*  554 */     _os_.marshal(this._taskconsts);
/*  555 */     _os_.marshal(this._chatconsts);
/*  556 */     _os_.marshal(this._friendconsts);
/*  557 */     _os_.marshal(this._mailconsts);
/*  558 */     _os_.marshal(this._itemxstoretype);
/*  559 */     _os_.marshal(this._itemsourceenum);
/*  560 */     _os_.marshal(this._growconsts);
/*  561 */     _os_.marshal(this._status_errorcode);
/*  562 */     _os_.marshal(this._statusenum);
/*  563 */     _os_.marshal(this._fightconsts);
/*  564 */     _os_.marshal(this._opskill);
/*  565 */     _os_.marshal(this._opitem);
/*  566 */     _os_.marshal(this._opcapture);
/*  567 */     _os_.marshal(this._opprotect);
/*  568 */     _os_.marshal(this._opsummonpet);
/*  569 */     _os_.marshal(this._opsummonchild);
/*  570 */     _os_.marshal(this._opsummonmonster);
/*  571 */     _os_.marshal(this._playtype);
/*  572 */     _os_.marshal(this._playskill);
/*  573 */     _os_.marshal(this._playtip);
/*  574 */     _os_.marshal(this._playescape);
/*  575 */     _os_.marshal(this._playuseitem);
/*  576 */     _os_.marshal(this._playcapture);
/*  577 */     _os_.marshal(this._playsummon);
/*  578 */     _os_.marshal(this._playtalk);
/*  579 */     _os_.marshal(this._playchangefightmap);
/*  580 */     _os_.marshal(this._playfighterstatus);
/*  581 */     _os_.marshal(this._playchangefighter);
/*  582 */     _os_.marshal(this._playchangemodel);
/*  583 */     _os_.marshal(this._bulletinparamkey);
/*  584 */     _os_.marshal(this._petconsts);
/*  585 */     _os_.marshal(this._systemsetting);
/*  586 */     _os_.marshal(this._roledeletestatus);
/*  587 */     _os_.marshal(this._gangbuildingenum);
/*  588 */     _os_.marshal(this._instanceconst);
/*  589 */     _os_.marshal(this._jiuxiaoconsts);
/*  590 */     _os_.marshal(this._menpaipvp_npcservice);
/*  591 */     _os_.marshal(this._arena_npcservice);
/*  592 */     _os_.marshal(this._competition_npcservice);
/*  593 */     _os_.marshal(this._const);
/*  594 */     _os_.marshal(this._petaptconst);
/*  595 */     _os_.marshal(this._idip);
/*  596 */     _os_.marshal(this._marriageconst);
/*  597 */     _os_.marshal(this._guideconst);
/*  598 */     _os_.marshal(this._mapmodelinfo);
/*  599 */     _os_.marshal(this._npcmodelinfo);
/*  600 */     _os_.marshal(this._marketstate);
/*  601 */     _os_.marshal(this._mapgrouptype);
/*  602 */     _os_.marshal(this._mapentitytype);
/*  603 */     _os_.marshal(this._mapentityextrainfotype);
/*  604 */     _os_.marshal(this._qmhwconsts);
/*  605 */     _os_.marshal(this._mapgroupextrainfotype);
/*  606 */     _os_.marshal(this._grc_errorcodes);
/*  607 */     _os_.marshal(this._grc_recallret);
/*  608 */     _os_.marshal(this._qqvipflag);
/*  609 */     _os_.marshal(this._shituconst);
/*  610 */     _os_.marshal(this._raceconsts);
/*  611 */     _os_.marshal(this._coupledailyconst);
/*  612 */     _os_.marshal(this._idipntimesoperator);
/*  613 */     _os_.marshal(this._apollo_errorcodes);
/*  614 */     _os_.marshal(this._apollolargeroomtype);
/*  615 */     _os_.marshal(this._apolloglobalroomtype);
/*  616 */     _os_.marshal(this._qyxthelpstatus);
/*  617 */     _os_.marshal(this._fashiondressconst);
/*  618 */     _os_.marshal(this._fabaoconst);
/*  619 */     _os_.marshal(this._conditionstate);
/*  620 */     _os_.marshal(this._achievementconst);
/*  621 */     _os_.marshal(this._backgameconst);
/*  622 */     _os_.marshal(this._personal);
/*  623 */     _os_.marshal(this._activityconst);
/*  624 */     _os_.marshal(this._advert);
/*  625 */     _os_.marshal(this._qingyuanconst);
/*  626 */     _os_.marshal(this._loginawardconst);
/*  627 */     _os_.marshal(this._massweddingconst);
/*  628 */     _os_.marshal(this._catconst);
/*  629 */     _os_.marshal(this._mountsconst);
/*  630 */     _os_.marshal(this._doublepointswitchtype);
/*  631 */     _os_.marshal(this._luckybagconst);
/*  632 */     _os_.marshal(this._recallfriendconst);
/*  633 */     _os_.marshal(this._apollo_voiproomtype);
/*  634 */     _os_.marshal(this._apollo_voiproomaction);
/*  635 */     _os_.marshal(this._popuptype);
/*  636 */     _os_.marshal(this._massexpret);
/*  637 */     _os_.marshal(this._monsterstate);
/*  638 */     _os_.marshal(this._hulaactivityphase);
/*  639 */     _os_.marshal(this._ladderconst);
/*  640 */     _os_.marshal(this._babyperiodinfo);
/*  641 */     _os_.marshal(this._childhoodinfo);
/*  642 */     _os_.marshal(this._adulthoodinfo);
/*  643 */     _os_.marshal(this._childhoodret);
/*  644 */     _os_.marshal(this._childfashionret);
/*  645 */     _os_.marshal(this._childgrowthtype);
/*  646 */     _os_.marshal(this._childgrowthsubtype);
/*  647 */     _os_.marshal(this._watchmoonerrorcode);
/*  648 */     _os_.marshal(this._qilinmode);
/*  649 */     _os_.marshal(this._memorycompetitionconst);
/*  650 */     _os_.marshal(this._menpaistarret);
/*  651 */     _os_.marshal(this._geniusret);
/*  652 */     _os_.marshal(this._blessret);
/*  653 */     _os_.marshal(this._exploitconsts);
/*  654 */     _os_.marshal(this._zooret);
/*  655 */     _os_.marshal(this._embryostageinfo);
/*  656 */     _os_.marshal(this._adultstageinfo);
/*  657 */     _os_.marshal(this._drawandguessconst);
/*  658 */     _os_.marshal(this._crossbattleactivitystage);
/*  659 */     _os_.marshal(this._crossbattlevoteranktype);
/*  660 */     _os_.marshal(this._roundrobinroundstage);
/*  661 */     _os_.marshal(this._crossbattleownerrorcode);
/*  662 */     _os_.marshal(this._crossbattlepointconst);
/*  663 */     _os_.marshal(this._crossbattlebeterrorcode);
/*  664 */     _os_.marshal(this._crossbattleselectionconsts);
/*  665 */     _os_.marshal(this._getknockoutstagebetinforeason);
/*  666 */     _os_.marshal(this._crossbattlefinalconsts);
/*  667 */     _os_.marshal(this._crossfieldimportbean);
/*  668 */     _os_.marshal(this._jailaction);
/*  669 */     _os_.marshal(this._questionvoiceconst);
/*  670 */     _os_.marshal(this._sspreqtype);
/*  671 */     _os_.marshal(this._crossbattlebetimportbean);
/*  672 */     _os_.marshal(this._aircraftdatainfo);
/*  673 */     _os_.marshal(this._indianaimportbean);
/*  674 */     _os_.marshal(this._alllottoimportbean);
/*  675 */     _os_.marshal(this._cakeconsts);
/*  676 */     _os_.marshal(this._fireworkconsts);
/*  677 */     _os_.marshal(this._petarenaret);
/*  678 */     _os_.marshal(this._bigbossimportbean);
/*  679 */     _os_.marshal(this._ballbattleplayerstateenum);
/*  680 */     return _os_;
/*      */   }
/*      */   
/*      */   public OctetsStream unmarshal(OctetsStream _os_) throws com.goldhuman.Common.Marshal.MarshalException {
/*  684 */     this._onlinestatus.unmarshal(_os_);
/*  685 */     this._fighterstatus.unmarshal(_os_);
/*  686 */     this._taskconsts.unmarshal(_os_);
/*  687 */     this._chatconsts.unmarshal(_os_);
/*  688 */     this._friendconsts.unmarshal(_os_);
/*  689 */     this._mailconsts.unmarshal(_os_);
/*  690 */     this._itemxstoretype.unmarshal(_os_);
/*  691 */     this._itemsourceenum.unmarshal(_os_);
/*  692 */     this._growconsts.unmarshal(_os_);
/*  693 */     this._status_errorcode.unmarshal(_os_);
/*  694 */     this._statusenum.unmarshal(_os_);
/*  695 */     this._fightconsts.unmarshal(_os_);
/*  696 */     this._opskill.unmarshal(_os_);
/*  697 */     this._opitem.unmarshal(_os_);
/*  698 */     this._opcapture.unmarshal(_os_);
/*  699 */     this._opprotect.unmarshal(_os_);
/*  700 */     this._opsummonpet.unmarshal(_os_);
/*  701 */     this._opsummonchild.unmarshal(_os_);
/*  702 */     this._opsummonmonster.unmarshal(_os_);
/*  703 */     this._playtype.unmarshal(_os_);
/*  704 */     this._playskill.unmarshal(_os_);
/*  705 */     this._playtip.unmarshal(_os_);
/*  706 */     this._playescape.unmarshal(_os_);
/*  707 */     this._playuseitem.unmarshal(_os_);
/*  708 */     this._playcapture.unmarshal(_os_);
/*  709 */     this._playsummon.unmarshal(_os_);
/*  710 */     this._playtalk.unmarshal(_os_);
/*  711 */     this._playchangefightmap.unmarshal(_os_);
/*  712 */     this._playfighterstatus.unmarshal(_os_);
/*  713 */     this._playchangefighter.unmarshal(_os_);
/*  714 */     this._playchangemodel.unmarshal(_os_);
/*  715 */     this._bulletinparamkey.unmarshal(_os_);
/*  716 */     this._petconsts.unmarshal(_os_);
/*  717 */     this._systemsetting.unmarshal(_os_);
/*  718 */     this._roledeletestatus.unmarshal(_os_);
/*  719 */     this._gangbuildingenum.unmarshal(_os_);
/*  720 */     this._instanceconst.unmarshal(_os_);
/*  721 */     this._jiuxiaoconsts.unmarshal(_os_);
/*  722 */     this._menpaipvp_npcservice.unmarshal(_os_);
/*  723 */     this._arena_npcservice.unmarshal(_os_);
/*  724 */     this._competition_npcservice.unmarshal(_os_);
/*  725 */     this._const.unmarshal(_os_);
/*  726 */     this._petaptconst.unmarshal(_os_);
/*  727 */     this._idip.unmarshal(_os_);
/*  728 */     this._marriageconst.unmarshal(_os_);
/*  729 */     this._guideconst.unmarshal(_os_);
/*  730 */     this._mapmodelinfo.unmarshal(_os_);
/*  731 */     this._npcmodelinfo.unmarshal(_os_);
/*  732 */     this._marketstate.unmarshal(_os_);
/*  733 */     this._mapgrouptype.unmarshal(_os_);
/*  734 */     this._mapentitytype.unmarshal(_os_);
/*  735 */     this._mapentityextrainfotype.unmarshal(_os_);
/*  736 */     this._qmhwconsts.unmarshal(_os_);
/*  737 */     this._mapgroupextrainfotype.unmarshal(_os_);
/*  738 */     this._grc_errorcodes.unmarshal(_os_);
/*  739 */     this._grc_recallret.unmarshal(_os_);
/*  740 */     this._qqvipflag.unmarshal(_os_);
/*  741 */     this._shituconst.unmarshal(_os_);
/*  742 */     this._raceconsts.unmarshal(_os_);
/*  743 */     this._coupledailyconst.unmarshal(_os_);
/*  744 */     this._idipntimesoperator.unmarshal(_os_);
/*  745 */     this._apollo_errorcodes.unmarshal(_os_);
/*  746 */     this._apollolargeroomtype.unmarshal(_os_);
/*  747 */     this._apolloglobalroomtype.unmarshal(_os_);
/*  748 */     this._qyxthelpstatus.unmarshal(_os_);
/*  749 */     this._fashiondressconst.unmarshal(_os_);
/*  750 */     this._fabaoconst.unmarshal(_os_);
/*  751 */     this._conditionstate.unmarshal(_os_);
/*  752 */     this._achievementconst.unmarshal(_os_);
/*  753 */     this._backgameconst.unmarshal(_os_);
/*  754 */     this._personal.unmarshal(_os_);
/*  755 */     this._activityconst.unmarshal(_os_);
/*  756 */     this._advert.unmarshal(_os_);
/*  757 */     this._qingyuanconst.unmarshal(_os_);
/*  758 */     this._loginawardconst.unmarshal(_os_);
/*  759 */     this._massweddingconst.unmarshal(_os_);
/*  760 */     this._catconst.unmarshal(_os_);
/*  761 */     this._mountsconst.unmarshal(_os_);
/*  762 */     this._doublepointswitchtype.unmarshal(_os_);
/*  763 */     this._luckybagconst.unmarshal(_os_);
/*  764 */     this._recallfriendconst.unmarshal(_os_);
/*  765 */     this._apollo_voiproomtype.unmarshal(_os_);
/*  766 */     this._apollo_voiproomaction.unmarshal(_os_);
/*  767 */     this._popuptype.unmarshal(_os_);
/*  768 */     this._massexpret.unmarshal(_os_);
/*  769 */     this._monsterstate.unmarshal(_os_);
/*  770 */     this._hulaactivityphase.unmarshal(_os_);
/*  771 */     this._ladderconst.unmarshal(_os_);
/*  772 */     this._babyperiodinfo.unmarshal(_os_);
/*  773 */     this._childhoodinfo.unmarshal(_os_);
/*  774 */     this._adulthoodinfo.unmarshal(_os_);
/*  775 */     this._childhoodret.unmarshal(_os_);
/*  776 */     this._childfashionret.unmarshal(_os_);
/*  777 */     this._childgrowthtype.unmarshal(_os_);
/*  778 */     this._childgrowthsubtype.unmarshal(_os_);
/*  779 */     this._watchmoonerrorcode.unmarshal(_os_);
/*  780 */     this._qilinmode.unmarshal(_os_);
/*  781 */     this._memorycompetitionconst.unmarshal(_os_);
/*  782 */     this._menpaistarret.unmarshal(_os_);
/*  783 */     this._geniusret.unmarshal(_os_);
/*  784 */     this._blessret.unmarshal(_os_);
/*  785 */     this._exploitconsts.unmarshal(_os_);
/*  786 */     this._zooret.unmarshal(_os_);
/*  787 */     this._embryostageinfo.unmarshal(_os_);
/*  788 */     this._adultstageinfo.unmarshal(_os_);
/*  789 */     this._drawandguessconst.unmarshal(_os_);
/*  790 */     this._crossbattleactivitystage.unmarshal(_os_);
/*  791 */     this._crossbattlevoteranktype.unmarshal(_os_);
/*  792 */     this._roundrobinroundstage.unmarshal(_os_);
/*  793 */     this._crossbattleownerrorcode.unmarshal(_os_);
/*  794 */     this._crossbattlepointconst.unmarshal(_os_);
/*  795 */     this._crossbattlebeterrorcode.unmarshal(_os_);
/*  796 */     this._crossbattleselectionconsts.unmarshal(_os_);
/*  797 */     this._getknockoutstagebetinforeason.unmarshal(_os_);
/*  798 */     this._crossbattlefinalconsts.unmarshal(_os_);
/*  799 */     this._crossfieldimportbean.unmarshal(_os_);
/*  800 */     this._jailaction.unmarshal(_os_);
/*  801 */     this._questionvoiceconst.unmarshal(_os_);
/*  802 */     this._sspreqtype.unmarshal(_os_);
/*  803 */     this._crossbattlebetimportbean.unmarshal(_os_);
/*  804 */     this._aircraftdatainfo.unmarshal(_os_);
/*  805 */     this._indianaimportbean.unmarshal(_os_);
/*  806 */     this._alllottoimportbean.unmarshal(_os_);
/*  807 */     this._cakeconsts.unmarshal(_os_);
/*  808 */     this._fireworkconsts.unmarshal(_os_);
/*  809 */     this._petarenaret.unmarshal(_os_);
/*  810 */     this._bigbossimportbean.unmarshal(_os_);
/*  811 */     this._ballbattleplayerstateenum.unmarshal(_os_);
/*  812 */     if (!_validator_()) {
/*  813 */       throw new VerifyError("validator failed");
/*      */     }
/*  815 */     return _os_;
/*      */   }
/*      */   
/*      */   public boolean equals(Object _o1_) {
/*  819 */     if (_o1_ == this) return true;
/*  820 */     if ((_o1_ instanceof BeanImport)) {
/*  821 */       BeanImport _o_ = (BeanImport)_o1_;
/*  822 */       if (!this._onlinestatus.equals(_o_._onlinestatus)) return false;
/*  823 */       if (!this._fighterstatus.equals(_o_._fighterstatus)) return false;
/*  824 */       if (!this._taskconsts.equals(_o_._taskconsts)) return false;
/*  825 */       if (!this._chatconsts.equals(_o_._chatconsts)) return false;
/*  826 */       if (!this._friendconsts.equals(_o_._friendconsts)) return false;
/*  827 */       if (!this._mailconsts.equals(_o_._mailconsts)) return false;
/*  828 */       if (!this._itemxstoretype.equals(_o_._itemxstoretype)) return false;
/*  829 */       if (!this._itemsourceenum.equals(_o_._itemsourceenum)) return false;
/*  830 */       if (!this._growconsts.equals(_o_._growconsts)) return false;
/*  831 */       if (!this._status_errorcode.equals(_o_._status_errorcode)) return false;
/*  832 */       if (!this._statusenum.equals(_o_._statusenum)) return false;
/*  833 */       if (!this._fightconsts.equals(_o_._fightconsts)) return false;
/*  834 */       if (!this._opskill.equals(_o_._opskill)) return false;
/*  835 */       if (!this._opitem.equals(_o_._opitem)) return false;
/*  836 */       if (!this._opcapture.equals(_o_._opcapture)) return false;
/*  837 */       if (!this._opprotect.equals(_o_._opprotect)) return false;
/*  838 */       if (!this._opsummonpet.equals(_o_._opsummonpet)) return false;
/*  839 */       if (!this._opsummonchild.equals(_o_._opsummonchild)) return false;
/*  840 */       if (!this._opsummonmonster.equals(_o_._opsummonmonster)) return false;
/*  841 */       if (!this._playtype.equals(_o_._playtype)) return false;
/*  842 */       if (!this._playskill.equals(_o_._playskill)) return false;
/*  843 */       if (!this._playtip.equals(_o_._playtip)) return false;
/*  844 */       if (!this._playescape.equals(_o_._playescape)) return false;
/*  845 */       if (!this._playuseitem.equals(_o_._playuseitem)) return false;
/*  846 */       if (!this._playcapture.equals(_o_._playcapture)) return false;
/*  847 */       if (!this._playsummon.equals(_o_._playsummon)) return false;
/*  848 */       if (!this._playtalk.equals(_o_._playtalk)) return false;
/*  849 */       if (!this._playchangefightmap.equals(_o_._playchangefightmap)) return false;
/*  850 */       if (!this._playfighterstatus.equals(_o_._playfighterstatus)) return false;
/*  851 */       if (!this._playchangefighter.equals(_o_._playchangefighter)) return false;
/*  852 */       if (!this._playchangemodel.equals(_o_._playchangemodel)) return false;
/*  853 */       if (!this._bulletinparamkey.equals(_o_._bulletinparamkey)) return false;
/*  854 */       if (!this._petconsts.equals(_o_._petconsts)) return false;
/*  855 */       if (!this._systemsetting.equals(_o_._systemsetting)) return false;
/*  856 */       if (!this._roledeletestatus.equals(_o_._roledeletestatus)) return false;
/*  857 */       if (!this._gangbuildingenum.equals(_o_._gangbuildingenum)) return false;
/*  858 */       if (!this._instanceconst.equals(_o_._instanceconst)) return false;
/*  859 */       if (!this._jiuxiaoconsts.equals(_o_._jiuxiaoconsts)) return false;
/*  860 */       if (!this._menpaipvp_npcservice.equals(_o_._menpaipvp_npcservice)) return false;
/*  861 */       if (!this._arena_npcservice.equals(_o_._arena_npcservice)) return false;
/*  862 */       if (!this._competition_npcservice.equals(_o_._competition_npcservice)) return false;
/*  863 */       if (!this._const.equals(_o_._const)) return false;
/*  864 */       if (!this._petaptconst.equals(_o_._petaptconst)) return false;
/*  865 */       if (!this._idip.equals(_o_._idip)) return false;
/*  866 */       if (!this._marriageconst.equals(_o_._marriageconst)) return false;
/*  867 */       if (!this._guideconst.equals(_o_._guideconst)) return false;
/*  868 */       if (!this._mapmodelinfo.equals(_o_._mapmodelinfo)) return false;
/*  869 */       if (!this._npcmodelinfo.equals(_o_._npcmodelinfo)) return false;
/*  870 */       if (!this._marketstate.equals(_o_._marketstate)) return false;
/*  871 */       if (!this._mapgrouptype.equals(_o_._mapgrouptype)) return false;
/*  872 */       if (!this._mapentitytype.equals(_o_._mapentitytype)) return false;
/*  873 */       if (!this._mapentityextrainfotype.equals(_o_._mapentityextrainfotype)) return false;
/*  874 */       if (!this._qmhwconsts.equals(_o_._qmhwconsts)) return false;
/*  875 */       if (!this._mapgroupextrainfotype.equals(_o_._mapgroupextrainfotype)) return false;
/*  876 */       if (!this._grc_errorcodes.equals(_o_._grc_errorcodes)) return false;
/*  877 */       if (!this._grc_recallret.equals(_o_._grc_recallret)) return false;
/*  878 */       if (!this._qqvipflag.equals(_o_._qqvipflag)) return false;
/*  879 */       if (!this._shituconst.equals(_o_._shituconst)) return false;
/*  880 */       if (!this._raceconsts.equals(_o_._raceconsts)) return false;
/*  881 */       if (!this._coupledailyconst.equals(_o_._coupledailyconst)) return false;
/*  882 */       if (!this._idipntimesoperator.equals(_o_._idipntimesoperator)) return false;
/*  883 */       if (!this._apollo_errorcodes.equals(_o_._apollo_errorcodes)) return false;
/*  884 */       if (!this._apollolargeroomtype.equals(_o_._apollolargeroomtype)) return false;
/*  885 */       if (!this._apolloglobalroomtype.equals(_o_._apolloglobalroomtype)) return false;
/*  886 */       if (!this._qyxthelpstatus.equals(_o_._qyxthelpstatus)) return false;
/*  887 */       if (!this._fashiondressconst.equals(_o_._fashiondressconst)) return false;
/*  888 */       if (!this._fabaoconst.equals(_o_._fabaoconst)) return false;
/*  889 */       if (!this._conditionstate.equals(_o_._conditionstate)) return false;
/*  890 */       if (!this._achievementconst.equals(_o_._achievementconst)) return false;
/*  891 */       if (!this._backgameconst.equals(_o_._backgameconst)) return false;
/*  892 */       if (!this._personal.equals(_o_._personal)) return false;
/*  893 */       if (!this._activityconst.equals(_o_._activityconst)) return false;
/*  894 */       if (!this._advert.equals(_o_._advert)) return false;
/*  895 */       if (!this._qingyuanconst.equals(_o_._qingyuanconst)) return false;
/*  896 */       if (!this._loginawardconst.equals(_o_._loginawardconst)) return false;
/*  897 */       if (!this._massweddingconst.equals(_o_._massweddingconst)) return false;
/*  898 */       if (!this._catconst.equals(_o_._catconst)) return false;
/*  899 */       if (!this._mountsconst.equals(_o_._mountsconst)) return false;
/*  900 */       if (!this._doublepointswitchtype.equals(_o_._doublepointswitchtype)) return false;
/*  901 */       if (!this._luckybagconst.equals(_o_._luckybagconst)) return false;
/*  902 */       if (!this._recallfriendconst.equals(_o_._recallfriendconst)) return false;
/*  903 */       if (!this._apollo_voiproomtype.equals(_o_._apollo_voiproomtype)) return false;
/*  904 */       if (!this._apollo_voiproomaction.equals(_o_._apollo_voiproomaction)) return false;
/*  905 */       if (!this._popuptype.equals(_o_._popuptype)) return false;
/*  906 */       if (!this._massexpret.equals(_o_._massexpret)) return false;
/*  907 */       if (!this._monsterstate.equals(_o_._monsterstate)) return false;
/*  908 */       if (!this._hulaactivityphase.equals(_o_._hulaactivityphase)) return false;
/*  909 */       if (!this._ladderconst.equals(_o_._ladderconst)) return false;
/*  910 */       if (!this._babyperiodinfo.equals(_o_._babyperiodinfo)) return false;
/*  911 */       if (!this._childhoodinfo.equals(_o_._childhoodinfo)) return false;
/*  912 */       if (!this._adulthoodinfo.equals(_o_._adulthoodinfo)) return false;
/*  913 */       if (!this._childhoodret.equals(_o_._childhoodret)) return false;
/*  914 */       if (!this._childfashionret.equals(_o_._childfashionret)) return false;
/*  915 */       if (!this._childgrowthtype.equals(_o_._childgrowthtype)) return false;
/*  916 */       if (!this._childgrowthsubtype.equals(_o_._childgrowthsubtype)) return false;
/*  917 */       if (!this._watchmoonerrorcode.equals(_o_._watchmoonerrorcode)) return false;
/*  918 */       if (!this._qilinmode.equals(_o_._qilinmode)) return false;
/*  919 */       if (!this._memorycompetitionconst.equals(_o_._memorycompetitionconst)) return false;
/*  920 */       if (!this._menpaistarret.equals(_o_._menpaistarret)) return false;
/*  921 */       if (!this._geniusret.equals(_o_._geniusret)) return false;
/*  922 */       if (!this._blessret.equals(_o_._blessret)) return false;
/*  923 */       if (!this._exploitconsts.equals(_o_._exploitconsts)) return false;
/*  924 */       if (!this._zooret.equals(_o_._zooret)) return false;
/*  925 */       if (!this._embryostageinfo.equals(_o_._embryostageinfo)) return false;
/*  926 */       if (!this._adultstageinfo.equals(_o_._adultstageinfo)) return false;
/*  927 */       if (!this._drawandguessconst.equals(_o_._drawandguessconst)) return false;
/*  928 */       if (!this._crossbattleactivitystage.equals(_o_._crossbattleactivitystage)) return false;
/*  929 */       if (!this._crossbattlevoteranktype.equals(_o_._crossbattlevoteranktype)) return false;
/*  930 */       if (!this._roundrobinroundstage.equals(_o_._roundrobinroundstage)) return false;
/*  931 */       if (!this._crossbattleownerrorcode.equals(_o_._crossbattleownerrorcode)) return false;
/*  932 */       if (!this._crossbattlepointconst.equals(_o_._crossbattlepointconst)) return false;
/*  933 */       if (!this._crossbattlebeterrorcode.equals(_o_._crossbattlebeterrorcode)) return false;
/*  934 */       if (!this._crossbattleselectionconsts.equals(_o_._crossbattleselectionconsts)) return false;
/*  935 */       if (!this._getknockoutstagebetinforeason.equals(_o_._getknockoutstagebetinforeason)) return false;
/*  936 */       if (!this._crossbattlefinalconsts.equals(_o_._crossbattlefinalconsts)) return false;
/*  937 */       if (!this._crossfieldimportbean.equals(_o_._crossfieldimportbean)) return false;
/*  938 */       if (!this._jailaction.equals(_o_._jailaction)) return false;
/*  939 */       if (!this._questionvoiceconst.equals(_o_._questionvoiceconst)) return false;
/*  940 */       if (!this._sspreqtype.equals(_o_._sspreqtype)) return false;
/*  941 */       if (!this._crossbattlebetimportbean.equals(_o_._crossbattlebetimportbean)) return false;
/*  942 */       if (!this._aircraftdatainfo.equals(_o_._aircraftdatainfo)) return false;
/*  943 */       if (!this._indianaimportbean.equals(_o_._indianaimportbean)) return false;
/*  944 */       if (!this._alllottoimportbean.equals(_o_._alllottoimportbean)) return false;
/*  945 */       if (!this._cakeconsts.equals(_o_._cakeconsts)) return false;
/*  946 */       if (!this._fireworkconsts.equals(_o_._fireworkconsts)) return false;
/*  947 */       if (!this._petarenaret.equals(_o_._petarenaret)) return false;
/*  948 */       if (!this._bigbossimportbean.equals(_o_._bigbossimportbean)) return false;
/*  949 */       if (!this._ballbattleplayerstateenum.equals(_o_._ballbattleplayerstateenum)) return false;
/*  950 */       return true;
/*      */     }
/*  952 */     return false;
/*      */   }
/*      */   
/*      */   public int hashCode() {
/*  956 */     int _h_ = 0;
/*  957 */     _h_ += this._onlinestatus.hashCode();
/*  958 */     _h_ += this._fighterstatus.hashCode();
/*  959 */     _h_ += this._taskconsts.hashCode();
/*  960 */     _h_ += this._chatconsts.hashCode();
/*  961 */     _h_ += this._friendconsts.hashCode();
/*  962 */     _h_ += this._mailconsts.hashCode();
/*  963 */     _h_ += this._itemxstoretype.hashCode();
/*  964 */     _h_ += this._itemsourceenum.hashCode();
/*  965 */     _h_ += this._growconsts.hashCode();
/*  966 */     _h_ += this._status_errorcode.hashCode();
/*  967 */     _h_ += this._statusenum.hashCode();
/*  968 */     _h_ += this._fightconsts.hashCode();
/*  969 */     _h_ += this._opskill.hashCode();
/*  970 */     _h_ += this._opitem.hashCode();
/*  971 */     _h_ += this._opcapture.hashCode();
/*  972 */     _h_ += this._opprotect.hashCode();
/*  973 */     _h_ += this._opsummonpet.hashCode();
/*  974 */     _h_ += this._opsummonchild.hashCode();
/*  975 */     _h_ += this._opsummonmonster.hashCode();
/*  976 */     _h_ += this._playtype.hashCode();
/*  977 */     _h_ += this._playskill.hashCode();
/*  978 */     _h_ += this._playtip.hashCode();
/*  979 */     _h_ += this._playescape.hashCode();
/*  980 */     _h_ += this._playuseitem.hashCode();
/*  981 */     _h_ += this._playcapture.hashCode();
/*  982 */     _h_ += this._playsummon.hashCode();
/*  983 */     _h_ += this._playtalk.hashCode();
/*  984 */     _h_ += this._playchangefightmap.hashCode();
/*  985 */     _h_ += this._playfighterstatus.hashCode();
/*  986 */     _h_ += this._playchangefighter.hashCode();
/*  987 */     _h_ += this._playchangemodel.hashCode();
/*  988 */     _h_ += this._bulletinparamkey.hashCode();
/*  989 */     _h_ += this._petconsts.hashCode();
/*  990 */     _h_ += this._systemsetting.hashCode();
/*  991 */     _h_ += this._roledeletestatus.hashCode();
/*  992 */     _h_ += this._gangbuildingenum.hashCode();
/*  993 */     _h_ += this._instanceconst.hashCode();
/*  994 */     _h_ += this._jiuxiaoconsts.hashCode();
/*  995 */     _h_ += this._menpaipvp_npcservice.hashCode();
/*  996 */     _h_ += this._arena_npcservice.hashCode();
/*  997 */     _h_ += this._competition_npcservice.hashCode();
/*  998 */     _h_ += this._const.hashCode();
/*  999 */     _h_ += this._petaptconst.hashCode();
/* 1000 */     _h_ += this._idip.hashCode();
/* 1001 */     _h_ += this._marriageconst.hashCode();
/* 1002 */     _h_ += this._guideconst.hashCode();
/* 1003 */     _h_ += this._mapmodelinfo.hashCode();
/* 1004 */     _h_ += this._npcmodelinfo.hashCode();
/* 1005 */     _h_ += this._marketstate.hashCode();
/* 1006 */     _h_ += this._mapgrouptype.hashCode();
/* 1007 */     _h_ += this._mapentitytype.hashCode();
/* 1008 */     _h_ += this._mapentityextrainfotype.hashCode();
/* 1009 */     _h_ += this._qmhwconsts.hashCode();
/* 1010 */     _h_ += this._mapgroupextrainfotype.hashCode();
/* 1011 */     _h_ += this._grc_errorcodes.hashCode();
/* 1012 */     _h_ += this._grc_recallret.hashCode();
/* 1013 */     _h_ += this._qqvipflag.hashCode();
/* 1014 */     _h_ += this._shituconst.hashCode();
/* 1015 */     _h_ += this._raceconsts.hashCode();
/* 1016 */     _h_ += this._coupledailyconst.hashCode();
/* 1017 */     _h_ += this._idipntimesoperator.hashCode();
/* 1018 */     _h_ += this._apollo_errorcodes.hashCode();
/* 1019 */     _h_ += this._apollolargeroomtype.hashCode();
/* 1020 */     _h_ += this._apolloglobalroomtype.hashCode();
/* 1021 */     _h_ += this._qyxthelpstatus.hashCode();
/* 1022 */     _h_ += this._fashiondressconst.hashCode();
/* 1023 */     _h_ += this._fabaoconst.hashCode();
/* 1024 */     _h_ += this._conditionstate.hashCode();
/* 1025 */     _h_ += this._achievementconst.hashCode();
/* 1026 */     _h_ += this._backgameconst.hashCode();
/* 1027 */     _h_ += this._personal.hashCode();
/* 1028 */     _h_ += this._activityconst.hashCode();
/* 1029 */     _h_ += this._advert.hashCode();
/* 1030 */     _h_ += this._qingyuanconst.hashCode();
/* 1031 */     _h_ += this._loginawardconst.hashCode();
/* 1032 */     _h_ += this._massweddingconst.hashCode();
/* 1033 */     _h_ += this._catconst.hashCode();
/* 1034 */     _h_ += this._mountsconst.hashCode();
/* 1035 */     _h_ += this._doublepointswitchtype.hashCode();
/* 1036 */     _h_ += this._luckybagconst.hashCode();
/* 1037 */     _h_ += this._recallfriendconst.hashCode();
/* 1038 */     _h_ += this._apollo_voiproomtype.hashCode();
/* 1039 */     _h_ += this._apollo_voiproomaction.hashCode();
/* 1040 */     _h_ += this._popuptype.hashCode();
/* 1041 */     _h_ += this._massexpret.hashCode();
/* 1042 */     _h_ += this._monsterstate.hashCode();
/* 1043 */     _h_ += this._hulaactivityphase.hashCode();
/* 1044 */     _h_ += this._ladderconst.hashCode();
/* 1045 */     _h_ += this._babyperiodinfo.hashCode();
/* 1046 */     _h_ += this._childhoodinfo.hashCode();
/* 1047 */     _h_ += this._adulthoodinfo.hashCode();
/* 1048 */     _h_ += this._childhoodret.hashCode();
/* 1049 */     _h_ += this._childfashionret.hashCode();
/* 1050 */     _h_ += this._childgrowthtype.hashCode();
/* 1051 */     _h_ += this._childgrowthsubtype.hashCode();
/* 1052 */     _h_ += this._watchmoonerrorcode.hashCode();
/* 1053 */     _h_ += this._qilinmode.hashCode();
/* 1054 */     _h_ += this._memorycompetitionconst.hashCode();
/* 1055 */     _h_ += this._menpaistarret.hashCode();
/* 1056 */     _h_ += this._geniusret.hashCode();
/* 1057 */     _h_ += this._blessret.hashCode();
/* 1058 */     _h_ += this._exploitconsts.hashCode();
/* 1059 */     _h_ += this._zooret.hashCode();
/* 1060 */     _h_ += this._embryostageinfo.hashCode();
/* 1061 */     _h_ += this._adultstageinfo.hashCode();
/* 1062 */     _h_ += this._drawandguessconst.hashCode();
/* 1063 */     _h_ += this._crossbattleactivitystage.hashCode();
/* 1064 */     _h_ += this._crossbattlevoteranktype.hashCode();
/* 1065 */     _h_ += this._roundrobinroundstage.hashCode();
/* 1066 */     _h_ += this._crossbattleownerrorcode.hashCode();
/* 1067 */     _h_ += this._crossbattlepointconst.hashCode();
/* 1068 */     _h_ += this._crossbattlebeterrorcode.hashCode();
/* 1069 */     _h_ += this._crossbattleselectionconsts.hashCode();
/* 1070 */     _h_ += this._getknockoutstagebetinforeason.hashCode();
/* 1071 */     _h_ += this._crossbattlefinalconsts.hashCode();
/* 1072 */     _h_ += this._crossfieldimportbean.hashCode();
/* 1073 */     _h_ += this._jailaction.hashCode();
/* 1074 */     _h_ += this._questionvoiceconst.hashCode();
/* 1075 */     _h_ += this._sspreqtype.hashCode();
/* 1076 */     _h_ += this._crossbattlebetimportbean.hashCode();
/* 1077 */     _h_ += this._aircraftdatainfo.hashCode();
/* 1078 */     _h_ += this._indianaimportbean.hashCode();
/* 1079 */     _h_ += this._alllottoimportbean.hashCode();
/* 1080 */     _h_ += this._cakeconsts.hashCode();
/* 1081 */     _h_ += this._fireworkconsts.hashCode();
/* 1082 */     _h_ += this._petarenaret.hashCode();
/* 1083 */     _h_ += this._bigbossimportbean.hashCode();
/* 1084 */     _h_ += this._ballbattleplayerstateenum.hashCode();
/* 1085 */     return _h_;
/*      */   }
/*      */   
/*      */   public String toString() {
/* 1089 */     StringBuilder _sb_ = new StringBuilder();
/* 1090 */     _sb_.append("(");
/* 1091 */     _sb_.append(this._onlinestatus).append(",");
/* 1092 */     _sb_.append(this._fighterstatus).append(",");
/* 1093 */     _sb_.append(this._taskconsts).append(",");
/* 1094 */     _sb_.append(this._chatconsts).append(",");
/* 1095 */     _sb_.append(this._friendconsts).append(",");
/* 1096 */     _sb_.append(this._mailconsts).append(",");
/* 1097 */     _sb_.append(this._itemxstoretype).append(",");
/* 1098 */     _sb_.append(this._itemsourceenum).append(",");
/* 1099 */     _sb_.append(this._growconsts).append(",");
/* 1100 */     _sb_.append(this._status_errorcode).append(",");
/* 1101 */     _sb_.append(this._statusenum).append(",");
/* 1102 */     _sb_.append(this._fightconsts).append(",");
/* 1103 */     _sb_.append(this._opskill).append(",");
/* 1104 */     _sb_.append(this._opitem).append(",");
/* 1105 */     _sb_.append(this._opcapture).append(",");
/* 1106 */     _sb_.append(this._opprotect).append(",");
/* 1107 */     _sb_.append(this._opsummonpet).append(",");
/* 1108 */     _sb_.append(this._opsummonchild).append(",");
/* 1109 */     _sb_.append(this._opsummonmonster).append(",");
/* 1110 */     _sb_.append(this._playtype).append(",");
/* 1111 */     _sb_.append(this._playskill).append(",");
/* 1112 */     _sb_.append(this._playtip).append(",");
/* 1113 */     _sb_.append(this._playescape).append(",");
/* 1114 */     _sb_.append(this._playuseitem).append(",");
/* 1115 */     _sb_.append(this._playcapture).append(",");
/* 1116 */     _sb_.append(this._playsummon).append(",");
/* 1117 */     _sb_.append(this._playtalk).append(",");
/* 1118 */     _sb_.append(this._playchangefightmap).append(",");
/* 1119 */     _sb_.append(this._playfighterstatus).append(",");
/* 1120 */     _sb_.append(this._playchangefighter).append(",");
/* 1121 */     _sb_.append(this._playchangemodel).append(",");
/* 1122 */     _sb_.append(this._bulletinparamkey).append(",");
/* 1123 */     _sb_.append(this._petconsts).append(",");
/* 1124 */     _sb_.append(this._systemsetting).append(",");
/* 1125 */     _sb_.append(this._roledeletestatus).append(",");
/* 1126 */     _sb_.append(this._gangbuildingenum).append(",");
/* 1127 */     _sb_.append(this._instanceconst).append(",");
/* 1128 */     _sb_.append(this._jiuxiaoconsts).append(",");
/* 1129 */     _sb_.append(this._menpaipvp_npcservice).append(",");
/* 1130 */     _sb_.append(this._arena_npcservice).append(",");
/* 1131 */     _sb_.append(this._competition_npcservice).append(",");
/* 1132 */     _sb_.append(this._const).append(",");
/* 1133 */     _sb_.append(this._petaptconst).append(",");
/* 1134 */     _sb_.append(this._idip).append(",");
/* 1135 */     _sb_.append(this._marriageconst).append(",");
/* 1136 */     _sb_.append(this._guideconst).append(",");
/* 1137 */     _sb_.append(this._mapmodelinfo).append(",");
/* 1138 */     _sb_.append(this._npcmodelinfo).append(",");
/* 1139 */     _sb_.append(this._marketstate).append(",");
/* 1140 */     _sb_.append(this._mapgrouptype).append(",");
/* 1141 */     _sb_.append(this._mapentitytype).append(",");
/* 1142 */     _sb_.append(this._mapentityextrainfotype).append(",");
/* 1143 */     _sb_.append(this._qmhwconsts).append(",");
/* 1144 */     _sb_.append(this._mapgroupextrainfotype).append(",");
/* 1145 */     _sb_.append(this._grc_errorcodes).append(",");
/* 1146 */     _sb_.append(this._grc_recallret).append(",");
/* 1147 */     _sb_.append(this._qqvipflag).append(",");
/* 1148 */     _sb_.append(this._shituconst).append(",");
/* 1149 */     _sb_.append(this._raceconsts).append(",");
/* 1150 */     _sb_.append(this._coupledailyconst).append(",");
/* 1151 */     _sb_.append(this._idipntimesoperator).append(",");
/* 1152 */     _sb_.append(this._apollo_errorcodes).append(",");
/* 1153 */     _sb_.append(this._apollolargeroomtype).append(",");
/* 1154 */     _sb_.append(this._apolloglobalroomtype).append(",");
/* 1155 */     _sb_.append(this._qyxthelpstatus).append(",");
/* 1156 */     _sb_.append(this._fashiondressconst).append(",");
/* 1157 */     _sb_.append(this._fabaoconst).append(",");
/* 1158 */     _sb_.append(this._conditionstate).append(",");
/* 1159 */     _sb_.append(this._achievementconst).append(",");
/* 1160 */     _sb_.append(this._backgameconst).append(",");
/* 1161 */     _sb_.append(this._personal).append(",");
/* 1162 */     _sb_.append(this._activityconst).append(",");
/* 1163 */     _sb_.append(this._advert).append(",");
/* 1164 */     _sb_.append(this._qingyuanconst).append(",");
/* 1165 */     _sb_.append(this._loginawardconst).append(",");
/* 1166 */     _sb_.append(this._massweddingconst).append(",");
/* 1167 */     _sb_.append(this._catconst).append(",");
/* 1168 */     _sb_.append(this._mountsconst).append(",");
/* 1169 */     _sb_.append(this._doublepointswitchtype).append(",");
/* 1170 */     _sb_.append(this._luckybagconst).append(",");
/* 1171 */     _sb_.append(this._recallfriendconst).append(",");
/* 1172 */     _sb_.append(this._apollo_voiproomtype).append(",");
/* 1173 */     _sb_.append(this._apollo_voiproomaction).append(",");
/* 1174 */     _sb_.append(this._popuptype).append(",");
/* 1175 */     _sb_.append(this._massexpret).append(",");
/* 1176 */     _sb_.append(this._monsterstate).append(",");
/* 1177 */     _sb_.append(this._hulaactivityphase).append(",");
/* 1178 */     _sb_.append(this._ladderconst).append(",");
/* 1179 */     _sb_.append(this._babyperiodinfo).append(",");
/* 1180 */     _sb_.append(this._childhoodinfo).append(",");
/* 1181 */     _sb_.append(this._adulthoodinfo).append(",");
/* 1182 */     _sb_.append(this._childhoodret).append(",");
/* 1183 */     _sb_.append(this._childfashionret).append(",");
/* 1184 */     _sb_.append(this._childgrowthtype).append(",");
/* 1185 */     _sb_.append(this._childgrowthsubtype).append(",");
/* 1186 */     _sb_.append(this._watchmoonerrorcode).append(",");
/* 1187 */     _sb_.append(this._qilinmode).append(",");
/* 1188 */     _sb_.append(this._memorycompetitionconst).append(",");
/* 1189 */     _sb_.append(this._menpaistarret).append(",");
/* 1190 */     _sb_.append(this._geniusret).append(",");
/* 1191 */     _sb_.append(this._blessret).append(",");
/* 1192 */     _sb_.append(this._exploitconsts).append(",");
/* 1193 */     _sb_.append(this._zooret).append(",");
/* 1194 */     _sb_.append(this._embryostageinfo).append(",");
/* 1195 */     _sb_.append(this._adultstageinfo).append(",");
/* 1196 */     _sb_.append(this._drawandguessconst).append(",");
/* 1197 */     _sb_.append(this._crossbattleactivitystage).append(",");
/* 1198 */     _sb_.append(this._crossbattlevoteranktype).append(",");
/* 1199 */     _sb_.append(this._roundrobinroundstage).append(",");
/* 1200 */     _sb_.append(this._crossbattleownerrorcode).append(",");
/* 1201 */     _sb_.append(this._crossbattlepointconst).append(",");
/* 1202 */     _sb_.append(this._crossbattlebeterrorcode).append(",");
/* 1203 */     _sb_.append(this._crossbattleselectionconsts).append(",");
/* 1204 */     _sb_.append(this._getknockoutstagebetinforeason).append(",");
/* 1205 */     _sb_.append(this._crossbattlefinalconsts).append(",");
/* 1206 */     _sb_.append(this._crossfieldimportbean).append(",");
/* 1207 */     _sb_.append(this._jailaction).append(",");
/* 1208 */     _sb_.append(this._questionvoiceconst).append(",");
/* 1209 */     _sb_.append(this._sspreqtype).append(",");
/* 1210 */     _sb_.append(this._crossbattlebetimportbean).append(",");
/* 1211 */     _sb_.append(this._aircraftdatainfo).append(",");
/* 1212 */     _sb_.append(this._indianaimportbean).append(",");
/* 1213 */     _sb_.append(this._alllottoimportbean).append(",");
/* 1214 */     _sb_.append(this._cakeconsts).append(",");
/* 1215 */     _sb_.append(this._fireworkconsts).append(",");
/* 1216 */     _sb_.append(this._petarenaret).append(",");
/* 1217 */     _sb_.append(this._bigbossimportbean).append(",");
/* 1218 */     _sb_.append(this._ballbattleplayerstateenum).append(",");
/* 1219 */     _sb_.append(")");
/* 1220 */     return _sb_.toString();
/*      */   }
/*      */ }


/* Location:              D:\桌面\山海\gsxdbdebug.jar!\mzm\gsp\BeanImport.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */