textRes.Firework = {
  FEATRUE_IDIP_NOT_OPEN = "花火功能开关关闭",
  NOT_OPEN_LOW_LEVEL = "%d级后花火功能开启",
  FIREWORK_TITLE_PREFIX = "花火名称：",
  FIREWORK_TITLE_DEFAULT = "【%s】的花火",
  FIREWORK_TITLE_OVERLENGTH = "花火名称最多%d个字",
  FIREWORK_TITLE_SHORT = "花火名称过短",
  FIREWORK_TITLE_COST_NONE = "免费",
  FIREWORK_ELEMENT_GET = "恭喜获得【%s】*%d",
  FIREWORK_SCHEME_NAME_OVERLENGTH = "花火方案名称最多%d个字",
  FIREWORK_SCHEME_NAME_SHORT = "花火方案名称过短",
  FIREWORK_SCHEME_NAME_DEFAULT = "花火方案",
  FIREWORK_SCHEME_RENAME = "花火方案命名",
  FIREWORK_CHANGE_ELEMENT_TYPE_SINGLE = "单击图纸格子放置，双击格子清除",
  FIREWORK_CHANGE_ELEMENT_TYPE_MULTI = "点击【摆放】按钮放置，点【取消】按钮清除，图纸内拖动更换位置",
  FIREWORK_SCHEME_SAVE_CONFIRM_TITLE = "花火方案保存",
  FIREWORK_SCHEME_SAVE_CONFIRM_CONTENT = "当前花火方案未保存，是否保存?",
  FIREWORK_SCHEME_COUNT_MAX = "方案已满，请先删除不必要的方案",
  FIREWORK_DEL_CONFIRM_TITLE = "花火方案删除",
  FIREWORK_DEL_CONFIRM_CONTENT = "是否删除花火方案【%s】?",
  FIREWORK_SCHEME_SAVE_SUCC = "方案保存成功",
  FIREWORK_SCHEME_PREVIEW_SELECT = "请选择一个花火方案",
  FIREWORK_SCHEME_ALREADY_SAVED = "当前方案已经保存过了",
  FIREWORK_SCHEME_RENAME_SUCC = "花火方案命名成功",
  FIREWORK_SCHEME_RENAME_FAIL_SAME = "与当前花火方案名称相同",
  FIREWORK_SCHEME_RENAME_TITLE = "花火方案命名",
  FIREWORK_SHCHEME_SHARE_LINK = "<a href='%s' id=%s><font color=#46bc58><effect name='shadow'>%s</effect></font></a>",
  FIREWORK_SHARE_FAIL_NOT_OWN = "未保存的花火方案无法分享哦",
  FIREWORK_SHARE_SUCC = "分享方案成功",
  FIREWORK_MAKE_SUCC = "成功制作{璀璨花火}",
  FIREWORK_MAKE_FAIL_NO_ELEMENT = "当前方案不包含任何花火元素",
  FIREWORK_USE_SUCC = "成功使用{璀璨花火}",
  FIREWORK_USE_FAIL_TEAM = "组队中不可燃放花火",
  FIREWORK_USE_FAIL_MAP = "当前地图中不可燃放花火",
  FIREWORK_USE_FAIL_NOT_AFK = "组队状态下，只有队长和暂离队员可以燃放花火",
  FIREWORK_USE_FAIL_BLOCK = "花火摆放的位置有不可达点",
  FIREWORK_USE_FAIL_OTHER = "与存在的花火位置太近了,请换个位置吧",
  FIREWORK_USE_FAIL_NOT_SELF_GANG = "无法在他人帮派摆放花火",
  FIREWORK_BROADCAST_WORLD_NULL = "<font color=#f75000><font color=#55965f>[%s]</font>在<font color=#46a3ff>%s(%d, %d)</font>处对<font color=#55965f>[%s]</font>使用了【璀璨花火】:<font color=#ff00ff>%s</font>。</font>",
  FIREWORK_BROADCAST_WORLD_REDPACKET = "<font color=#f75000><font color=#55965f>[%s]</font>在<font color=#46a3ff>%s(%d, %d)</font>处对<font color=#55965f>[%s]</font>使用了【璀璨花火】:<font color=#ff00ff>%s</font>，并洒下大量红包。</font>",
  FIREWORK_BROADCAST_WORLD_SELF_NULL = "<font color=#f75000><font color=#55965f>[%s]</font>在<font color=#46a3ff>%s(%d, %d)</font>处使用了【璀璨花火】:<font color=#ff00ff>%s</font>。</font>",
  FIREWORK_BROADCAST_WORLD_SELF_REDPACKET = "<font color=#f75000><font color=#55965f>[%s]</font>在<font color=#46a3ff>%s(%d, %d)</font>处使用了【璀璨花火】:<font color=#ff00ff>%s</font>，并洒下大量红包。</font>",
  FIREWORK_BROADCAST_GANG_NULL = "<font color=#f75000><font color=#55965f>[%s]</font>在%s帮派中对<font color=#55965f>[%s]</font>使用了【璀璨花火】:<font color=#ff00ff>%s</font>。</font>",
  FIREWORK_BROADCAST_GANG_REDPACKET = "<font color=#f75000><font color=#55965f>[%s]</font>在%s帮派中对<font color=#55965f>[%s]</font>使用了【璀璨花火】:<font color=#ff00ff>%s</font>，并洒下大量红包。</font>",
  FIREWORK_BROADCAST_GANG_SELF_NULL = "<font color=#f75000><font color=#55965f>[%s]</font>在%s帮派中使用了【璀璨花火】:<font color=#ff00ff>%s</font>。</font>",
  FIREWORK_BROADCAST_GANG_SELF_REDPACKET = "<font color=#f75000><font color=#55965f>[%s]</font>在%s帮派中使用了【璀璨花火】:<font color=#ff00ff>%s</font>，并洒下大量红包。</font>",
  FIREWORK_BROADCAST_GOTO_PACKET = "<a href='%s' id=%s><font color=#46bc58><effect name='shadow'><u>前去观赏</u></effect></font></a>",
  FIREWORK_REDPACKET_NUM = "(%d~%d)",
  FIREWORK_REDPACKET_NUM_ERR = "不能超出当前红包的个数限制",
  FIREWORK_REDPACKET_ENTITY_NAME_COLOR = 701303005,
  FIREWORK_REDPACKET_ENTITY_NAME = "花火红包",
  FIREWORK_REDPACKET_NOT_SAME_GANG = "不是此帮派成员，无法进入此帮派",
  FIREWORK_REDPACKET_FETCH_SUCC = "获得花火红包%d金币",
  FIREWORK_REDPACKET_FETCH_TITLE = "拾取花火红包",
  FIREWORK_ELEMENT_LIST_NONE = "当前花火方案没有消耗任何花火元素",
  FIREWORK_DURATION_FORMAT = "%d分钟",
  FIREWORK_DURATION_COST = "选择此持续时间在结算时需要额外加收费%d%s",
  FIREWORK_ITEM_PREVIEW = "预览",
  SFireworkNormalRes = {
    [1] = "花火制作功能尚未开放",
    [2] = "角色等级不足",
    [3] = "角色账号为空,数据库未知错误",
    [4] = "花火制作元素列表为空",
    [5] = "花火制作元素数量过多",
    [6] = "名称样式配置不存在",
    [7] = "红包配置不存在",
    [8] = "红包数量不合法",
    [9] = "敏感词校验网络错误",
    [10] = "敏感词校验系统错误",
    [11] = "花火名称中包含敏感词",
    [12] = "方案名称中包含敏感词",
    [13] = "花火制作持续时间配置不存在",
    [14] = "花火制作元素道具不存在",
    [15] = "红包所需的非绑定元宝不足",
    [16] = "客户端计算需要的货币值与服务器不一致",
    [17] = "创建物品失败",
    [18] = "添加物品失败",
    [19] = "您拥有的花火方案数已经达到上限了",
    [21] = "花火名称不能为空",
    [22] = "花火名称长度超过范围",
    [23] = "花火方案不能为空",
    [24] = "花火方案长度超过范围",
    [25] = "方案序号非法",
    [26] = "方案序号不存在",
    [27] = "uuid对应物品不存在",
    [28] = "要使用的物品不是花火制作元素道具",
    [29] = "角色花火数据为空",
    [30] = "未找到对应花火,数据库错误",
    [31] = "该道具不是花火道具",
    [32] = "该花火已经使用过了",
    [33] = "指定地图不可摆放花火",
    [34] = "要摆放的地图id与当前所处地图id不符",
    [35] = "地图回调未找到玩家位置,内部逻辑错误",
    [36] = "删除物品失败",
    [37] = "与存在的花火位置太近了,请换个位置吧",
    [38] = "当前地图摆放的花火达到上限,请等他人花火燃放结束后重试",
    [39] = "跟随状态下不能使用花火",
    [40] = "发送的帮派id不存在",
    [41] = "对方用户信息不存在",
    [42] = "角色花火中没有该uuid的数据",
    [43] = "红包对应的花火地图实例不存在",
    [44] = "红包被别人抢走了,请试试下一个吧",
    [45] = "只能在队长或者单人状态下使用花火道具",
    [46] = "包裹满不能制作花火",
    [47] = "货币不足,制作失败",
    [48] = "当前状态不能进行此操作",
    [49] = "未在红包附近,不可拾取",
    [50] = "发奖失败",
    [51] = "包裹满,不能领取",
    [52] = "花火不能领取,不是合服退还花火",
    [53] = "花火剩余时间为0",
    [54] = "花火不存在",
    [55] = "花火摆放的位置有不可达点",
    [56] = "同类元素重叠,请重新摆放",
    [57] = "非本帮派不能在帮派地图中摆放花火",
    [58] = "您今天拾取的花火红包太多了,把机会留给别人吧"
  },
  ElementLayoutToast = {
    [1] = "成功",
    [2] = "无效元素",
    [3] = "最多摆放%d个%s类型的花火元素",
    [4] = "超出边界",
    [5] = "不能和同类元素重叠"
  },
  ElementTypeName = {
    [1] = "装饰",
    [2] = "特效",
    [3] = "文字"
  }
}
