textRes.HotSpring = {
  FEATRUE_IDIP_NOT_OPEN = "%s功能开关关闭",
  NOT_OPEN_LOW_LEVEL = "%d级后功能开启",
  DO_ACTIVITY_FAIL_CLOSED = "当前不是活动开启时间",
  DO_ACTIVITY_FAIL_TEAM = "组队状态下无法参与活动",
  DO_ACTIVITY_FAIL_NO_GANG = "没有帮派无法参加此活动",
  DO_ACTIVITY_FAIL_TEAM_CAPTAIN = "只有队长才能进行此操作。",
  DO_ACTIVITY_FAIL_TEAM_LEAVE = "有队员处于暂离状态，无法进入雪山温泉。",
  DO_ACTIVITY_FAIL_TEAM_OFFLINE = "有队员处于离线状态，无法进入雪山温泉。",
  DO_ACTIVITY_FAIL_TEAM_GANG = "%s与你不属于同一帮派，无法进入雪山温泉。",
  DYE_SUCC = "染色成功",
  DYE_TIP = "染色成功",
  DYE_UI_TIP = "可以无限次更换自己喜欢的颜色哦",
  ARENA_COUNTDOWN = "%d:%02d",
  ARENA_LEAVE_CONFIRM_CONTENT = "是否退出活动？",
  INTERACTION_FAIL_NOT_IN_POOL = "只有在泳池中才能进行该动作",
  INTERACTION_PRIZE_COUNT = "交互动作奖励剩余次数：%d",
  ROSE_COLLECT_SUCC = "成功采摘%d朵玫瑰",
  ROSE_COLLECT_FAIL_ROUND = "您已达到最大玫瑰采摘次数",
  ROSE_COLLECT_FAIL_COUNT = "已达到帮派最大玫瑰数量",
  ROSE_COLLECT_FAIL_GANG = "只能在自己帮派的温泉内采集玫瑰",
  ROSE_COLLECT_FAIL_TIME_OUT = "超出时间上限, 即将关闭",
  ROSE_COLLECT_FAIL_TEAM = "组队时只有队长或暂离队员可以采集玫瑰",
  ROSE_COLLECT_FAIL_CD = "<font color=#00ff00>%d秒</font>后才能再次采集玫瑰",
  ROSE_COLLECT_END = "已结束采集",
  ROSE_POOL_UPDATE = "经过大家的努力，成功采摘%d朵玫瑰，温泉升级为玫瑰温泉，请大家尽情享受吧。",
  ROSE_COUNTDOWN = "%d:%02d",
  ROSE_CLOSE_CONFIRM_CONTENT = "是否确认结束采集玫瑰？",
  ROSE_TIME_LIMIT_NONE = "不限",
  ROSE_UI_TIP = "手指轻轻划过红玫瑰即可成功采摘",
  MILK_COLLECT_SUCC = "成功采摘%d杯牛奶",
  MILK_COLLECT_FAIL_ROUND = "您已达到最大牛奶采集次数",
  MILK_COLLECT_FAIL_COUNT = "已达到帮派最大牛奶数量",
  MILK_COLLECT_FAIL_GANG = "只能在自己帮派的温泉内采集牛奶",
  MILK_COLLECT_FAIL_TIME_OUT = "超出时间上限, 即将关闭",
  MILK_COLLECT_FAIL_TEAM = "组队时只有队长或暂离队员可以采集牛奶",
  MILK_COLLECT_FAIL_CD = "<font color=#00ff00>%d秒</font>后才能再次采集牛奶",
  MILK_COLLECT_END = "已结束采集",
  MILK_POOL_UPDATE = "经过大家的努力，成功获得%d滴牛奶，温泉升级为奶浴温泉，请大家尽情享受吧。",
  MILK_COUNTDOWN = "%d:%02d",
  MILK_CLOSE_CONFIRM_CONTENT = "是否确认结束采集牛奶？",
  MILK_TIME_LIMIT_NONE = "不限",
  MILK_DROP_CATCH_SUCC = "获得牛奶",
  MILK_DROP_CATCH_FAIL = "没有获得牛奶",
  MILK_DROP_CATCH_DELAY = 0.35,
  MILK_DROP_CATCH_THRESHOLD = 50,
  MILK_UI_TIP = "点击奶牛，使奶滴落入木桶即可获得牛奶",
  MILK_COLLECT_CD = "不可频繁操作",
  POOL_ENTER_SUCC = "进入泳池",
  POOL_LEAVE_SUCC = "离开泳池",
  POOL_OPERATE_CD = "不可频繁进出泳池",
  VISIT_NO_GANG = "当前没有满足条件的帮派",
  VISIT_UI_TIP = "前往其他帮派需要消耗[FF0000]%d金币[-]",
  VISIT_CONFIRM_CONTENT_OTHER = "是否花费%d金币前往[FF0000]%s[-]帮派的雪山温泉？",
  VISIT_CONFIRM_CONTENT_SELF = "是否回到自己帮派的雪山温泉？",
  VISIT_FAIL_TEAM = "只有非组队状态下才能串帮哦",
  VISIT_FAIL_CD = "<font color=#00ff00>%d秒</font>后才能再次串帮",
  VISIT_STRANGER_MALE = "来自<font color=#00ff00>%s</font>帮派的<font color=#00ff00>%s</font>坏笑着来到了温泉内，绅士们注意了，千万要保护小姐姐们别被撩走哦！",
  VISIT_STRANGER_FEMALE = "来自<font color=#00ff00>%s</font>帮派的<font color=#00ff00>%s</font>迈着长腿来到了温泉内，单身汪们注意了，你们的机会来了！",
  VISIT_REFRESH_CDING = "刷新(%dS)",
  VISIT_REFRESH_READY = "刷新",
  VISIT_REFRESH_CD = "%d秒后才可再次刷新",
  SRequestEnterHotSpringFail = {
    [-1] = "活动已过期",
    [-2] = "角色仍在串帮中",
    [-3] = "角色已经在副本中",
    [-4] = "角色所在帮派人数过少",
    [-5] = "队伍中有不属于本帮角色",
    [-6] = "角色在暂离状态",
    [-7] = "队伍有暂离或离线状态角色",
    [-8] = "角色不在所属帮派地图"
  },
  SQuitHotSpringFail = {
    [-1] = "副本不存在",
    [-2] = "角色不在副本中",
    [-3] = "活动已过期",
    [-4] = "队伍有暂离成员",
    [-5] = "组队跟随时不能进行此操作",
    [-6] = "组队暂离时不能进行此操作"
  },
  SDyeFail = {
    [-1] = "未知染色",
    [-2] = "染色性别不符",
    [-3] = "活动已过期"
  },
  SCommitRosesFail = {
    [-1] = "玫瑰数量非法",
    [-2] = "本次活动采玫瑰剩余次数已为0",
    [-3] = "角色非副本所属帮派成员",
    [-4] = "帮派收集玫瑰任务已经完成",
    [-5] = "活动已过期",
    [-6] = "组队跟随时不能进行此操作",
    [-7] = "<font color=#00ff00>%d秒</font>后才能再次采集玫瑰"
  },
  SCommitMilkFail = {
    [-1] = "牛奶数量非法",
    [-2] = "本次活动收集牛奶的剩余次数已为0",
    [-3] = "角色非副本所属帮派成员",
    [-4] = "帮派收集牛奶任务已经完成",
    [-5] = "活动已过期",
    [-6] = "组队跟随时不能进行此操作",
    [-7] = "<font color=#00ff00>%d秒</font>后才能再次采集牛奶"
  },
  SGetHotSpringGangListFail = {
    [-1] = "活动已过期"
  },
  SGuestFail = {
    [-1] = "帮派不存在",
    [-2] = "金币不足",
    [-3] = "帮派人数过多",
    [-4] = "已经在该帮派的温泉副本中",
    [-5] = "活动已过期",
    [-6] = "串帮次数不一致",
    [-7] = "只有单人状态才能串帮",
    [-8] = "<font color=#00ff00>%d秒</font>后才能再次串帮"
  },
  SEnterPoolFail = {
    [-1] = "活动已过期",
    [-2] = "角色已在池中",
    [-3] = "组队跟随时不能进行此操作"
  },
  SQuitPoolFail = {
    [-1] = "活动已过期",
    [-2] = "角色已在岸上",
    [-3] = "组队跟随时不能进行此操作"
  }
}
