textRes.VampireWar = {
  FEATRUE_IDIP_NOT_OPEN = "%s功能开关关闭",
  NOT_OPEN_LOW_LEVEL = "%d级后吸血鬼大作战功能开启",
  DO_ACTIVITY_FAIL_CLOSED = "当前不是吸血鬼大作战活动开启时间",
  DO_ACTIVITY_FAIL_TEAM = "只能单人参与",
  CAMP_ATLAS = "Arts/Image/Atlas/Compressed/Vampire.prefab.u3dext",
  ATTACK_FAIL_SAME_CAMP = "队长，别开枪，自己人！",
  ATTACK_FAIL_SKILL_CD = "你的技能尚未准备好",
  ATTACK_FAIL_OVER_DIST = "对方超出了你的攻击范围",
  ATTACK_FAIL_INVINCIBLE = "对方抵御了你的法术",
  ATTACK_FAIL_PROTECT_TARGET = "对方处于保护状态无法攻击",
  ATTACK_FAIL_PROTECT_HERO = "您处于保护状态无法攻击",
  ATTACK_SUCC = "你的法术产生了效果",
  HALL_LEAVE_CONFIRM_TITLE = "",
  HALL_LEAVE_CONFIRM_CONTENT = "您是否确认离开大厅？",
  HALL_COUNTDOWN = "%d分%02d秒",
  HALL_FINISHED = "今日活动已经结束啦~",
  ARENA_INIT_HERO_INFO = "<font color=#00ff00>快去寻找敌人，直接点击敌人进行攻击吧！</font>",
  ARENA_PENTA_KILL = "神勇无比的%s连续击败3名对手，已经无人可挡啦！",
  ARENA_SHUT_DOWN = "异军突起，%s终结了%s的狂欢！",
  ARENA_CLICK_ATTACK_SKILL = "<font color=#00ff00>当前技能默认选中状态，请直接点击敌人进行攻击</font>",
  ARENA_KILL_NUM = "%s击杀数",
  ARENA_COUNTDOWN = "%d分%02d秒",
  ARENA_KILL_BROADCAST = "<img src='%s:%s' width=32 height=32><font color=#ff0000>%s</font>击杀了<img src='%s:%s' width=32 height=32><font color=#00ff00>%s</font>",
  ARENA_END_BY_KILL = "%s阵营神勇无比，已经击败了30名敌人，获得了本场活动的胜利！",
  SKILL_COUNTDOWN = "%ds",
  SKILL_COUNTDOWN_CN = "%d秒",
  SVampireWarNormalFail = {
    [1] = "您今天的领奖次数已经达到上限了,再参与将不会获得奖励",
    [2] = "目标已经被击杀,当前处于重生保护状态,不能被攻击",
    [3] = "目标处于护盾无敌状态,不能被攻击",
    [4] = "当前技能CD尚未结束,请稍后",
    [5] = "您当前处于保护状态,不能攻击他人",
    [6] = "目标角色血量小于等于0",
    [7] = "当前已经是护盾无敌状态,请稍后使用",
    [8] = "护盾技能只能对自己使用",
    [9] = "对方超出了你的攻击范围",
    [10] = "未知错误,准备大厅不存在",
    [11] = "活动配置不存在",
    [12] = "不具备参加当前活动的资格",
    [13] = "不支持的技能类型",
    [14] = "不能攻击自己",
    [15] = "不能攻击友方",
    [16] = "游戏已结束",
    [17] = "游戏已结束",
    [18] = "您当前在本轮游戏中, 暂时不能退出"
  },
  SkillTypeName = {
    [1] = "攻击",
    [2] = "防御"
  }
}
