/*      */ package hub;
/*      */ 
/*      */ import com.goldhuman.Common.Marshal.OctetsStream;
/*      */ 
/*      */ public class ImportDataTransferBeans extends __ImportDataTransferBeans__ {
/*      */   public static final int PROTOCOL_TYPE = 14099;
/*      */   public DataTransferType _datatransfertype;
/*      */   public DataBroadcastType _databroadcasttype;
/*      */   public GenRoamTokenReq _genroamtokenreq;
/*      */   public GenRoamTokenRsp _genroamtokenrsp;
/*      */   public RoamRoleDataReq _roamroledatareq;
/*      */   public RoamRoleDataRsp _roamroledatarsp;
/*      */   public ValidateRoamTokenReq _validateroamtokenreq;
/*      */   public ValidateRoamTokenRsp _validateroamtokenrsp;
/*      */   public LadderDataBackReq _ladderdatabackreq;
/*      */   public LadderDataBackRsp _ladderdatabackrsp;
/*      */   public RoamMatchContextReq _roammatchcontextreq;
/*      */   public RoamMatchContextRsp _roammatchcontextrsp;
/*      */   public JoinMatchReq _joinmatchreq;
/*      */   public JoinMatchRsp _joinmatchrsp;
/*      */   
/*      */   protected void process() {}
/*      */   
/*      */   public int getType() {
/*   25 */     return 14099;
/*      */   }
/*      */   
/*      */ 
/*      */   public NotifyMatchResultReq _notifymatchresultreq;
/*      */   
/*      */   public NotifyMatchResultRsp _notifymatchresultrsp;
/*      */   
/*      */   public CancelMatchReq _cancelmatchreq;
/*      */   
/*      */   public CancelMatchRsp _cancelmatchrsp;
/*      */   
/*      */   public WaitNextRoundMatchReq _waitnextroundmatchreq;
/*      */   
/*      */   public WaitNextRoundMatchRsp _waitnextroundmatchrsp;
/*      */   
/*      */   public ConfirmJoinMatchReq _confirmjoinmatchreq;
/*      */   
/*      */   public ConfirmJoinMatchRsp _confirmjoinmatchrsp;
/*      */   
/*      */   public ReportGameServerBalanceInfoReq _reportgameserverbalanceinforeq;
/*      */   
/*      */   public ReportGameServerBalanceInfoRsp _reportgameserverbalanceinforsp;
/*      */   
/*      */   public CrossCompeteSignUpFaction _crosscompetesignupfaction;
/*      */   
/*      */   public ReportCrossCompeteSignUpReq _reportcrosscompetesignupreq;
/*      */   
/*      */   public ReportCrossCompeteSignUpRsp _reportcrosscompetesignuprsp;
/*      */   
/*      */   public CrossCompeteRoamServersReq _crosscompeteroamserversreq;
/*      */   public CrossCompeteRoamServersRsp _crosscompeteroamserversrsp;
/*      */   public NotifyCrossCompeteAgainstReq _notifycrosscompeteagainstreq;
/*      */   public NotifyCrossCompeteAgainstRsp _notifycrosscompeteagainstrsp;
/*      */   public ReportCrossCompeteFactionInfoReq _reportcrosscompetefactioninforeq;
/*      */   public ReportCrossCompeteFactionInfoRsp _reportcrosscompetefactioninforsp;
/*      */   public EnterCrossCompeteMapReq _entercrosscompetemapreq;
/*      */   public EnterCrossCompeteMapRsp _entercrosscompetemaprsp;
/*      */   public CrossCompeteRoleDataBackReq _crosscompeteroledatabackreq;
/*      */   public CrossCompeteRoleDataBackRsp _crosscompeteroledatabackrsp;
/*      */   public NotifyCrossCompeteResultReq _notifycrosscompeteresultreq;
/*      */   public NotifyCrossCompeteResultRsp _notifycrosscompeteresultrsp;
/*      */   public CrossCompeteTeamBackReq _crosscompeteteambackreq;
/*      */   public CrossCompeteTeamBackRsp _crosscompeteteambackrsp;
/*      */   public ReportCorpsFightValueReq _reportcorpsfightvaluereq;
/*      */   public ReportCorpsFightValueRsp _reportcorpsfightvaluersp;
/*      */   public JoinPointRaceReq _joinpointracereq;
/*      */   public JoinPointRaceRsp _joinpointracersp;
/*      */   public ConfirmJoinPointRaceReq _confirmjoinpointracereq;
/*      */   public ConfirmJoinPointRaceRsp _confirmjoinpointracersp;
/*      */   public RoamPointRaceContextReq _roampointracecontextreq;
/*      */   public RoamPointRaceContextRsp _roampointracecontextrsp;
/*      */   public NotifyPointRaceResultReq _notifypointraceresultreq;
/*      */   public NotifyPointRaceResultRsp _notifypointraceresultrsp;
/*      */   public NotifyPointRacePendingReq _notifypointracependingreq;
/*      */   public NotifyPointRacePendingRsp _notifypointracependingrsp;
/*      */   public RoamPointRaceDataReq _roampointracedatareq;
/*      */   public RoamPointRaceDataRsp _roampointracedatarsp;
/*      */   public PointRaceDataBackReq _pointracedatabackreq;
/*      */   public PointRaceDataBackRsp _pointracedatabackrsp;
/*      */   public UpdatePointRaceCorpsReq _updatepointracecorpsreq;
/*      */   public UpdatePointRaceCorpsRsp _updatepointracecorpsrsp;
/*      */   public ReportPointRaceCorpsCVCReq _reportpointracecorpscvcreq;
/*      */   public ReportPointRaceCorpsCVCRsp _reportpointracecorpscvcrsp;
/*      */   public PointRaceEndReq _pointraceendreq;
/*      */   public PointRaceEndRsp _pointraceendrsp;
/*      */   public PointRaceQueryReq _pointracequeryreq;
/*      */   public PointRaceQueryRsp _pointracequeryrsp;
/*      */   public JoinCrossBattleSelectionOrFinalReq _joincrossbattleselectionorfinalreq;
/*      */   public JoinCrossBattleSelectionOrFinalRsp _joincrossbattleselectionorfinalrsp;
/*      */   public RoamSelectionOrFinalContextReq _roamselectionorfinalcontextreq;
/*      */   public RoamSelectionOrFinalContextRsp _roamselectionorfinalcontextrsp;
/*      */   public NotifySelectionOrFinalMatchReq _notifyselectionorfinalmatchreq;
/*      */   public NotifySelectionOrFinalMatchRsp _notifyselectionorfinalmatchrsp;
/*      */   public SelectionOrFinalDataBackReq _selectionorfinaldatabackreq;
/*      */   public SelectionOrFinalDataBackRsp _selectionorfinaldatabackrsp;
/*      */   public SelectionOrFinalWaitNextRoundMatchReq _selectionorfinalwaitnextroundmatchreq;
/*      */   public SelectionOrFinalWaitNextRoundMatchRsp _selectionorfinalwaitnextroundmatchrsp;
/*      */   public SelectionOrFinalFightBeginReq _selectionorfinalfightbeginreq;
/*      */   public SelectionOrFinalFightBeginRsp _selectionorfinalfightbeginrsp;
/*      */   public ConfirmJoinSelectionOrFinalMatchReq _confirmjoinselectionorfinalmatchreq;
/*      */   public ConfirmJoinSelectionOrFinalMatchRsp _confirmjoinselectionorfinalmatchrsp;
/*      */   public NotifySelectionOrFinalByeReq _notifyselectionorfinalbyereq;
/*      */   public NotifySelectionOrFinalByeRsp _notifyselectionorfinalbyersp;
/*      */   public NotifyFightRecordStartInfo _notifyfightrecordstartinfo;
/*      */   public NotifyFightRecordEndInfo _notifyfightrecordendinfo;
/*      */   public NotifyFightRecordRoundInfo _notifyfightrecordroundinfo;
/*      */   public NotifyCrossBattleFinalBulletion _notifycrossbattlefinalbulletion;
/*      */   public NotifyModifyServerDate _notifymodifyserverdate;
/*      */   public NotifyModifyRoamServerDate _notifymodifyroamserverdate;
/*      */   public ModifyRoamServerDateReq _modifyroamserverdatereq;
/*      */   public ModifyRoamServerDateRsp _modifyroamserverdatersp;
/*      */   public SingleCrossFieldJoinMatchReq _singlecrossfieldjoinmatchreq;
/*      */   public SingleCrossFieldJoinMatchRsp _singlecrossfieldjoinmatchrsp;
/*      */   public SingleCrossFieldConfirmJoinMatchReq _singlecrossfieldconfirmjoinmatchreq;
/*      */   public SingleCrossFieldConfirmJoinMatchRsp _singlecrossfieldconfirmjoinmatchrsp;
/*      */   public SingleCrossFieldRoamMatchContextReq _singlecrossfieldroammatchcontextreq;
/*      */   public SingleCrossFieldRoamMatchContextRsp _singlecrossfieldroammatchcontextrsp;
/*      */   public SingleCrossFieldNotifyMatchResultReq _singlecrossfieldnotifymatchresultreq;
/*      */   public SingleCrossFieldNotifyMatchResultRsp _singlecrossfieldnotifymatchresultrsp;
/*      */   public SingleCrossFieldCancelMatchReq _singlecrossfieldcancelmatchreq;
/*      */   public SingleCrossFieldCancelMatchRsp _singlecrossfieldcancelmatchrsp;
/*      */   public SingleCrossFieldWaitNextRoundMatchReq _singlecrossfieldwaitnextroundmatchreq;
/*      */   public SingleCrossFieldWaitNextRoundMatchRsp _singlecrossfieldwaitnextroundmatchrsp;
/*      */   public SingleCrossFieldDataBackReq _singlecrossfielddatabackreq;
/*      */   public SingleCrossFieldDataBackRsp _singlecrossfielddatabackrsp;
/*      */   public MatchFailReason _matchfailreason;
/*      */   public TransferChatContentReq _transferchatcontentreq;
/*      */   public TransferChatContentRsp _transferchatcontentrsp;
/*      */   public FriendsCircleGiveGiftReq _friendscirclegivegiftreq;
/*      */   public FriendsCircleGiveGiftRsp _friendscirclegivegiftrsp;
/*      */   public FriendsCircleDeleteGiveGiftHistoryReq _friendscircledeletegivegifthistoryreq;
/*      */   public FriendsCircleDeleteGiveGiftHistoryRsp _friendscircledeletegivegifthistoryrsp;
/*      */   public FriendsCircleTreadReq _friendscircletreadreq;
/*      */   public FriendsCircleTreadRsp _friendscircletreadrsp;
/*      */   public FriendsCircleDeleteTreadHistoryReq _friendscircledeletetreadhistoryreq;
/*      */   public FriendsCircleDeleteTreadHistoryRsp _friendscircledeletetreadhistoryrsp;
/*      */   public FriendsCircleOperatorBlackReq _friendscircleoperatorblackreq;
/*      */   public FriendsCircleOperatorBlackRsp _friendscircleoperatorblackrsp;
/*      */   public RecallNotifyBindFriendReq _recallnotifybindfriendreq;
/*      */   public RecallNotifyBindFriendRsp _recallnotifybindfriendrsp;
/*      */   public NotifyIndianaAwardRoleInfo _notifyindianaawardroleinfo;
/*      */   public AllLottoReportCandidateInfoReq _alllottoreportcandidateinforeq;
/*      */   public AllLottoReportCandidateInfoRsp _alllottoreportcandidateinforsp;
/*      */   public AllLottoNotifyAwardRoleInfoReq _alllottonotifyawardroleinforeq;
/*      */   public AllLottoNotifyAwardRoleInfoRsp _alllottonotifyawardroleinforsp;
/*      */   public AllLottoBrdAwardRoleInfo _alllottobrdawardroleinfo;
/*      */   public TreasureBagExchangeData _treasurebagexchangedata;
/*      */   public ImportDataTransferBeans()
/*      */   {
/*  155 */     this._datatransfertype = new DataTransferType();
/*  156 */     this._databroadcasttype = new DataBroadcastType();
/*  157 */     this._genroamtokenreq = new GenRoamTokenReq();
/*  158 */     this._genroamtokenrsp = new GenRoamTokenRsp();
/*  159 */     this._roamroledatareq = new RoamRoleDataReq();
/*  160 */     this._roamroledatarsp = new RoamRoleDataRsp();
/*  161 */     this._validateroamtokenreq = new ValidateRoamTokenReq();
/*  162 */     this._validateroamtokenrsp = new ValidateRoamTokenRsp();
/*  163 */     this._ladderdatabackreq = new LadderDataBackReq();
/*  164 */     this._ladderdatabackrsp = new LadderDataBackRsp();
/*  165 */     this._roammatchcontextreq = new RoamMatchContextReq();
/*  166 */     this._roammatchcontextrsp = new RoamMatchContextRsp();
/*  167 */     this._joinmatchreq = new JoinMatchReq();
/*  168 */     this._joinmatchrsp = new JoinMatchRsp();
/*  169 */     this._notifymatchresultreq = new NotifyMatchResultReq();
/*  170 */     this._notifymatchresultrsp = new NotifyMatchResultRsp();
/*  171 */     this._cancelmatchreq = new CancelMatchReq();
/*  172 */     this._cancelmatchrsp = new CancelMatchRsp();
/*  173 */     this._waitnextroundmatchreq = new WaitNextRoundMatchReq();
/*  174 */     this._waitnextroundmatchrsp = new WaitNextRoundMatchRsp();
/*  175 */     this._confirmjoinmatchreq = new ConfirmJoinMatchReq();
/*  176 */     this._confirmjoinmatchrsp = new ConfirmJoinMatchRsp();
/*  177 */     this._reportgameserverbalanceinforeq = new ReportGameServerBalanceInfoReq();
/*  178 */     this._reportgameserverbalanceinforsp = new ReportGameServerBalanceInfoRsp();
/*  179 */     this._crosscompetesignupfaction = new CrossCompeteSignUpFaction();
/*  180 */     this._reportcrosscompetesignupreq = new ReportCrossCompeteSignUpReq();
/*  181 */     this._reportcrosscompetesignuprsp = new ReportCrossCompeteSignUpRsp();
/*  182 */     this._crosscompeteroamserversreq = new CrossCompeteRoamServersReq();
/*  183 */     this._crosscompeteroamserversrsp = new CrossCompeteRoamServersRsp();
/*  184 */     this._notifycrosscompeteagainstreq = new NotifyCrossCompeteAgainstReq();
/*  185 */     this._notifycrosscompeteagainstrsp = new NotifyCrossCompeteAgainstRsp();
/*  186 */     this._reportcrosscompetefactioninforeq = new ReportCrossCompeteFactionInfoReq();
/*  187 */     this._reportcrosscompetefactioninforsp = new ReportCrossCompeteFactionInfoRsp();
/*  188 */     this._entercrosscompetemapreq = new EnterCrossCompeteMapReq();
/*  189 */     this._entercrosscompetemaprsp = new EnterCrossCompeteMapRsp();
/*  190 */     this._crosscompeteroledatabackreq = new CrossCompeteRoleDataBackReq();
/*  191 */     this._crosscompeteroledatabackrsp = new CrossCompeteRoleDataBackRsp();
/*  192 */     this._notifycrosscompeteresultreq = new NotifyCrossCompeteResultReq();
/*  193 */     this._notifycrosscompeteresultrsp = new NotifyCrossCompeteResultRsp();
/*  194 */     this._crosscompeteteambackreq = new CrossCompeteTeamBackReq();
/*  195 */     this._crosscompeteteambackrsp = new CrossCompeteTeamBackRsp();
/*  196 */     this._reportcorpsfightvaluereq = new ReportCorpsFightValueReq();
/*  197 */     this._reportcorpsfightvaluersp = new ReportCorpsFightValueRsp();
/*  198 */     this._joinpointracereq = new JoinPointRaceReq();
/*  199 */     this._joinpointracersp = new JoinPointRaceRsp();
/*  200 */     this._confirmjoinpointracereq = new ConfirmJoinPointRaceReq();
/*  201 */     this._confirmjoinpointracersp = new ConfirmJoinPointRaceRsp();
/*  202 */     this._roampointracecontextreq = new RoamPointRaceContextReq();
/*  203 */     this._roampointracecontextrsp = new RoamPointRaceContextRsp();
/*  204 */     this._notifypointraceresultreq = new NotifyPointRaceResultReq();
/*  205 */     this._notifypointraceresultrsp = new NotifyPointRaceResultRsp();
/*  206 */     this._notifypointracependingreq = new NotifyPointRacePendingReq();
/*  207 */     this._notifypointracependingrsp = new NotifyPointRacePendingRsp();
/*  208 */     this._roampointracedatareq = new RoamPointRaceDataReq();
/*  209 */     this._roampointracedatarsp = new RoamPointRaceDataRsp();
/*  210 */     this._pointracedatabackreq = new PointRaceDataBackReq();
/*  211 */     this._pointracedatabackrsp = new PointRaceDataBackRsp();
/*  212 */     this._updatepointracecorpsreq = new UpdatePointRaceCorpsReq();
/*  213 */     this._updatepointracecorpsrsp = new UpdatePointRaceCorpsRsp();
/*  214 */     this._reportpointracecorpscvcreq = new ReportPointRaceCorpsCVCReq();
/*  215 */     this._reportpointracecorpscvcrsp = new ReportPointRaceCorpsCVCRsp();
/*  216 */     this._pointraceendreq = new PointRaceEndReq();
/*  217 */     this._pointraceendrsp = new PointRaceEndRsp();
/*  218 */     this._pointracequeryreq = new PointRaceQueryReq();
/*  219 */     this._pointracequeryrsp = new PointRaceQueryRsp();
/*  220 */     this._joincrossbattleselectionorfinalreq = new JoinCrossBattleSelectionOrFinalReq();
/*  221 */     this._joincrossbattleselectionorfinalrsp = new JoinCrossBattleSelectionOrFinalRsp();
/*  222 */     this._roamselectionorfinalcontextreq = new RoamSelectionOrFinalContextReq();
/*  223 */     this._roamselectionorfinalcontextrsp = new RoamSelectionOrFinalContextRsp();
/*  224 */     this._notifyselectionorfinalmatchreq = new NotifySelectionOrFinalMatchReq();
/*  225 */     this._notifyselectionorfinalmatchrsp = new NotifySelectionOrFinalMatchRsp();
/*  226 */     this._selectionorfinaldatabackreq = new SelectionOrFinalDataBackReq();
/*  227 */     this._selectionorfinaldatabackrsp = new SelectionOrFinalDataBackRsp();
/*  228 */     this._selectionorfinalwaitnextroundmatchreq = new SelectionOrFinalWaitNextRoundMatchReq();
/*  229 */     this._selectionorfinalwaitnextroundmatchrsp = new SelectionOrFinalWaitNextRoundMatchRsp();
/*  230 */     this._selectionorfinalfightbeginreq = new SelectionOrFinalFightBeginReq();
/*  231 */     this._selectionorfinalfightbeginrsp = new SelectionOrFinalFightBeginRsp();
/*  232 */     this._confirmjoinselectionorfinalmatchreq = new ConfirmJoinSelectionOrFinalMatchReq();
/*  233 */     this._confirmjoinselectionorfinalmatchrsp = new ConfirmJoinSelectionOrFinalMatchRsp();
/*  234 */     this._notifyselectionorfinalbyereq = new NotifySelectionOrFinalByeReq();
/*  235 */     this._notifyselectionorfinalbyersp = new NotifySelectionOrFinalByeRsp();
/*  236 */     this._notifyfightrecordstartinfo = new NotifyFightRecordStartInfo();
/*  237 */     this._notifyfightrecordendinfo = new NotifyFightRecordEndInfo();
/*  238 */     this._notifyfightrecordroundinfo = new NotifyFightRecordRoundInfo();
/*  239 */     this._notifycrossbattlefinalbulletion = new NotifyCrossBattleFinalBulletion();
/*  240 */     this._notifymodifyserverdate = new NotifyModifyServerDate();
/*  241 */     this._notifymodifyroamserverdate = new NotifyModifyRoamServerDate();
/*  242 */     this._modifyroamserverdatereq = new ModifyRoamServerDateReq();
/*  243 */     this._modifyroamserverdatersp = new ModifyRoamServerDateRsp();
/*  244 */     this._singlecrossfieldjoinmatchreq = new SingleCrossFieldJoinMatchReq();
/*  245 */     this._singlecrossfieldjoinmatchrsp = new SingleCrossFieldJoinMatchRsp();
/*  246 */     this._singlecrossfieldconfirmjoinmatchreq = new SingleCrossFieldConfirmJoinMatchReq();
/*  247 */     this._singlecrossfieldconfirmjoinmatchrsp = new SingleCrossFieldConfirmJoinMatchRsp();
/*  248 */     this._singlecrossfieldroammatchcontextreq = new SingleCrossFieldRoamMatchContextReq();
/*  249 */     this._singlecrossfieldroammatchcontextrsp = new SingleCrossFieldRoamMatchContextRsp();
/*  250 */     this._singlecrossfieldnotifymatchresultreq = new SingleCrossFieldNotifyMatchResultReq();
/*  251 */     this._singlecrossfieldnotifymatchresultrsp = new SingleCrossFieldNotifyMatchResultRsp();
/*  252 */     this._singlecrossfieldcancelmatchreq = new SingleCrossFieldCancelMatchReq();
/*  253 */     this._singlecrossfieldcancelmatchrsp = new SingleCrossFieldCancelMatchRsp();
/*  254 */     this._singlecrossfieldwaitnextroundmatchreq = new SingleCrossFieldWaitNextRoundMatchReq();
/*  255 */     this._singlecrossfieldwaitnextroundmatchrsp = new SingleCrossFieldWaitNextRoundMatchRsp();
/*  256 */     this._singlecrossfielddatabackreq = new SingleCrossFieldDataBackReq();
/*  257 */     this._singlecrossfielddatabackrsp = new SingleCrossFieldDataBackRsp();
/*  258 */     this._matchfailreason = new MatchFailReason();
/*  259 */     this._transferchatcontentreq = new TransferChatContentReq();
/*  260 */     this._transferchatcontentrsp = new TransferChatContentRsp();
/*  261 */     this._friendscirclegivegiftreq = new FriendsCircleGiveGiftReq();
/*  262 */     this._friendscirclegivegiftrsp = new FriendsCircleGiveGiftRsp();
/*  263 */     this._friendscircledeletegivegifthistoryreq = new FriendsCircleDeleteGiveGiftHistoryReq();
/*  264 */     this._friendscircledeletegivegifthistoryrsp = new FriendsCircleDeleteGiveGiftHistoryRsp();
/*  265 */     this._friendscircletreadreq = new FriendsCircleTreadReq();
/*  266 */     this._friendscircletreadrsp = new FriendsCircleTreadRsp();
/*  267 */     this._friendscircledeletetreadhistoryreq = new FriendsCircleDeleteTreadHistoryReq();
/*  268 */     this._friendscircledeletetreadhistoryrsp = new FriendsCircleDeleteTreadHistoryRsp();
/*  269 */     this._friendscircleoperatorblackreq = new FriendsCircleOperatorBlackReq();
/*  270 */     this._friendscircleoperatorblackrsp = new FriendsCircleOperatorBlackRsp();
/*  271 */     this._recallnotifybindfriendreq = new RecallNotifyBindFriendReq();
/*  272 */     this._recallnotifybindfriendrsp = new RecallNotifyBindFriendRsp();
/*  273 */     this._notifyindianaawardroleinfo = new NotifyIndianaAwardRoleInfo();
/*  274 */     this._alllottoreportcandidateinforeq = new AllLottoReportCandidateInfoReq();
/*  275 */     this._alllottoreportcandidateinforsp = new AllLottoReportCandidateInfoRsp();
/*  276 */     this._alllottonotifyawardroleinforeq = new AllLottoNotifyAwardRoleInfoReq();
/*  277 */     this._alllottonotifyawardroleinforsp = new AllLottoNotifyAwardRoleInfoRsp();
/*  278 */     this._alllottobrdawardroleinfo = new AllLottoBrdAwardRoleInfo();
/*  279 */     this._treasurebagexchangedata = new TreasureBagExchangeData();
/*      */   }
/*      */   
/*      */   public ImportDataTransferBeans(DataTransferType __datatransfertype_, DataBroadcastType __databroadcasttype_, GenRoamTokenReq __genroamtokenreq_, GenRoamTokenRsp __genroamtokenrsp_, RoamRoleDataReq __roamroledatareq_, RoamRoleDataRsp __roamroledatarsp_, ValidateRoamTokenReq __validateroamtokenreq_, ValidateRoamTokenRsp __validateroamtokenrsp_, LadderDataBackReq __ladderdatabackreq_, LadderDataBackRsp __ladderdatabackrsp_, RoamMatchContextReq __roammatchcontextreq_, RoamMatchContextRsp __roammatchcontextrsp_, JoinMatchReq __joinmatchreq_, JoinMatchRsp __joinmatchrsp_, NotifyMatchResultReq __notifymatchresultreq_, NotifyMatchResultRsp __notifymatchresultrsp_, CancelMatchReq __cancelmatchreq_, CancelMatchRsp __cancelmatchrsp_, WaitNextRoundMatchReq __waitnextroundmatchreq_, WaitNextRoundMatchRsp __waitnextroundmatchrsp_, ConfirmJoinMatchReq __confirmjoinmatchreq_, ConfirmJoinMatchRsp __confirmjoinmatchrsp_, ReportGameServerBalanceInfoReq __reportgameserverbalanceinforeq_, ReportGameServerBalanceInfoRsp __reportgameserverbalanceinforsp_, CrossCompeteSignUpFaction __crosscompetesignupfaction_, ReportCrossCompeteSignUpReq __reportcrosscompetesignupreq_, ReportCrossCompeteSignUpRsp __reportcrosscompetesignuprsp_, CrossCompeteRoamServersReq __crosscompeteroamserversreq_, CrossCompeteRoamServersRsp __crosscompeteroamserversrsp_, NotifyCrossCompeteAgainstReq __notifycrosscompeteagainstreq_, NotifyCrossCompeteAgainstRsp __notifycrosscompeteagainstrsp_, ReportCrossCompeteFactionInfoReq __reportcrosscompetefactioninforeq_, ReportCrossCompeteFactionInfoRsp __reportcrosscompetefactioninforsp_, EnterCrossCompeteMapReq __entercrosscompetemapreq_, EnterCrossCompeteMapRsp __entercrosscompetemaprsp_, CrossCompeteRoleDataBackReq __crosscompeteroledatabackreq_, CrossCompeteRoleDataBackRsp __crosscompeteroledatabackrsp_, NotifyCrossCompeteResultReq __notifycrosscompeteresultreq_, NotifyCrossCompeteResultRsp __notifycrosscompeteresultrsp_, CrossCompeteTeamBackReq __crosscompeteteambackreq_, CrossCompeteTeamBackRsp __crosscompeteteambackrsp_, ReportCorpsFightValueReq __reportcorpsfightvaluereq_, ReportCorpsFightValueRsp __reportcorpsfightvaluersp_, JoinPointRaceReq __joinpointracereq_, JoinPointRaceRsp __joinpointracersp_, ConfirmJoinPointRaceReq __confirmjoinpointracereq_, ConfirmJoinPointRaceRsp __confirmjoinpointracersp_, RoamPointRaceContextReq __roampointracecontextreq_, RoamPointRaceContextRsp __roampointracecontextrsp_, NotifyPointRaceResultReq __notifypointraceresultreq_, NotifyPointRaceResultRsp __notifypointraceresultrsp_, NotifyPointRacePendingReq __notifypointracependingreq_, NotifyPointRacePendingRsp __notifypointracependingrsp_, RoamPointRaceDataReq __roampointracedatareq_, RoamPointRaceDataRsp __roampointracedatarsp_, PointRaceDataBackReq __pointracedatabackreq_, PointRaceDataBackRsp __pointracedatabackrsp_, UpdatePointRaceCorpsReq __updatepointracecorpsreq_, UpdatePointRaceCorpsRsp __updatepointracecorpsrsp_, ReportPointRaceCorpsCVCReq __reportpointracecorpscvcreq_, ReportPointRaceCorpsCVCRsp __reportpointracecorpscvcrsp_, PointRaceEndReq __pointraceendreq_, PointRaceEndRsp __pointraceendrsp_, PointRaceQueryReq __pointracequeryreq_, PointRaceQueryRsp __pointracequeryrsp_, JoinCrossBattleSelectionOrFinalReq __joincrossbattleselectionorfinalreq_, JoinCrossBattleSelectionOrFinalRsp __joincrossbattleselectionorfinalrsp_, RoamSelectionOrFinalContextReq __roamselectionorfinalcontextreq_, RoamSelectionOrFinalContextRsp __roamselectionorfinalcontextrsp_, NotifySelectionOrFinalMatchReq __notifyselectionorfinalmatchreq_, NotifySelectionOrFinalMatchRsp __notifyselectionorfinalmatchrsp_, SelectionOrFinalDataBackReq __selectionorfinaldatabackreq_, SelectionOrFinalDataBackRsp __selectionorfinaldatabackrsp_, SelectionOrFinalWaitNextRoundMatchReq __selectionorfinalwaitnextroundmatchreq_, SelectionOrFinalWaitNextRoundMatchRsp __selectionorfinalwaitnextroundmatchrsp_, SelectionOrFinalFightBeginReq __selectionorfinalfightbeginreq_, SelectionOrFinalFightBeginRsp __selectionorfinalfightbeginrsp_, ConfirmJoinSelectionOrFinalMatchReq __confirmjoinselectionorfinalmatchreq_, ConfirmJoinSelectionOrFinalMatchRsp __confirmjoinselectionorfinalmatchrsp_, NotifySelectionOrFinalByeReq __notifyselectionorfinalbyereq_, NotifySelectionOrFinalByeRsp __notifyselectionorfinalbyersp_, NotifyFightRecordStartInfo __notifyfightrecordstartinfo_, NotifyFightRecordEndInfo __notifyfightrecordendinfo_, NotifyFightRecordRoundInfo __notifyfightrecordroundinfo_, NotifyCrossBattleFinalBulletion __notifycrossbattlefinalbulletion_, NotifyModifyServerDate __notifymodifyserverdate_, NotifyModifyRoamServerDate __notifymodifyroamserverdate_, ModifyRoamServerDateReq __modifyroamserverdatereq_, ModifyRoamServerDateRsp __modifyroamserverdatersp_, SingleCrossFieldJoinMatchReq __singlecrossfieldjoinmatchreq_, SingleCrossFieldJoinMatchRsp __singlecrossfieldjoinmatchrsp_, SingleCrossFieldConfirmJoinMatchReq __singlecrossfieldconfirmjoinmatchreq_, SingleCrossFieldConfirmJoinMatchRsp __singlecrossfieldconfirmjoinmatchrsp_, SingleCrossFieldRoamMatchContextReq __singlecrossfieldroammatchcontextreq_, SingleCrossFieldRoamMatchContextRsp __singlecrossfieldroammatchcontextrsp_, SingleCrossFieldNotifyMatchResultReq __singlecrossfieldnotifymatchresultreq_, SingleCrossFieldNotifyMatchResultRsp __singlecrossfieldnotifymatchresultrsp_, SingleCrossFieldCancelMatchReq __singlecrossfieldcancelmatchreq_, SingleCrossFieldCancelMatchRsp __singlecrossfieldcancelmatchrsp_, SingleCrossFieldWaitNextRoundMatchReq __singlecrossfieldwaitnextroundmatchreq_, SingleCrossFieldWaitNextRoundMatchRsp __singlecrossfieldwaitnextroundmatchrsp_, SingleCrossFieldDataBackReq __singlecrossfielddatabackreq_, SingleCrossFieldDataBackRsp __singlecrossfielddatabackrsp_, MatchFailReason __matchfailreason_, TransferChatContentReq __transferchatcontentreq_, TransferChatContentRsp __transferchatcontentrsp_, FriendsCircleGiveGiftReq __friendscirclegivegiftreq_, FriendsCircleGiveGiftRsp __friendscirclegivegiftrsp_, FriendsCircleDeleteGiveGiftHistoryReq __friendscircledeletegivegifthistoryreq_, FriendsCircleDeleteGiveGiftHistoryRsp __friendscircledeletegivegifthistoryrsp_, FriendsCircleTreadReq __friendscircletreadreq_, FriendsCircleTreadRsp __friendscircletreadrsp_, FriendsCircleDeleteTreadHistoryReq __friendscircledeletetreadhistoryreq_, FriendsCircleDeleteTreadHistoryRsp __friendscircledeletetreadhistoryrsp_, FriendsCircleOperatorBlackReq __friendscircleoperatorblackreq_, FriendsCircleOperatorBlackRsp __friendscircleoperatorblackrsp_, RecallNotifyBindFriendReq __recallnotifybindfriendreq_, RecallNotifyBindFriendRsp __recallnotifybindfriendrsp_, NotifyIndianaAwardRoleInfo __notifyindianaawardroleinfo_, AllLottoReportCandidateInfoReq __alllottoreportcandidateinforeq_, AllLottoReportCandidateInfoRsp __alllottoreportcandidateinforsp_, AllLottoNotifyAwardRoleInfoReq __alllottonotifyawardroleinforeq_, AllLottoNotifyAwardRoleInfoRsp __alllottonotifyawardroleinforsp_, AllLottoBrdAwardRoleInfo __alllottobrdawardroleinfo_, TreasureBagExchangeData __treasurebagexchangedata_) {
/*  283 */     this._datatransfertype = __datatransfertype_;
/*  284 */     this._databroadcasttype = __databroadcasttype_;
/*  285 */     this._genroamtokenreq = __genroamtokenreq_;
/*  286 */     this._genroamtokenrsp = __genroamtokenrsp_;
/*  287 */     this._roamroledatareq = __roamroledatareq_;
/*  288 */     this._roamroledatarsp = __roamroledatarsp_;
/*  289 */     this._validateroamtokenreq = __validateroamtokenreq_;
/*  290 */     this._validateroamtokenrsp = __validateroamtokenrsp_;
/*  291 */     this._ladderdatabackreq = __ladderdatabackreq_;
/*  292 */     this._ladderdatabackrsp = __ladderdatabackrsp_;
/*  293 */     this._roammatchcontextreq = __roammatchcontextreq_;
/*  294 */     this._roammatchcontextrsp = __roammatchcontextrsp_;
/*  295 */     this._joinmatchreq = __joinmatchreq_;
/*  296 */     this._joinmatchrsp = __joinmatchrsp_;
/*  297 */     this._notifymatchresultreq = __notifymatchresultreq_;
/*  298 */     this._notifymatchresultrsp = __notifymatchresultrsp_;
/*  299 */     this._cancelmatchreq = __cancelmatchreq_;
/*  300 */     this._cancelmatchrsp = __cancelmatchrsp_;
/*  301 */     this._waitnextroundmatchreq = __waitnextroundmatchreq_;
/*  302 */     this._waitnextroundmatchrsp = __waitnextroundmatchrsp_;
/*  303 */     this._confirmjoinmatchreq = __confirmjoinmatchreq_;
/*  304 */     this._confirmjoinmatchrsp = __confirmjoinmatchrsp_;
/*  305 */     this._reportgameserverbalanceinforeq = __reportgameserverbalanceinforeq_;
/*  306 */     this._reportgameserverbalanceinforsp = __reportgameserverbalanceinforsp_;
/*  307 */     this._crosscompetesignupfaction = __crosscompetesignupfaction_;
/*  308 */     this._reportcrosscompetesignupreq = __reportcrosscompetesignupreq_;
/*  309 */     this._reportcrosscompetesignuprsp = __reportcrosscompetesignuprsp_;
/*  310 */     this._crosscompeteroamserversreq = __crosscompeteroamserversreq_;
/*  311 */     this._crosscompeteroamserversrsp = __crosscompeteroamserversrsp_;
/*  312 */     this._notifycrosscompeteagainstreq = __notifycrosscompeteagainstreq_;
/*  313 */     this._notifycrosscompeteagainstrsp = __notifycrosscompeteagainstrsp_;
/*  314 */     this._reportcrosscompetefactioninforeq = __reportcrosscompetefactioninforeq_;
/*  315 */     this._reportcrosscompetefactioninforsp = __reportcrosscompetefactioninforsp_;
/*  316 */     this._entercrosscompetemapreq = __entercrosscompetemapreq_;
/*  317 */     this._entercrosscompetemaprsp = __entercrosscompetemaprsp_;
/*  318 */     this._crosscompeteroledatabackreq = __crosscompeteroledatabackreq_;
/*  319 */     this._crosscompeteroledatabackrsp = __crosscompeteroledatabackrsp_;
/*  320 */     this._notifycrosscompeteresultreq = __notifycrosscompeteresultreq_;
/*  321 */     this._notifycrosscompeteresultrsp = __notifycrosscompeteresultrsp_;
/*  322 */     this._crosscompeteteambackreq = __crosscompeteteambackreq_;
/*  323 */     this._crosscompeteteambackrsp = __crosscompeteteambackrsp_;
/*  324 */     this._reportcorpsfightvaluereq = __reportcorpsfightvaluereq_;
/*  325 */     this._reportcorpsfightvaluersp = __reportcorpsfightvaluersp_;
/*  326 */     this._joinpointracereq = __joinpointracereq_;
/*  327 */     this._joinpointracersp = __joinpointracersp_;
/*  328 */     this._confirmjoinpointracereq = __confirmjoinpointracereq_;
/*  329 */     this._confirmjoinpointracersp = __confirmjoinpointracersp_;
/*  330 */     this._roampointracecontextreq = __roampointracecontextreq_;
/*  331 */     this._roampointracecontextrsp = __roampointracecontextrsp_;
/*  332 */     this._notifypointraceresultreq = __notifypointraceresultreq_;
/*  333 */     this._notifypointraceresultrsp = __notifypointraceresultrsp_;
/*  334 */     this._notifypointracependingreq = __notifypointracependingreq_;
/*  335 */     this._notifypointracependingrsp = __notifypointracependingrsp_;
/*  336 */     this._roampointracedatareq = __roampointracedatareq_;
/*  337 */     this._roampointracedatarsp = __roampointracedatarsp_;
/*  338 */     this._pointracedatabackreq = __pointracedatabackreq_;
/*  339 */     this._pointracedatabackrsp = __pointracedatabackrsp_;
/*  340 */     this._updatepointracecorpsreq = __updatepointracecorpsreq_;
/*  341 */     this._updatepointracecorpsrsp = __updatepointracecorpsrsp_;
/*  342 */     this._reportpointracecorpscvcreq = __reportpointracecorpscvcreq_;
/*  343 */     this._reportpointracecorpscvcrsp = __reportpointracecorpscvcrsp_;
/*  344 */     this._pointraceendreq = __pointraceendreq_;
/*  345 */     this._pointraceendrsp = __pointraceendrsp_;
/*  346 */     this._pointracequeryreq = __pointracequeryreq_;
/*  347 */     this._pointracequeryrsp = __pointracequeryrsp_;
/*  348 */     this._joincrossbattleselectionorfinalreq = __joincrossbattleselectionorfinalreq_;
/*  349 */     this._joincrossbattleselectionorfinalrsp = __joincrossbattleselectionorfinalrsp_;
/*  350 */     this._roamselectionorfinalcontextreq = __roamselectionorfinalcontextreq_;
/*  351 */     this._roamselectionorfinalcontextrsp = __roamselectionorfinalcontextrsp_;
/*  352 */     this._notifyselectionorfinalmatchreq = __notifyselectionorfinalmatchreq_;
/*  353 */     this._notifyselectionorfinalmatchrsp = __notifyselectionorfinalmatchrsp_;
/*  354 */     this._selectionorfinaldatabackreq = __selectionorfinaldatabackreq_;
/*  355 */     this._selectionorfinaldatabackrsp = __selectionorfinaldatabackrsp_;
/*  356 */     this._selectionorfinalwaitnextroundmatchreq = __selectionorfinalwaitnextroundmatchreq_;
/*  357 */     this._selectionorfinalwaitnextroundmatchrsp = __selectionorfinalwaitnextroundmatchrsp_;
/*  358 */     this._selectionorfinalfightbeginreq = __selectionorfinalfightbeginreq_;
/*  359 */     this._selectionorfinalfightbeginrsp = __selectionorfinalfightbeginrsp_;
/*  360 */     this._confirmjoinselectionorfinalmatchreq = __confirmjoinselectionorfinalmatchreq_;
/*  361 */     this._confirmjoinselectionorfinalmatchrsp = __confirmjoinselectionorfinalmatchrsp_;
/*  362 */     this._notifyselectionorfinalbyereq = __notifyselectionorfinalbyereq_;
/*  363 */     this._notifyselectionorfinalbyersp = __notifyselectionorfinalbyersp_;
/*  364 */     this._notifyfightrecordstartinfo = __notifyfightrecordstartinfo_;
/*  365 */     this._notifyfightrecordendinfo = __notifyfightrecordendinfo_;
/*  366 */     this._notifyfightrecordroundinfo = __notifyfightrecordroundinfo_;
/*  367 */     this._notifycrossbattlefinalbulletion = __notifycrossbattlefinalbulletion_;
/*  368 */     this._notifymodifyserverdate = __notifymodifyserverdate_;
/*  369 */     this._notifymodifyroamserverdate = __notifymodifyroamserverdate_;
/*  370 */     this._modifyroamserverdatereq = __modifyroamserverdatereq_;
/*  371 */     this._modifyroamserverdatersp = __modifyroamserverdatersp_;
/*  372 */     this._singlecrossfieldjoinmatchreq = __singlecrossfieldjoinmatchreq_;
/*  373 */     this._singlecrossfieldjoinmatchrsp = __singlecrossfieldjoinmatchrsp_;
/*  374 */     this._singlecrossfieldconfirmjoinmatchreq = __singlecrossfieldconfirmjoinmatchreq_;
/*  375 */     this._singlecrossfieldconfirmjoinmatchrsp = __singlecrossfieldconfirmjoinmatchrsp_;
/*  376 */     this._singlecrossfieldroammatchcontextreq = __singlecrossfieldroammatchcontextreq_;
/*  377 */     this._singlecrossfieldroammatchcontextrsp = __singlecrossfieldroammatchcontextrsp_;
/*  378 */     this._singlecrossfieldnotifymatchresultreq = __singlecrossfieldnotifymatchresultreq_;
/*  379 */     this._singlecrossfieldnotifymatchresultrsp = __singlecrossfieldnotifymatchresultrsp_;
/*  380 */     this._singlecrossfieldcancelmatchreq = __singlecrossfieldcancelmatchreq_;
/*  381 */     this._singlecrossfieldcancelmatchrsp = __singlecrossfieldcancelmatchrsp_;
/*  382 */     this._singlecrossfieldwaitnextroundmatchreq = __singlecrossfieldwaitnextroundmatchreq_;
/*  383 */     this._singlecrossfieldwaitnextroundmatchrsp = __singlecrossfieldwaitnextroundmatchrsp_;
/*  384 */     this._singlecrossfielddatabackreq = __singlecrossfielddatabackreq_;
/*  385 */     this._singlecrossfielddatabackrsp = __singlecrossfielddatabackrsp_;
/*  386 */     this._matchfailreason = __matchfailreason_;
/*  387 */     this._transferchatcontentreq = __transferchatcontentreq_;
/*  388 */     this._transferchatcontentrsp = __transferchatcontentrsp_;
/*  389 */     this._friendscirclegivegiftreq = __friendscirclegivegiftreq_;
/*  390 */     this._friendscirclegivegiftrsp = __friendscirclegivegiftrsp_;
/*  391 */     this._friendscircledeletegivegifthistoryreq = __friendscircledeletegivegifthistoryreq_;
/*  392 */     this._friendscircledeletegivegifthistoryrsp = __friendscircledeletegivegifthistoryrsp_;
/*  393 */     this._friendscircletreadreq = __friendscircletreadreq_;
/*  394 */     this._friendscircletreadrsp = __friendscircletreadrsp_;
/*  395 */     this._friendscircledeletetreadhistoryreq = __friendscircledeletetreadhistoryreq_;
/*  396 */     this._friendscircledeletetreadhistoryrsp = __friendscircledeletetreadhistoryrsp_;
/*  397 */     this._friendscircleoperatorblackreq = __friendscircleoperatorblackreq_;
/*  398 */     this._friendscircleoperatorblackrsp = __friendscircleoperatorblackrsp_;
/*  399 */     this._recallnotifybindfriendreq = __recallnotifybindfriendreq_;
/*  400 */     this._recallnotifybindfriendrsp = __recallnotifybindfriendrsp_;
/*  401 */     this._notifyindianaawardroleinfo = __notifyindianaawardroleinfo_;
/*  402 */     this._alllottoreportcandidateinforeq = __alllottoreportcandidateinforeq_;
/*  403 */     this._alllottoreportcandidateinforsp = __alllottoreportcandidateinforsp_;
/*  404 */     this._alllottonotifyawardroleinforeq = __alllottonotifyawardroleinforeq_;
/*  405 */     this._alllottonotifyawardroleinforsp = __alllottonotifyawardroleinforsp_;
/*  406 */     this._alllottobrdawardroleinfo = __alllottobrdawardroleinfo_;
/*  407 */     this._treasurebagexchangedata = __treasurebagexchangedata_;
/*      */   }
/*      */   
/*      */   public final boolean _validator_() {
/*  411 */     if (!this._datatransfertype._validator_()) return false;
/*  412 */     if (!this._databroadcasttype._validator_()) return false;
/*  413 */     if (!this._genroamtokenreq._validator_()) return false;
/*  414 */     if (!this._genroamtokenrsp._validator_()) return false;
/*  415 */     if (!this._roamroledatareq._validator_()) return false;
/*  416 */     if (!this._roamroledatarsp._validator_()) return false;
/*  417 */     if (!this._validateroamtokenreq._validator_()) return false;
/*  418 */     if (!this._validateroamtokenrsp._validator_()) return false;
/*  419 */     if (!this._ladderdatabackreq._validator_()) return false;
/*  420 */     if (!this._ladderdatabackrsp._validator_()) return false;
/*  421 */     if (!this._roammatchcontextreq._validator_()) return false;
/*  422 */     if (!this._roammatchcontextrsp._validator_()) return false;
/*  423 */     if (!this._joinmatchreq._validator_()) return false;
/*  424 */     if (!this._joinmatchrsp._validator_()) return false;
/*  425 */     if (!this._notifymatchresultreq._validator_()) return false;
/*  426 */     if (!this._notifymatchresultrsp._validator_()) return false;
/*  427 */     if (!this._cancelmatchreq._validator_()) return false;
/*  428 */     if (!this._cancelmatchrsp._validator_()) return false;
/*  429 */     if (!this._waitnextroundmatchreq._validator_()) return false;
/*  430 */     if (!this._waitnextroundmatchrsp._validator_()) return false;
/*  431 */     if (!this._confirmjoinmatchreq._validator_()) return false;
/*  432 */     if (!this._confirmjoinmatchrsp._validator_()) return false;
/*  433 */     if (!this._reportgameserverbalanceinforeq._validator_()) return false;
/*  434 */     if (!this._reportgameserverbalanceinforsp._validator_()) return false;
/*  435 */     if (!this._crosscompetesignupfaction._validator_()) return false;
/*  436 */     if (!this._reportcrosscompetesignupreq._validator_()) return false;
/*  437 */     if (!this._reportcrosscompetesignuprsp._validator_()) return false;
/*  438 */     if (!this._crosscompeteroamserversreq._validator_()) return false;
/*  439 */     if (!this._crosscompeteroamserversrsp._validator_()) return false;
/*  440 */     if (!this._notifycrosscompeteagainstreq._validator_()) return false;
/*  441 */     if (!this._notifycrosscompeteagainstrsp._validator_()) return false;
/*  442 */     if (!this._reportcrosscompetefactioninforeq._validator_()) return false;
/*  443 */     if (!this._reportcrosscompetefactioninforsp._validator_()) return false;
/*  444 */     if (!this._entercrosscompetemapreq._validator_()) return false;
/*  445 */     if (!this._entercrosscompetemaprsp._validator_()) return false;
/*  446 */     if (!this._crosscompeteroledatabackreq._validator_()) return false;
/*  447 */     if (!this._crosscompeteroledatabackrsp._validator_()) return false;
/*  448 */     if (!this._notifycrosscompeteresultreq._validator_()) return false;
/*  449 */     if (!this._notifycrosscompeteresultrsp._validator_()) return false;
/*  450 */     if (!this._crosscompeteteambackreq._validator_()) return false;
/*  451 */     if (!this._crosscompeteteambackrsp._validator_()) return false;
/*  452 */     if (!this._reportcorpsfightvaluereq._validator_()) return false;
/*  453 */     if (!this._reportcorpsfightvaluersp._validator_()) return false;
/*  454 */     if (!this._joinpointracereq._validator_()) return false;
/*  455 */     if (!this._joinpointracersp._validator_()) return false;
/*  456 */     if (!this._confirmjoinpointracereq._validator_()) return false;
/*  457 */     if (!this._confirmjoinpointracersp._validator_()) return false;
/*  458 */     if (!this._roampointracecontextreq._validator_()) return false;
/*  459 */     if (!this._roampointracecontextrsp._validator_()) return false;
/*  460 */     if (!this._notifypointraceresultreq._validator_()) return false;
/*  461 */     if (!this._notifypointraceresultrsp._validator_()) return false;
/*  462 */     if (!this._notifypointracependingreq._validator_()) return false;
/*  463 */     if (!this._notifypointracependingrsp._validator_()) return false;
/*  464 */     if (!this._roampointracedatareq._validator_()) return false;
/*  465 */     if (!this._roampointracedatarsp._validator_()) return false;
/*  466 */     if (!this._pointracedatabackreq._validator_()) return false;
/*  467 */     if (!this._pointracedatabackrsp._validator_()) return false;
/*  468 */     if (!this._updatepointracecorpsreq._validator_()) return false;
/*  469 */     if (!this._updatepointracecorpsrsp._validator_()) return false;
/*  470 */     if (!this._reportpointracecorpscvcreq._validator_()) return false;
/*  471 */     if (!this._reportpointracecorpscvcrsp._validator_()) return false;
/*  472 */     if (!this._pointraceendreq._validator_()) return false;
/*  473 */     if (!this._pointraceendrsp._validator_()) return false;
/*  474 */     if (!this._pointracequeryreq._validator_()) return false;
/*  475 */     if (!this._pointracequeryrsp._validator_()) return false;
/*  476 */     if (!this._joincrossbattleselectionorfinalreq._validator_()) return false;
/*  477 */     if (!this._joincrossbattleselectionorfinalrsp._validator_()) return false;
/*  478 */     if (!this._roamselectionorfinalcontextreq._validator_()) return false;
/*  479 */     if (!this._roamselectionorfinalcontextrsp._validator_()) return false;
/*  480 */     if (!this._notifyselectionorfinalmatchreq._validator_()) return false;
/*  481 */     if (!this._notifyselectionorfinalmatchrsp._validator_()) return false;
/*  482 */     if (!this._selectionorfinaldatabackreq._validator_()) return false;
/*  483 */     if (!this._selectionorfinaldatabackrsp._validator_()) return false;
/*  484 */     if (!this._selectionorfinalwaitnextroundmatchreq._validator_()) return false;
/*  485 */     if (!this._selectionorfinalwaitnextroundmatchrsp._validator_()) return false;
/*  486 */     if (!this._selectionorfinalfightbeginreq._validator_()) return false;
/*  487 */     if (!this._selectionorfinalfightbeginrsp._validator_()) return false;
/*  488 */     if (!this._confirmjoinselectionorfinalmatchreq._validator_()) return false;
/*  489 */     if (!this._confirmjoinselectionorfinalmatchrsp._validator_()) return false;
/*  490 */     if (!this._notifyselectionorfinalbyereq._validator_()) return false;
/*  491 */     if (!this._notifyselectionorfinalbyersp._validator_()) return false;
/*  492 */     if (!this._notifyfightrecordstartinfo._validator_()) return false;
/*  493 */     if (!this._notifyfightrecordendinfo._validator_()) return false;
/*  494 */     if (!this._notifyfightrecordroundinfo._validator_()) return false;
/*  495 */     if (!this._notifycrossbattlefinalbulletion._validator_()) return false;
/*  496 */     if (!this._notifymodifyserverdate._validator_()) return false;
/*  497 */     if (!this._notifymodifyroamserverdate._validator_()) return false;
/*  498 */     if (!this._modifyroamserverdatereq._validator_()) return false;
/*  499 */     if (!this._modifyroamserverdatersp._validator_()) return false;
/*  500 */     if (!this._singlecrossfieldjoinmatchreq._validator_()) return false;
/*  501 */     if (!this._singlecrossfieldjoinmatchrsp._validator_()) return false;
/*  502 */     if (!this._singlecrossfieldconfirmjoinmatchreq._validator_()) return false;
/*  503 */     if (!this._singlecrossfieldconfirmjoinmatchrsp._validator_()) return false;
/*  504 */     if (!this._singlecrossfieldroammatchcontextreq._validator_()) return false;
/*  505 */     if (!this._singlecrossfieldroammatchcontextrsp._validator_()) return false;
/*  506 */     if (!this._singlecrossfieldnotifymatchresultreq._validator_()) return false;
/*  507 */     if (!this._singlecrossfieldnotifymatchresultrsp._validator_()) return false;
/*  508 */     if (!this._singlecrossfieldcancelmatchreq._validator_()) return false;
/*  509 */     if (!this._singlecrossfieldcancelmatchrsp._validator_()) return false;
/*  510 */     if (!this._singlecrossfieldwaitnextroundmatchreq._validator_()) return false;
/*  511 */     if (!this._singlecrossfieldwaitnextroundmatchrsp._validator_()) return false;
/*  512 */     if (!this._singlecrossfielddatabackreq._validator_()) return false;
/*  513 */     if (!this._singlecrossfielddatabackrsp._validator_()) return false;
/*  514 */     if (!this._matchfailreason._validator_()) return false;
/*  515 */     if (!this._transferchatcontentreq._validator_()) return false;
/*  516 */     if (!this._transferchatcontentrsp._validator_()) return false;
/*  517 */     if (!this._friendscirclegivegiftreq._validator_()) return false;
/*  518 */     if (!this._friendscirclegivegiftrsp._validator_()) return false;
/*  519 */     if (!this._friendscircledeletegivegifthistoryreq._validator_()) return false;
/*  520 */     if (!this._friendscircledeletegivegifthistoryrsp._validator_()) return false;
/*  521 */     if (!this._friendscircletreadreq._validator_()) return false;
/*  522 */     if (!this._friendscircletreadrsp._validator_()) return false;
/*  523 */     if (!this._friendscircledeletetreadhistoryreq._validator_()) return false;
/*  524 */     if (!this._friendscircledeletetreadhistoryrsp._validator_()) return false;
/*  525 */     if (!this._friendscircleoperatorblackreq._validator_()) return false;
/*  526 */     if (!this._friendscircleoperatorblackrsp._validator_()) return false;
/*  527 */     if (!this._recallnotifybindfriendreq._validator_()) return false;
/*  528 */     if (!this._recallnotifybindfriendrsp._validator_()) return false;
/*  529 */     if (!this._notifyindianaawardroleinfo._validator_()) return false;
/*  530 */     if (!this._alllottoreportcandidateinforeq._validator_()) return false;
/*  531 */     if (!this._alllottoreportcandidateinforsp._validator_()) return false;
/*  532 */     if (!this._alllottonotifyawardroleinforeq._validator_()) return false;
/*  533 */     if (!this._alllottonotifyawardroleinforsp._validator_()) return false;
/*  534 */     if (!this._alllottobrdawardroleinfo._validator_()) return false;
/*  535 */     if (!this._treasurebagexchangedata._validator_()) return false;
/*  536 */     return true;
/*      */   }
/*      */   
/*      */   public OctetsStream marshal(OctetsStream _os_) {
/*  540 */     _os_.marshal(this._datatransfertype);
/*  541 */     _os_.marshal(this._databroadcasttype);
/*  542 */     _os_.marshal(this._genroamtokenreq);
/*  543 */     _os_.marshal(this._genroamtokenrsp);
/*  544 */     _os_.marshal(this._roamroledatareq);
/*  545 */     _os_.marshal(this._roamroledatarsp);
/*  546 */     _os_.marshal(this._validateroamtokenreq);
/*  547 */     _os_.marshal(this._validateroamtokenrsp);
/*  548 */     _os_.marshal(this._ladderdatabackreq);
/*  549 */     _os_.marshal(this._ladderdatabackrsp);
/*  550 */     _os_.marshal(this._roammatchcontextreq);
/*  551 */     _os_.marshal(this._roammatchcontextrsp);
/*  552 */     _os_.marshal(this._joinmatchreq);
/*  553 */     _os_.marshal(this._joinmatchrsp);
/*  554 */     _os_.marshal(this._notifymatchresultreq);
/*  555 */     _os_.marshal(this._notifymatchresultrsp);
/*  556 */     _os_.marshal(this._cancelmatchreq);
/*  557 */     _os_.marshal(this._cancelmatchrsp);
/*  558 */     _os_.marshal(this._waitnextroundmatchreq);
/*  559 */     _os_.marshal(this._waitnextroundmatchrsp);
/*  560 */     _os_.marshal(this._confirmjoinmatchreq);
/*  561 */     _os_.marshal(this._confirmjoinmatchrsp);
/*  562 */     _os_.marshal(this._reportgameserverbalanceinforeq);
/*  563 */     _os_.marshal(this._reportgameserverbalanceinforsp);
/*  564 */     _os_.marshal(this._crosscompetesignupfaction);
/*  565 */     _os_.marshal(this._reportcrosscompetesignupreq);
/*  566 */     _os_.marshal(this._reportcrosscompetesignuprsp);
/*  567 */     _os_.marshal(this._crosscompeteroamserversreq);
/*  568 */     _os_.marshal(this._crosscompeteroamserversrsp);
/*  569 */     _os_.marshal(this._notifycrosscompeteagainstreq);
/*  570 */     _os_.marshal(this._notifycrosscompeteagainstrsp);
/*  571 */     _os_.marshal(this._reportcrosscompetefactioninforeq);
/*  572 */     _os_.marshal(this._reportcrosscompetefactioninforsp);
/*  573 */     _os_.marshal(this._entercrosscompetemapreq);
/*  574 */     _os_.marshal(this._entercrosscompetemaprsp);
/*  575 */     _os_.marshal(this._crosscompeteroledatabackreq);
/*  576 */     _os_.marshal(this._crosscompeteroledatabackrsp);
/*  577 */     _os_.marshal(this._notifycrosscompeteresultreq);
/*  578 */     _os_.marshal(this._notifycrosscompeteresultrsp);
/*  579 */     _os_.marshal(this._crosscompeteteambackreq);
/*  580 */     _os_.marshal(this._crosscompeteteambackrsp);
/*  581 */     _os_.marshal(this._reportcorpsfightvaluereq);
/*  582 */     _os_.marshal(this._reportcorpsfightvaluersp);
/*  583 */     _os_.marshal(this._joinpointracereq);
/*  584 */     _os_.marshal(this._joinpointracersp);
/*  585 */     _os_.marshal(this._confirmjoinpointracereq);
/*  586 */     _os_.marshal(this._confirmjoinpointracersp);
/*  587 */     _os_.marshal(this._roampointracecontextreq);
/*  588 */     _os_.marshal(this._roampointracecontextrsp);
/*  589 */     _os_.marshal(this._notifypointraceresultreq);
/*  590 */     _os_.marshal(this._notifypointraceresultrsp);
/*  591 */     _os_.marshal(this._notifypointracependingreq);
/*  592 */     _os_.marshal(this._notifypointracependingrsp);
/*  593 */     _os_.marshal(this._roampointracedatareq);
/*  594 */     _os_.marshal(this._roampointracedatarsp);
/*  595 */     _os_.marshal(this._pointracedatabackreq);
/*  596 */     _os_.marshal(this._pointracedatabackrsp);
/*  597 */     _os_.marshal(this._updatepointracecorpsreq);
/*  598 */     _os_.marshal(this._updatepointracecorpsrsp);
/*  599 */     _os_.marshal(this._reportpointracecorpscvcreq);
/*  600 */     _os_.marshal(this._reportpointracecorpscvcrsp);
/*  601 */     _os_.marshal(this._pointraceendreq);
/*  602 */     _os_.marshal(this._pointraceendrsp);
/*  603 */     _os_.marshal(this._pointracequeryreq);
/*  604 */     _os_.marshal(this._pointracequeryrsp);
/*  605 */     _os_.marshal(this._joincrossbattleselectionorfinalreq);
/*  606 */     _os_.marshal(this._joincrossbattleselectionorfinalrsp);
/*  607 */     _os_.marshal(this._roamselectionorfinalcontextreq);
/*  608 */     _os_.marshal(this._roamselectionorfinalcontextrsp);
/*  609 */     _os_.marshal(this._notifyselectionorfinalmatchreq);
/*  610 */     _os_.marshal(this._notifyselectionorfinalmatchrsp);
/*  611 */     _os_.marshal(this._selectionorfinaldatabackreq);
/*  612 */     _os_.marshal(this._selectionorfinaldatabackrsp);
/*  613 */     _os_.marshal(this._selectionorfinalwaitnextroundmatchreq);
/*  614 */     _os_.marshal(this._selectionorfinalwaitnextroundmatchrsp);
/*  615 */     _os_.marshal(this._selectionorfinalfightbeginreq);
/*  616 */     _os_.marshal(this._selectionorfinalfightbeginrsp);
/*  617 */     _os_.marshal(this._confirmjoinselectionorfinalmatchreq);
/*  618 */     _os_.marshal(this._confirmjoinselectionorfinalmatchrsp);
/*  619 */     _os_.marshal(this._notifyselectionorfinalbyereq);
/*  620 */     _os_.marshal(this._notifyselectionorfinalbyersp);
/*  621 */     _os_.marshal(this._notifyfightrecordstartinfo);
/*  622 */     _os_.marshal(this._notifyfightrecordendinfo);
/*  623 */     _os_.marshal(this._notifyfightrecordroundinfo);
/*  624 */     _os_.marshal(this._notifycrossbattlefinalbulletion);
/*  625 */     _os_.marshal(this._notifymodifyserverdate);
/*  626 */     _os_.marshal(this._notifymodifyroamserverdate);
/*  627 */     _os_.marshal(this._modifyroamserverdatereq);
/*  628 */     _os_.marshal(this._modifyroamserverdatersp);
/*  629 */     _os_.marshal(this._singlecrossfieldjoinmatchreq);
/*  630 */     _os_.marshal(this._singlecrossfieldjoinmatchrsp);
/*  631 */     _os_.marshal(this._singlecrossfieldconfirmjoinmatchreq);
/*  632 */     _os_.marshal(this._singlecrossfieldconfirmjoinmatchrsp);
/*  633 */     _os_.marshal(this._singlecrossfieldroammatchcontextreq);
/*  634 */     _os_.marshal(this._singlecrossfieldroammatchcontextrsp);
/*  635 */     _os_.marshal(this._singlecrossfieldnotifymatchresultreq);
/*  636 */     _os_.marshal(this._singlecrossfieldnotifymatchresultrsp);
/*  637 */     _os_.marshal(this._singlecrossfieldcancelmatchreq);
/*  638 */     _os_.marshal(this._singlecrossfieldcancelmatchrsp);
/*  639 */     _os_.marshal(this._singlecrossfieldwaitnextroundmatchreq);
/*  640 */     _os_.marshal(this._singlecrossfieldwaitnextroundmatchrsp);
/*  641 */     _os_.marshal(this._singlecrossfielddatabackreq);
/*  642 */     _os_.marshal(this._singlecrossfielddatabackrsp);
/*  643 */     _os_.marshal(this._matchfailreason);
/*  644 */     _os_.marshal(this._transferchatcontentreq);
/*  645 */     _os_.marshal(this._transferchatcontentrsp);
/*  646 */     _os_.marshal(this._friendscirclegivegiftreq);
/*  647 */     _os_.marshal(this._friendscirclegivegiftrsp);
/*  648 */     _os_.marshal(this._friendscircledeletegivegifthistoryreq);
/*  649 */     _os_.marshal(this._friendscircledeletegivegifthistoryrsp);
/*  650 */     _os_.marshal(this._friendscircletreadreq);
/*  651 */     _os_.marshal(this._friendscircletreadrsp);
/*  652 */     _os_.marshal(this._friendscircledeletetreadhistoryreq);
/*  653 */     _os_.marshal(this._friendscircledeletetreadhistoryrsp);
/*  654 */     _os_.marshal(this._friendscircleoperatorblackreq);
/*  655 */     _os_.marshal(this._friendscircleoperatorblackrsp);
/*  656 */     _os_.marshal(this._recallnotifybindfriendreq);
/*  657 */     _os_.marshal(this._recallnotifybindfriendrsp);
/*  658 */     _os_.marshal(this._notifyindianaawardroleinfo);
/*  659 */     _os_.marshal(this._alllottoreportcandidateinforeq);
/*  660 */     _os_.marshal(this._alllottoreportcandidateinforsp);
/*  661 */     _os_.marshal(this._alllottonotifyawardroleinforeq);
/*  662 */     _os_.marshal(this._alllottonotifyawardroleinforsp);
/*  663 */     _os_.marshal(this._alllottobrdawardroleinfo);
/*  664 */     _os_.marshal(this._treasurebagexchangedata);
/*  665 */     return _os_;
/*      */   }
/*      */   
/*      */   public OctetsStream unmarshal(OctetsStream _os_) throws com.goldhuman.Common.Marshal.MarshalException {
/*  669 */     this._datatransfertype.unmarshal(_os_);
/*  670 */     this._databroadcasttype.unmarshal(_os_);
/*  671 */     this._genroamtokenreq.unmarshal(_os_);
/*  672 */     this._genroamtokenrsp.unmarshal(_os_);
/*  673 */     this._roamroledatareq.unmarshal(_os_);
/*  674 */     this._roamroledatarsp.unmarshal(_os_);
/*  675 */     this._validateroamtokenreq.unmarshal(_os_);
/*  676 */     this._validateroamtokenrsp.unmarshal(_os_);
/*  677 */     this._ladderdatabackreq.unmarshal(_os_);
/*  678 */     this._ladderdatabackrsp.unmarshal(_os_);
/*  679 */     this._roammatchcontextreq.unmarshal(_os_);
/*  680 */     this._roammatchcontextrsp.unmarshal(_os_);
/*  681 */     this._joinmatchreq.unmarshal(_os_);
/*  682 */     this._joinmatchrsp.unmarshal(_os_);
/*  683 */     this._notifymatchresultreq.unmarshal(_os_);
/*  684 */     this._notifymatchresultrsp.unmarshal(_os_);
/*  685 */     this._cancelmatchreq.unmarshal(_os_);
/*  686 */     this._cancelmatchrsp.unmarshal(_os_);
/*  687 */     this._waitnextroundmatchreq.unmarshal(_os_);
/*  688 */     this._waitnextroundmatchrsp.unmarshal(_os_);
/*  689 */     this._confirmjoinmatchreq.unmarshal(_os_);
/*  690 */     this._confirmjoinmatchrsp.unmarshal(_os_);
/*  691 */     this._reportgameserverbalanceinforeq.unmarshal(_os_);
/*  692 */     this._reportgameserverbalanceinforsp.unmarshal(_os_);
/*  693 */     this._crosscompetesignupfaction.unmarshal(_os_);
/*  694 */     this._reportcrosscompetesignupreq.unmarshal(_os_);
/*  695 */     this._reportcrosscompetesignuprsp.unmarshal(_os_);
/*  696 */     this._crosscompeteroamserversreq.unmarshal(_os_);
/*  697 */     this._crosscompeteroamserversrsp.unmarshal(_os_);
/*  698 */     this._notifycrosscompeteagainstreq.unmarshal(_os_);
/*  699 */     this._notifycrosscompeteagainstrsp.unmarshal(_os_);
/*  700 */     this._reportcrosscompetefactioninforeq.unmarshal(_os_);
/*  701 */     this._reportcrosscompetefactioninforsp.unmarshal(_os_);
/*  702 */     this._entercrosscompetemapreq.unmarshal(_os_);
/*  703 */     this._entercrosscompetemaprsp.unmarshal(_os_);
/*  704 */     this._crosscompeteroledatabackreq.unmarshal(_os_);
/*  705 */     this._crosscompeteroledatabackrsp.unmarshal(_os_);
/*  706 */     this._notifycrosscompeteresultreq.unmarshal(_os_);
/*  707 */     this._notifycrosscompeteresultrsp.unmarshal(_os_);
/*  708 */     this._crosscompeteteambackreq.unmarshal(_os_);
/*  709 */     this._crosscompeteteambackrsp.unmarshal(_os_);
/*  710 */     this._reportcorpsfightvaluereq.unmarshal(_os_);
/*  711 */     this._reportcorpsfightvaluersp.unmarshal(_os_);
/*  712 */     this._joinpointracereq.unmarshal(_os_);
/*  713 */     this._joinpointracersp.unmarshal(_os_);
/*  714 */     this._confirmjoinpointracereq.unmarshal(_os_);
/*  715 */     this._confirmjoinpointracersp.unmarshal(_os_);
/*  716 */     this._roampointracecontextreq.unmarshal(_os_);
/*  717 */     this._roampointracecontextrsp.unmarshal(_os_);
/*  718 */     this._notifypointraceresultreq.unmarshal(_os_);
/*  719 */     this._notifypointraceresultrsp.unmarshal(_os_);
/*  720 */     this._notifypointracependingreq.unmarshal(_os_);
/*  721 */     this._notifypointracependingrsp.unmarshal(_os_);
/*  722 */     this._roampointracedatareq.unmarshal(_os_);
/*  723 */     this._roampointracedatarsp.unmarshal(_os_);
/*  724 */     this._pointracedatabackreq.unmarshal(_os_);
/*  725 */     this._pointracedatabackrsp.unmarshal(_os_);
/*  726 */     this._updatepointracecorpsreq.unmarshal(_os_);
/*  727 */     this._updatepointracecorpsrsp.unmarshal(_os_);
/*  728 */     this._reportpointracecorpscvcreq.unmarshal(_os_);
/*  729 */     this._reportpointracecorpscvcrsp.unmarshal(_os_);
/*  730 */     this._pointraceendreq.unmarshal(_os_);
/*  731 */     this._pointraceendrsp.unmarshal(_os_);
/*  732 */     this._pointracequeryreq.unmarshal(_os_);
/*  733 */     this._pointracequeryrsp.unmarshal(_os_);
/*  734 */     this._joincrossbattleselectionorfinalreq.unmarshal(_os_);
/*  735 */     this._joincrossbattleselectionorfinalrsp.unmarshal(_os_);
/*  736 */     this._roamselectionorfinalcontextreq.unmarshal(_os_);
/*  737 */     this._roamselectionorfinalcontextrsp.unmarshal(_os_);
/*  738 */     this._notifyselectionorfinalmatchreq.unmarshal(_os_);
/*  739 */     this._notifyselectionorfinalmatchrsp.unmarshal(_os_);
/*  740 */     this._selectionorfinaldatabackreq.unmarshal(_os_);
/*  741 */     this._selectionorfinaldatabackrsp.unmarshal(_os_);
/*  742 */     this._selectionorfinalwaitnextroundmatchreq.unmarshal(_os_);
/*  743 */     this._selectionorfinalwaitnextroundmatchrsp.unmarshal(_os_);
/*  744 */     this._selectionorfinalfightbeginreq.unmarshal(_os_);
/*  745 */     this._selectionorfinalfightbeginrsp.unmarshal(_os_);
/*  746 */     this._confirmjoinselectionorfinalmatchreq.unmarshal(_os_);
/*  747 */     this._confirmjoinselectionorfinalmatchrsp.unmarshal(_os_);
/*  748 */     this._notifyselectionorfinalbyereq.unmarshal(_os_);
/*  749 */     this._notifyselectionorfinalbyersp.unmarshal(_os_);
/*  750 */     this._notifyfightrecordstartinfo.unmarshal(_os_);
/*  751 */     this._notifyfightrecordendinfo.unmarshal(_os_);
/*  752 */     this._notifyfightrecordroundinfo.unmarshal(_os_);
/*  753 */     this._notifycrossbattlefinalbulletion.unmarshal(_os_);
/*  754 */     this._notifymodifyserverdate.unmarshal(_os_);
/*  755 */     this._notifymodifyroamserverdate.unmarshal(_os_);
/*  756 */     this._modifyroamserverdatereq.unmarshal(_os_);
/*  757 */     this._modifyroamserverdatersp.unmarshal(_os_);
/*  758 */     this._singlecrossfieldjoinmatchreq.unmarshal(_os_);
/*  759 */     this._singlecrossfieldjoinmatchrsp.unmarshal(_os_);
/*  760 */     this._singlecrossfieldconfirmjoinmatchreq.unmarshal(_os_);
/*  761 */     this._singlecrossfieldconfirmjoinmatchrsp.unmarshal(_os_);
/*  762 */     this._singlecrossfieldroammatchcontextreq.unmarshal(_os_);
/*  763 */     this._singlecrossfieldroammatchcontextrsp.unmarshal(_os_);
/*  764 */     this._singlecrossfieldnotifymatchresultreq.unmarshal(_os_);
/*  765 */     this._singlecrossfieldnotifymatchresultrsp.unmarshal(_os_);
/*  766 */     this._singlecrossfieldcancelmatchreq.unmarshal(_os_);
/*  767 */     this._singlecrossfieldcancelmatchrsp.unmarshal(_os_);
/*  768 */     this._singlecrossfieldwaitnextroundmatchreq.unmarshal(_os_);
/*  769 */     this._singlecrossfieldwaitnextroundmatchrsp.unmarshal(_os_);
/*  770 */     this._singlecrossfielddatabackreq.unmarshal(_os_);
/*  771 */     this._singlecrossfielddatabackrsp.unmarshal(_os_);
/*  772 */     this._matchfailreason.unmarshal(_os_);
/*  773 */     this._transferchatcontentreq.unmarshal(_os_);
/*  774 */     this._transferchatcontentrsp.unmarshal(_os_);
/*  775 */     this._friendscirclegivegiftreq.unmarshal(_os_);
/*  776 */     this._friendscirclegivegiftrsp.unmarshal(_os_);
/*  777 */     this._friendscircledeletegivegifthistoryreq.unmarshal(_os_);
/*  778 */     this._friendscircledeletegivegifthistoryrsp.unmarshal(_os_);
/*  779 */     this._friendscircletreadreq.unmarshal(_os_);
/*  780 */     this._friendscircletreadrsp.unmarshal(_os_);
/*  781 */     this._friendscircledeletetreadhistoryreq.unmarshal(_os_);
/*  782 */     this._friendscircledeletetreadhistoryrsp.unmarshal(_os_);
/*  783 */     this._friendscircleoperatorblackreq.unmarshal(_os_);
/*  784 */     this._friendscircleoperatorblackrsp.unmarshal(_os_);
/*  785 */     this._recallnotifybindfriendreq.unmarshal(_os_);
/*  786 */     this._recallnotifybindfriendrsp.unmarshal(_os_);
/*  787 */     this._notifyindianaawardroleinfo.unmarshal(_os_);
/*  788 */     this._alllottoreportcandidateinforeq.unmarshal(_os_);
/*  789 */     this._alllottoreportcandidateinforsp.unmarshal(_os_);
/*  790 */     this._alllottonotifyawardroleinforeq.unmarshal(_os_);
/*  791 */     this._alllottonotifyawardroleinforsp.unmarshal(_os_);
/*  792 */     this._alllottobrdawardroleinfo.unmarshal(_os_);
/*  793 */     this._treasurebagexchangedata.unmarshal(_os_);
/*  794 */     if (!_validator_()) {
/*  795 */       throw new VerifyError("validator failed");
/*      */     }
/*  797 */     return _os_;
/*      */   }
/*      */   
/*      */   public boolean equals(Object _o1_) {
/*  801 */     if (_o1_ == this) return true;
/*  802 */     if ((_o1_ instanceof ImportDataTransferBeans)) {
/*  803 */       ImportDataTransferBeans _o_ = (ImportDataTransferBeans)_o1_;
/*  804 */       if (!this._datatransfertype.equals(_o_._datatransfertype)) return false;
/*  805 */       if (!this._databroadcasttype.equals(_o_._databroadcasttype)) return false;
/*  806 */       if (!this._genroamtokenreq.equals(_o_._genroamtokenreq)) return false;
/*  807 */       if (!this._genroamtokenrsp.equals(_o_._genroamtokenrsp)) return false;
/*  808 */       if (!this._roamroledatareq.equals(_o_._roamroledatareq)) return false;
/*  809 */       if (!this._roamroledatarsp.equals(_o_._roamroledatarsp)) return false;
/*  810 */       if (!this._validateroamtokenreq.equals(_o_._validateroamtokenreq)) return false;
/*  811 */       if (!this._validateroamtokenrsp.equals(_o_._validateroamtokenrsp)) return false;
/*  812 */       if (!this._ladderdatabackreq.equals(_o_._ladderdatabackreq)) return false;
/*  813 */       if (!this._ladderdatabackrsp.equals(_o_._ladderdatabackrsp)) return false;
/*  814 */       if (!this._roammatchcontextreq.equals(_o_._roammatchcontextreq)) return false;
/*  815 */       if (!this._roammatchcontextrsp.equals(_o_._roammatchcontextrsp)) return false;
/*  816 */       if (!this._joinmatchreq.equals(_o_._joinmatchreq)) return false;
/*  817 */       if (!this._joinmatchrsp.equals(_o_._joinmatchrsp)) return false;
/*  818 */       if (!this._notifymatchresultreq.equals(_o_._notifymatchresultreq)) return false;
/*  819 */       if (!this._notifymatchresultrsp.equals(_o_._notifymatchresultrsp)) return false;
/*  820 */       if (!this._cancelmatchreq.equals(_o_._cancelmatchreq)) return false;
/*  821 */       if (!this._cancelmatchrsp.equals(_o_._cancelmatchrsp)) return false;
/*  822 */       if (!this._waitnextroundmatchreq.equals(_o_._waitnextroundmatchreq)) return false;
/*  823 */       if (!this._waitnextroundmatchrsp.equals(_o_._waitnextroundmatchrsp)) return false;
/*  824 */       if (!this._confirmjoinmatchreq.equals(_o_._confirmjoinmatchreq)) return false;
/*  825 */       if (!this._confirmjoinmatchrsp.equals(_o_._confirmjoinmatchrsp)) return false;
/*  826 */       if (!this._reportgameserverbalanceinforeq.equals(_o_._reportgameserverbalanceinforeq)) return false;
/*  827 */       if (!this._reportgameserverbalanceinforsp.equals(_o_._reportgameserverbalanceinforsp)) return false;
/*  828 */       if (!this._crosscompetesignupfaction.equals(_o_._crosscompetesignupfaction)) return false;
/*  829 */       if (!this._reportcrosscompetesignupreq.equals(_o_._reportcrosscompetesignupreq)) return false;
/*  830 */       if (!this._reportcrosscompetesignuprsp.equals(_o_._reportcrosscompetesignuprsp)) return false;
/*  831 */       if (!this._crosscompeteroamserversreq.equals(_o_._crosscompeteroamserversreq)) return false;
/*  832 */       if (!this._crosscompeteroamserversrsp.equals(_o_._crosscompeteroamserversrsp)) return false;
/*  833 */       if (!this._notifycrosscompeteagainstreq.equals(_o_._notifycrosscompeteagainstreq)) return false;
/*  834 */       if (!this._notifycrosscompeteagainstrsp.equals(_o_._notifycrosscompeteagainstrsp)) return false;
/*  835 */       if (!this._reportcrosscompetefactioninforeq.equals(_o_._reportcrosscompetefactioninforeq)) return false;
/*  836 */       if (!this._reportcrosscompetefactioninforsp.equals(_o_._reportcrosscompetefactioninforsp)) return false;
/*  837 */       if (!this._entercrosscompetemapreq.equals(_o_._entercrosscompetemapreq)) return false;
/*  838 */       if (!this._entercrosscompetemaprsp.equals(_o_._entercrosscompetemaprsp)) return false;
/*  839 */       if (!this._crosscompeteroledatabackreq.equals(_o_._crosscompeteroledatabackreq)) return false;
/*  840 */       if (!this._crosscompeteroledatabackrsp.equals(_o_._crosscompeteroledatabackrsp)) return false;
/*  841 */       if (!this._notifycrosscompeteresultreq.equals(_o_._notifycrosscompeteresultreq)) return false;
/*  842 */       if (!this._notifycrosscompeteresultrsp.equals(_o_._notifycrosscompeteresultrsp)) return false;
/*  843 */       if (!this._crosscompeteteambackreq.equals(_o_._crosscompeteteambackreq)) return false;
/*  844 */       if (!this._crosscompeteteambackrsp.equals(_o_._crosscompeteteambackrsp)) return false;
/*  845 */       if (!this._reportcorpsfightvaluereq.equals(_o_._reportcorpsfightvaluereq)) return false;
/*  846 */       if (!this._reportcorpsfightvaluersp.equals(_o_._reportcorpsfightvaluersp)) return false;
/*  847 */       if (!this._joinpointracereq.equals(_o_._joinpointracereq)) return false;
/*  848 */       if (!this._joinpointracersp.equals(_o_._joinpointracersp)) return false;
/*  849 */       if (!this._confirmjoinpointracereq.equals(_o_._confirmjoinpointracereq)) return false;
/*  850 */       if (!this._confirmjoinpointracersp.equals(_o_._confirmjoinpointracersp)) return false;
/*  851 */       if (!this._roampointracecontextreq.equals(_o_._roampointracecontextreq)) return false;
/*  852 */       if (!this._roampointracecontextrsp.equals(_o_._roampointracecontextrsp)) return false;
/*  853 */       if (!this._notifypointraceresultreq.equals(_o_._notifypointraceresultreq)) return false;
/*  854 */       if (!this._notifypointraceresultrsp.equals(_o_._notifypointraceresultrsp)) return false;
/*  855 */       if (!this._notifypointracependingreq.equals(_o_._notifypointracependingreq)) return false;
/*  856 */       if (!this._notifypointracependingrsp.equals(_o_._notifypointracependingrsp)) return false;
/*  857 */       if (!this._roampointracedatareq.equals(_o_._roampointracedatareq)) return false;
/*  858 */       if (!this._roampointracedatarsp.equals(_o_._roampointracedatarsp)) return false;
/*  859 */       if (!this._pointracedatabackreq.equals(_o_._pointracedatabackreq)) return false;
/*  860 */       if (!this._pointracedatabackrsp.equals(_o_._pointracedatabackrsp)) return false;
/*  861 */       if (!this._updatepointracecorpsreq.equals(_o_._updatepointracecorpsreq)) return false;
/*  862 */       if (!this._updatepointracecorpsrsp.equals(_o_._updatepointracecorpsrsp)) return false;
/*  863 */       if (!this._reportpointracecorpscvcreq.equals(_o_._reportpointracecorpscvcreq)) return false;
/*  864 */       if (!this._reportpointracecorpscvcrsp.equals(_o_._reportpointracecorpscvcrsp)) return false;
/*  865 */       if (!this._pointraceendreq.equals(_o_._pointraceendreq)) return false;
/*  866 */       if (!this._pointraceendrsp.equals(_o_._pointraceendrsp)) return false;
/*  867 */       if (!this._pointracequeryreq.equals(_o_._pointracequeryreq)) return false;
/*  868 */       if (!this._pointracequeryrsp.equals(_o_._pointracequeryrsp)) return false;
/*  869 */       if (!this._joincrossbattleselectionorfinalreq.equals(_o_._joincrossbattleselectionorfinalreq)) return false;
/*  870 */       if (!this._joincrossbattleselectionorfinalrsp.equals(_o_._joincrossbattleselectionorfinalrsp)) return false;
/*  871 */       if (!this._roamselectionorfinalcontextreq.equals(_o_._roamselectionorfinalcontextreq)) return false;
/*  872 */       if (!this._roamselectionorfinalcontextrsp.equals(_o_._roamselectionorfinalcontextrsp)) return false;
/*  873 */       if (!this._notifyselectionorfinalmatchreq.equals(_o_._notifyselectionorfinalmatchreq)) return false;
/*  874 */       if (!this._notifyselectionorfinalmatchrsp.equals(_o_._notifyselectionorfinalmatchrsp)) return false;
/*  875 */       if (!this._selectionorfinaldatabackreq.equals(_o_._selectionorfinaldatabackreq)) return false;
/*  876 */       if (!this._selectionorfinaldatabackrsp.equals(_o_._selectionorfinaldatabackrsp)) return false;
/*  877 */       if (!this._selectionorfinalwaitnextroundmatchreq.equals(_o_._selectionorfinalwaitnextroundmatchreq)) return false;
/*  878 */       if (!this._selectionorfinalwaitnextroundmatchrsp.equals(_o_._selectionorfinalwaitnextroundmatchrsp)) return false;
/*  879 */       if (!this._selectionorfinalfightbeginreq.equals(_o_._selectionorfinalfightbeginreq)) return false;
/*  880 */       if (!this._selectionorfinalfightbeginrsp.equals(_o_._selectionorfinalfightbeginrsp)) return false;
/*  881 */       if (!this._confirmjoinselectionorfinalmatchreq.equals(_o_._confirmjoinselectionorfinalmatchreq)) return false;
/*  882 */       if (!this._confirmjoinselectionorfinalmatchrsp.equals(_o_._confirmjoinselectionorfinalmatchrsp)) return false;
/*  883 */       if (!this._notifyselectionorfinalbyereq.equals(_o_._notifyselectionorfinalbyereq)) return false;
/*  884 */       if (!this._notifyselectionorfinalbyersp.equals(_o_._notifyselectionorfinalbyersp)) return false;
/*  885 */       if (!this._notifyfightrecordstartinfo.equals(_o_._notifyfightrecordstartinfo)) return false;
/*  886 */       if (!this._notifyfightrecordendinfo.equals(_o_._notifyfightrecordendinfo)) return false;
/*  887 */       if (!this._notifyfightrecordroundinfo.equals(_o_._notifyfightrecordroundinfo)) return false;
/*  888 */       if (!this._notifycrossbattlefinalbulletion.equals(_o_._notifycrossbattlefinalbulletion)) return false;
/*  889 */       if (!this._notifymodifyserverdate.equals(_o_._notifymodifyserverdate)) return false;
/*  890 */       if (!this._notifymodifyroamserverdate.equals(_o_._notifymodifyroamserverdate)) return false;
/*  891 */       if (!this._modifyroamserverdatereq.equals(_o_._modifyroamserverdatereq)) return false;
/*  892 */       if (!this._modifyroamserverdatersp.equals(_o_._modifyroamserverdatersp)) return false;
/*  893 */       if (!this._singlecrossfieldjoinmatchreq.equals(_o_._singlecrossfieldjoinmatchreq)) return false;
/*  894 */       if (!this._singlecrossfieldjoinmatchrsp.equals(_o_._singlecrossfieldjoinmatchrsp)) return false;
/*  895 */       if (!this._singlecrossfieldconfirmjoinmatchreq.equals(_o_._singlecrossfieldconfirmjoinmatchreq)) return false;
/*  896 */       if (!this._singlecrossfieldconfirmjoinmatchrsp.equals(_o_._singlecrossfieldconfirmjoinmatchrsp)) return false;
/*  897 */       if (!this._singlecrossfieldroammatchcontextreq.equals(_o_._singlecrossfieldroammatchcontextreq)) return false;
/*  898 */       if (!this._singlecrossfieldroammatchcontextrsp.equals(_o_._singlecrossfieldroammatchcontextrsp)) return false;
/*  899 */       if (!this._singlecrossfieldnotifymatchresultreq.equals(_o_._singlecrossfieldnotifymatchresultreq)) return false;
/*  900 */       if (!this._singlecrossfieldnotifymatchresultrsp.equals(_o_._singlecrossfieldnotifymatchresultrsp)) return false;
/*  901 */       if (!this._singlecrossfieldcancelmatchreq.equals(_o_._singlecrossfieldcancelmatchreq)) return false;
/*  902 */       if (!this._singlecrossfieldcancelmatchrsp.equals(_o_._singlecrossfieldcancelmatchrsp)) return false;
/*  903 */       if (!this._singlecrossfieldwaitnextroundmatchreq.equals(_o_._singlecrossfieldwaitnextroundmatchreq)) return false;
/*  904 */       if (!this._singlecrossfieldwaitnextroundmatchrsp.equals(_o_._singlecrossfieldwaitnextroundmatchrsp)) return false;
/*  905 */       if (!this._singlecrossfielddatabackreq.equals(_o_._singlecrossfielddatabackreq)) return false;
/*  906 */       if (!this._singlecrossfielddatabackrsp.equals(_o_._singlecrossfielddatabackrsp)) return false;
/*  907 */       if (!this._matchfailreason.equals(_o_._matchfailreason)) return false;
/*  908 */       if (!this._transferchatcontentreq.equals(_o_._transferchatcontentreq)) return false;
/*  909 */       if (!this._transferchatcontentrsp.equals(_o_._transferchatcontentrsp)) return false;
/*  910 */       if (!this._friendscirclegivegiftreq.equals(_o_._friendscirclegivegiftreq)) return false;
/*  911 */       if (!this._friendscirclegivegiftrsp.equals(_o_._friendscirclegivegiftrsp)) return false;
/*  912 */       if (!this._friendscircledeletegivegifthistoryreq.equals(_o_._friendscircledeletegivegifthistoryreq)) return false;
/*  913 */       if (!this._friendscircledeletegivegifthistoryrsp.equals(_o_._friendscircledeletegivegifthistoryrsp)) return false;
/*  914 */       if (!this._friendscircletreadreq.equals(_o_._friendscircletreadreq)) return false;
/*  915 */       if (!this._friendscircletreadrsp.equals(_o_._friendscircletreadrsp)) return false;
/*  916 */       if (!this._friendscircledeletetreadhistoryreq.equals(_o_._friendscircledeletetreadhistoryreq)) return false;
/*  917 */       if (!this._friendscircledeletetreadhistoryrsp.equals(_o_._friendscircledeletetreadhistoryrsp)) return false;
/*  918 */       if (!this._friendscircleoperatorblackreq.equals(_o_._friendscircleoperatorblackreq)) return false;
/*  919 */       if (!this._friendscircleoperatorblackrsp.equals(_o_._friendscircleoperatorblackrsp)) return false;
/*  920 */       if (!this._recallnotifybindfriendreq.equals(_o_._recallnotifybindfriendreq)) return false;
/*  921 */       if (!this._recallnotifybindfriendrsp.equals(_o_._recallnotifybindfriendrsp)) return false;
/*  922 */       if (!this._notifyindianaawardroleinfo.equals(_o_._notifyindianaawardroleinfo)) return false;
/*  923 */       if (!this._alllottoreportcandidateinforeq.equals(_o_._alllottoreportcandidateinforeq)) return false;
/*  924 */       if (!this._alllottoreportcandidateinforsp.equals(_o_._alllottoreportcandidateinforsp)) return false;
/*  925 */       if (!this._alllottonotifyawardroleinforeq.equals(_o_._alllottonotifyawardroleinforeq)) return false;
/*  926 */       if (!this._alllottonotifyawardroleinforsp.equals(_o_._alllottonotifyawardroleinforsp)) return false;
/*  927 */       if (!this._alllottobrdawardroleinfo.equals(_o_._alllottobrdawardroleinfo)) return false;
/*  928 */       if (!this._treasurebagexchangedata.equals(_o_._treasurebagexchangedata)) return false;
/*  929 */       return true;
/*      */     }
/*  931 */     return false;
/*      */   }
/*      */   
/*      */   public int hashCode() {
/*  935 */     int _h_ = 0;
/*  936 */     _h_ += this._datatransfertype.hashCode();
/*  937 */     _h_ += this._databroadcasttype.hashCode();
/*  938 */     _h_ += this._genroamtokenreq.hashCode();
/*  939 */     _h_ += this._genroamtokenrsp.hashCode();
/*  940 */     _h_ += this._roamroledatareq.hashCode();
/*  941 */     _h_ += this._roamroledatarsp.hashCode();
/*  942 */     _h_ += this._validateroamtokenreq.hashCode();
/*  943 */     _h_ += this._validateroamtokenrsp.hashCode();
/*  944 */     _h_ += this._ladderdatabackreq.hashCode();
/*  945 */     _h_ += this._ladderdatabackrsp.hashCode();
/*  946 */     _h_ += this._roammatchcontextreq.hashCode();
/*  947 */     _h_ += this._roammatchcontextrsp.hashCode();
/*  948 */     _h_ += this._joinmatchreq.hashCode();
/*  949 */     _h_ += this._joinmatchrsp.hashCode();
/*  950 */     _h_ += this._notifymatchresultreq.hashCode();
/*  951 */     _h_ += this._notifymatchresultrsp.hashCode();
/*  952 */     _h_ += this._cancelmatchreq.hashCode();
/*  953 */     _h_ += this._cancelmatchrsp.hashCode();
/*  954 */     _h_ += this._waitnextroundmatchreq.hashCode();
/*  955 */     _h_ += this._waitnextroundmatchrsp.hashCode();
/*  956 */     _h_ += this._confirmjoinmatchreq.hashCode();
/*  957 */     _h_ += this._confirmjoinmatchrsp.hashCode();
/*  958 */     _h_ += this._reportgameserverbalanceinforeq.hashCode();
/*  959 */     _h_ += this._reportgameserverbalanceinforsp.hashCode();
/*  960 */     _h_ += this._crosscompetesignupfaction.hashCode();
/*  961 */     _h_ += this._reportcrosscompetesignupreq.hashCode();
/*  962 */     _h_ += this._reportcrosscompetesignuprsp.hashCode();
/*  963 */     _h_ += this._crosscompeteroamserversreq.hashCode();
/*  964 */     _h_ += this._crosscompeteroamserversrsp.hashCode();
/*  965 */     _h_ += this._notifycrosscompeteagainstreq.hashCode();
/*  966 */     _h_ += this._notifycrosscompeteagainstrsp.hashCode();
/*  967 */     _h_ += this._reportcrosscompetefactioninforeq.hashCode();
/*  968 */     _h_ += this._reportcrosscompetefactioninforsp.hashCode();
/*  969 */     _h_ += this._entercrosscompetemapreq.hashCode();
/*  970 */     _h_ += this._entercrosscompetemaprsp.hashCode();
/*  971 */     _h_ += this._crosscompeteroledatabackreq.hashCode();
/*  972 */     _h_ += this._crosscompeteroledatabackrsp.hashCode();
/*  973 */     _h_ += this._notifycrosscompeteresultreq.hashCode();
/*  974 */     _h_ += this._notifycrosscompeteresultrsp.hashCode();
/*  975 */     _h_ += this._crosscompeteteambackreq.hashCode();
/*  976 */     _h_ += this._crosscompeteteambackrsp.hashCode();
/*  977 */     _h_ += this._reportcorpsfightvaluereq.hashCode();
/*  978 */     _h_ += this._reportcorpsfightvaluersp.hashCode();
/*  979 */     _h_ += this._joinpointracereq.hashCode();
/*  980 */     _h_ += this._joinpointracersp.hashCode();
/*  981 */     _h_ += this._confirmjoinpointracereq.hashCode();
/*  982 */     _h_ += this._confirmjoinpointracersp.hashCode();
/*  983 */     _h_ += this._roampointracecontextreq.hashCode();
/*  984 */     _h_ += this._roampointracecontextrsp.hashCode();
/*  985 */     _h_ += this._notifypointraceresultreq.hashCode();
/*  986 */     _h_ += this._notifypointraceresultrsp.hashCode();
/*  987 */     _h_ += this._notifypointracependingreq.hashCode();
/*  988 */     _h_ += this._notifypointracependingrsp.hashCode();
/*  989 */     _h_ += this._roampointracedatareq.hashCode();
/*  990 */     _h_ += this._roampointracedatarsp.hashCode();
/*  991 */     _h_ += this._pointracedatabackreq.hashCode();
/*  992 */     _h_ += this._pointracedatabackrsp.hashCode();
/*  993 */     _h_ += this._updatepointracecorpsreq.hashCode();
/*  994 */     _h_ += this._updatepointracecorpsrsp.hashCode();
/*  995 */     _h_ += this._reportpointracecorpscvcreq.hashCode();
/*  996 */     _h_ += this._reportpointracecorpscvcrsp.hashCode();
/*  997 */     _h_ += this._pointraceendreq.hashCode();
/*  998 */     _h_ += this._pointraceendrsp.hashCode();
/*  999 */     _h_ += this._pointracequeryreq.hashCode();
/* 1000 */     _h_ += this._pointracequeryrsp.hashCode();
/* 1001 */     _h_ += this._joincrossbattleselectionorfinalreq.hashCode();
/* 1002 */     _h_ += this._joincrossbattleselectionorfinalrsp.hashCode();
/* 1003 */     _h_ += this._roamselectionorfinalcontextreq.hashCode();
/* 1004 */     _h_ += this._roamselectionorfinalcontextrsp.hashCode();
/* 1005 */     _h_ += this._notifyselectionorfinalmatchreq.hashCode();
/* 1006 */     _h_ += this._notifyselectionorfinalmatchrsp.hashCode();
/* 1007 */     _h_ += this._selectionorfinaldatabackreq.hashCode();
/* 1008 */     _h_ += this._selectionorfinaldatabackrsp.hashCode();
/* 1009 */     _h_ += this._selectionorfinalwaitnextroundmatchreq.hashCode();
/* 1010 */     _h_ += this._selectionorfinalwaitnextroundmatchrsp.hashCode();
/* 1011 */     _h_ += this._selectionorfinalfightbeginreq.hashCode();
/* 1012 */     _h_ += this._selectionorfinalfightbeginrsp.hashCode();
/* 1013 */     _h_ += this._confirmjoinselectionorfinalmatchreq.hashCode();
/* 1014 */     _h_ += this._confirmjoinselectionorfinalmatchrsp.hashCode();
/* 1015 */     _h_ += this._notifyselectionorfinalbyereq.hashCode();
/* 1016 */     _h_ += this._notifyselectionorfinalbyersp.hashCode();
/* 1017 */     _h_ += this._notifyfightrecordstartinfo.hashCode();
/* 1018 */     _h_ += this._notifyfightrecordendinfo.hashCode();
/* 1019 */     _h_ += this._notifyfightrecordroundinfo.hashCode();
/* 1020 */     _h_ += this._notifycrossbattlefinalbulletion.hashCode();
/* 1021 */     _h_ += this._notifymodifyserverdate.hashCode();
/* 1022 */     _h_ += this._notifymodifyroamserverdate.hashCode();
/* 1023 */     _h_ += this._modifyroamserverdatereq.hashCode();
/* 1024 */     _h_ += this._modifyroamserverdatersp.hashCode();
/* 1025 */     _h_ += this._singlecrossfieldjoinmatchreq.hashCode();
/* 1026 */     _h_ += this._singlecrossfieldjoinmatchrsp.hashCode();
/* 1027 */     _h_ += this._singlecrossfieldconfirmjoinmatchreq.hashCode();
/* 1028 */     _h_ += this._singlecrossfieldconfirmjoinmatchrsp.hashCode();
/* 1029 */     _h_ += this._singlecrossfieldroammatchcontextreq.hashCode();
/* 1030 */     _h_ += this._singlecrossfieldroammatchcontextrsp.hashCode();
/* 1031 */     _h_ += this._singlecrossfieldnotifymatchresultreq.hashCode();
/* 1032 */     _h_ += this._singlecrossfieldnotifymatchresultrsp.hashCode();
/* 1033 */     _h_ += this._singlecrossfieldcancelmatchreq.hashCode();
/* 1034 */     _h_ += this._singlecrossfieldcancelmatchrsp.hashCode();
/* 1035 */     _h_ += this._singlecrossfieldwaitnextroundmatchreq.hashCode();
/* 1036 */     _h_ += this._singlecrossfieldwaitnextroundmatchrsp.hashCode();
/* 1037 */     _h_ += this._singlecrossfielddatabackreq.hashCode();
/* 1038 */     _h_ += this._singlecrossfielddatabackrsp.hashCode();
/* 1039 */     _h_ += this._matchfailreason.hashCode();
/* 1040 */     _h_ += this._transferchatcontentreq.hashCode();
/* 1041 */     _h_ += this._transferchatcontentrsp.hashCode();
/* 1042 */     _h_ += this._friendscirclegivegiftreq.hashCode();
/* 1043 */     _h_ += this._friendscirclegivegiftrsp.hashCode();
/* 1044 */     _h_ += this._friendscircledeletegivegifthistoryreq.hashCode();
/* 1045 */     _h_ += this._friendscircledeletegivegifthistoryrsp.hashCode();
/* 1046 */     _h_ += this._friendscircletreadreq.hashCode();
/* 1047 */     _h_ += this._friendscircletreadrsp.hashCode();
/* 1048 */     _h_ += this._friendscircledeletetreadhistoryreq.hashCode();
/* 1049 */     _h_ += this._friendscircledeletetreadhistoryrsp.hashCode();
/* 1050 */     _h_ += this._friendscircleoperatorblackreq.hashCode();
/* 1051 */     _h_ += this._friendscircleoperatorblackrsp.hashCode();
/* 1052 */     _h_ += this._recallnotifybindfriendreq.hashCode();
/* 1053 */     _h_ += this._recallnotifybindfriendrsp.hashCode();
/* 1054 */     _h_ += this._notifyindianaawardroleinfo.hashCode();
/* 1055 */     _h_ += this._alllottoreportcandidateinforeq.hashCode();
/* 1056 */     _h_ += this._alllottoreportcandidateinforsp.hashCode();
/* 1057 */     _h_ += this._alllottonotifyawardroleinforeq.hashCode();
/* 1058 */     _h_ += this._alllottonotifyawardroleinforsp.hashCode();
/* 1059 */     _h_ += this._alllottobrdawardroleinfo.hashCode();
/* 1060 */     _h_ += this._treasurebagexchangedata.hashCode();
/* 1061 */     return _h_;
/*      */   }
/*      */   
/*      */   public String toString() {
/* 1065 */     StringBuilder _sb_ = new StringBuilder();
/* 1066 */     _sb_.append("(");
/* 1067 */     _sb_.append(this._datatransfertype).append(",");
/* 1068 */     _sb_.append(this._databroadcasttype).append(",");
/* 1069 */     _sb_.append(this._genroamtokenreq).append(",");
/* 1070 */     _sb_.append(this._genroamtokenrsp).append(",");
/* 1071 */     _sb_.append(this._roamroledatareq).append(",");
/* 1072 */     _sb_.append(this._roamroledatarsp).append(",");
/* 1073 */     _sb_.append(this._validateroamtokenreq).append(",");
/* 1074 */     _sb_.append(this._validateroamtokenrsp).append(",");
/* 1075 */     _sb_.append(this._ladderdatabackreq).append(",");
/* 1076 */     _sb_.append(this._ladderdatabackrsp).append(",");
/* 1077 */     _sb_.append(this._roammatchcontextreq).append(",");
/* 1078 */     _sb_.append(this._roammatchcontextrsp).append(",");
/* 1079 */     _sb_.append(this._joinmatchreq).append(",");
/* 1080 */     _sb_.append(this._joinmatchrsp).append(",");
/* 1081 */     _sb_.append(this._notifymatchresultreq).append(",");
/* 1082 */     _sb_.append(this._notifymatchresultrsp).append(",");
/* 1083 */     _sb_.append(this._cancelmatchreq).append(",");
/* 1084 */     _sb_.append(this._cancelmatchrsp).append(",");
/* 1085 */     _sb_.append(this._waitnextroundmatchreq).append(",");
/* 1086 */     _sb_.append(this._waitnextroundmatchrsp).append(",");
/* 1087 */     _sb_.append(this._confirmjoinmatchreq).append(",");
/* 1088 */     _sb_.append(this._confirmjoinmatchrsp).append(",");
/* 1089 */     _sb_.append(this._reportgameserverbalanceinforeq).append(",");
/* 1090 */     _sb_.append(this._reportgameserverbalanceinforsp).append(",");
/* 1091 */     _sb_.append(this._crosscompetesignupfaction).append(",");
/* 1092 */     _sb_.append(this._reportcrosscompetesignupreq).append(",");
/* 1093 */     _sb_.append(this._reportcrosscompetesignuprsp).append(",");
/* 1094 */     _sb_.append(this._crosscompeteroamserversreq).append(",");
/* 1095 */     _sb_.append(this._crosscompeteroamserversrsp).append(",");
/* 1096 */     _sb_.append(this._notifycrosscompeteagainstreq).append(",");
/* 1097 */     _sb_.append(this._notifycrosscompeteagainstrsp).append(",");
/* 1098 */     _sb_.append(this._reportcrosscompetefactioninforeq).append(",");
/* 1099 */     _sb_.append(this._reportcrosscompetefactioninforsp).append(",");
/* 1100 */     _sb_.append(this._entercrosscompetemapreq).append(",");
/* 1101 */     _sb_.append(this._entercrosscompetemaprsp).append(",");
/* 1102 */     _sb_.append(this._crosscompeteroledatabackreq).append(",");
/* 1103 */     _sb_.append(this._crosscompeteroledatabackrsp).append(",");
/* 1104 */     _sb_.append(this._notifycrosscompeteresultreq).append(",");
/* 1105 */     _sb_.append(this._notifycrosscompeteresultrsp).append(",");
/* 1106 */     _sb_.append(this._crosscompeteteambackreq).append(",");
/* 1107 */     _sb_.append(this._crosscompeteteambackrsp).append(",");
/* 1108 */     _sb_.append(this._reportcorpsfightvaluereq).append(",");
/* 1109 */     _sb_.append(this._reportcorpsfightvaluersp).append(",");
/* 1110 */     _sb_.append(this._joinpointracereq).append(",");
/* 1111 */     _sb_.append(this._joinpointracersp).append(",");
/* 1112 */     _sb_.append(this._confirmjoinpointracereq).append(",");
/* 1113 */     _sb_.append(this._confirmjoinpointracersp).append(",");
/* 1114 */     _sb_.append(this._roampointracecontextreq).append(",");
/* 1115 */     _sb_.append(this._roampointracecontextrsp).append(",");
/* 1116 */     _sb_.append(this._notifypointraceresultreq).append(",");
/* 1117 */     _sb_.append(this._notifypointraceresultrsp).append(",");
/* 1118 */     _sb_.append(this._notifypointracependingreq).append(",");
/* 1119 */     _sb_.append(this._notifypointracependingrsp).append(",");
/* 1120 */     _sb_.append(this._roampointracedatareq).append(",");
/* 1121 */     _sb_.append(this._roampointracedatarsp).append(",");
/* 1122 */     _sb_.append(this._pointracedatabackreq).append(",");
/* 1123 */     _sb_.append(this._pointracedatabackrsp).append(",");
/* 1124 */     _sb_.append(this._updatepointracecorpsreq).append(",");
/* 1125 */     _sb_.append(this._updatepointracecorpsrsp).append(",");
/* 1126 */     _sb_.append(this._reportpointracecorpscvcreq).append(",");
/* 1127 */     _sb_.append(this._reportpointracecorpscvcrsp).append(",");
/* 1128 */     _sb_.append(this._pointraceendreq).append(",");
/* 1129 */     _sb_.append(this._pointraceendrsp).append(",");
/* 1130 */     _sb_.append(this._pointracequeryreq).append(",");
/* 1131 */     _sb_.append(this._pointracequeryrsp).append(",");
/* 1132 */     _sb_.append(this._joincrossbattleselectionorfinalreq).append(",");
/* 1133 */     _sb_.append(this._joincrossbattleselectionorfinalrsp).append(",");
/* 1134 */     _sb_.append(this._roamselectionorfinalcontextreq).append(",");
/* 1135 */     _sb_.append(this._roamselectionorfinalcontextrsp).append(",");
/* 1136 */     _sb_.append(this._notifyselectionorfinalmatchreq).append(",");
/* 1137 */     _sb_.append(this._notifyselectionorfinalmatchrsp).append(",");
/* 1138 */     _sb_.append(this._selectionorfinaldatabackreq).append(",");
/* 1139 */     _sb_.append(this._selectionorfinaldatabackrsp).append(",");
/* 1140 */     _sb_.append(this._selectionorfinalwaitnextroundmatchreq).append(",");
/* 1141 */     _sb_.append(this._selectionorfinalwaitnextroundmatchrsp).append(",");
/* 1142 */     _sb_.append(this._selectionorfinalfightbeginreq).append(",");
/* 1143 */     _sb_.append(this._selectionorfinalfightbeginrsp).append(",");
/* 1144 */     _sb_.append(this._confirmjoinselectionorfinalmatchreq).append(",");
/* 1145 */     _sb_.append(this._confirmjoinselectionorfinalmatchrsp).append(",");
/* 1146 */     _sb_.append(this._notifyselectionorfinalbyereq).append(",");
/* 1147 */     _sb_.append(this._notifyselectionorfinalbyersp).append(",");
/* 1148 */     _sb_.append(this._notifyfightrecordstartinfo).append(",");
/* 1149 */     _sb_.append(this._notifyfightrecordendinfo).append(",");
/* 1150 */     _sb_.append(this._notifyfightrecordroundinfo).append(",");
/* 1151 */     _sb_.append(this._notifycrossbattlefinalbulletion).append(",");
/* 1152 */     _sb_.append(this._notifymodifyserverdate).append(",");
/* 1153 */     _sb_.append(this._notifymodifyroamserverdate).append(",");
/* 1154 */     _sb_.append(this._modifyroamserverdatereq).append(",");
/* 1155 */     _sb_.append(this._modifyroamserverdatersp).append(",");
/* 1156 */     _sb_.append(this._singlecrossfieldjoinmatchreq).append(",");
/* 1157 */     _sb_.append(this._singlecrossfieldjoinmatchrsp).append(",");
/* 1158 */     _sb_.append(this._singlecrossfieldconfirmjoinmatchreq).append(",");
/* 1159 */     _sb_.append(this._singlecrossfieldconfirmjoinmatchrsp).append(",");
/* 1160 */     _sb_.append(this._singlecrossfieldroammatchcontextreq).append(",");
/* 1161 */     _sb_.append(this._singlecrossfieldroammatchcontextrsp).append(",");
/* 1162 */     _sb_.append(this._singlecrossfieldnotifymatchresultreq).append(",");
/* 1163 */     _sb_.append(this._singlecrossfieldnotifymatchresultrsp).append(",");
/* 1164 */     _sb_.append(this._singlecrossfieldcancelmatchreq).append(",");
/* 1165 */     _sb_.append(this._singlecrossfieldcancelmatchrsp).append(",");
/* 1166 */     _sb_.append(this._singlecrossfieldwaitnextroundmatchreq).append(",");
/* 1167 */     _sb_.append(this._singlecrossfieldwaitnextroundmatchrsp).append(",");
/* 1168 */     _sb_.append(this._singlecrossfielddatabackreq).append(",");
/* 1169 */     _sb_.append(this._singlecrossfielddatabackrsp).append(",");
/* 1170 */     _sb_.append(this._matchfailreason).append(",");
/* 1171 */     _sb_.append(this._transferchatcontentreq).append(",");
/* 1172 */     _sb_.append(this._transferchatcontentrsp).append(",");
/* 1173 */     _sb_.append(this._friendscirclegivegiftreq).append(",");
/* 1174 */     _sb_.append(this._friendscirclegivegiftrsp).append(",");
/* 1175 */     _sb_.append(this._friendscircledeletegivegifthistoryreq).append(",");
/* 1176 */     _sb_.append(this._friendscircledeletegivegifthistoryrsp).append(",");
/* 1177 */     _sb_.append(this._friendscircletreadreq).append(",");
/* 1178 */     _sb_.append(this._friendscircletreadrsp).append(",");
/* 1179 */     _sb_.append(this._friendscircledeletetreadhistoryreq).append(",");
/* 1180 */     _sb_.append(this._friendscircledeletetreadhistoryrsp).append(",");
/* 1181 */     _sb_.append(this._friendscircleoperatorblackreq).append(",");
/* 1182 */     _sb_.append(this._friendscircleoperatorblackrsp).append(",");
/* 1183 */     _sb_.append(this._recallnotifybindfriendreq).append(",");
/* 1184 */     _sb_.append(this._recallnotifybindfriendrsp).append(",");
/* 1185 */     _sb_.append(this._notifyindianaawardroleinfo).append(",");
/* 1186 */     _sb_.append(this._alllottoreportcandidateinforeq).append(",");
/* 1187 */     _sb_.append(this._alllottoreportcandidateinforsp).append(",");
/* 1188 */     _sb_.append(this._alllottonotifyawardroleinforeq).append(",");
/* 1189 */     _sb_.append(this._alllottonotifyawardroleinforsp).append(",");
/* 1190 */     _sb_.append(this._alllottobrdawardroleinfo).append(",");
/* 1191 */     _sb_.append(this._treasurebagexchangedata).append(",");
/* 1192 */     _sb_.append(")");
/* 1193 */     return _sb_.toString();
/*      */   }
/*      */ }


/* Location:              D:\桌面\山海\gsxdbdebug.jar!\hub\ImportDataTransferBeans.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */