/*     */ package mzm.gsp.open;
/*     */ 
/*     */ import com.goldhuman.Common.Marshal.Marshal;
/*     */ import com.goldhuman.Common.Marshal.MarshalException;
/*     */ import com.goldhuman.Common.Marshal.OctetsStream;
/*     */ import java.util.LinkedList;
/*     */ 
/*     */ public class ModuleFunSwitchInfo
/*     */   implements Marshal
/*     */ {
/*     */   public static final int TYPE_SHIMENRENWU = 0;
/*     */   public static final int TYPE_ZHENYAOHUODONG = 1;
/*     */   public static final int TYPE_CANGBAOTU = 2;
/*     */   public static final int TYPE_SHANGJINLIEREN = 3;
/*     */   public static final int TYPE_HEILONGHAOJIE = 4;
/*     */   public static final int TYPE_HUSONG = 5;
/*     */   public static final int TYPE_SHILIAN = 6;
/*     */   public static final int TYPE_JUQINGFUBEN = 7;
/*     */   public static final int TYPE_JINGJICHANG = 8;
/*     */   public static final int TYPE_HUANHUNMISHU = 9;
/*     */   public static final int TYPE_MENPAITIAOZHAN = 10;
/*     */   public static final int TYPE_SHOUXIZHENGBA = 11;
/*     */   public static final int TYPE_HUANYUEDONGFU = 12;
/*     */   public static final int TYPE_JUEZHANJIUXIAO = 13;
/*     */   public static final int TYPE_SHIJIEBOSS = 14;
/*     */   public static final int TYPE_BANGZHAN = 15;
/*     */   public static final int TYPE_TIANXIAHUIWU = 16;
/*     */   public static final int TYPE_QING = 17;
/*     */   public static final int TYPE_FACTION_TASK = 18;
/*     */   public static final int TYPE_SUMMER_SINGLE = 19;
/*     */   public static final int TYPE_SUMMER_MULTI = 20;
/*     */   public static final int TYPE_RECHARGE = 21;
/*     */   public static final int TYPE_LEVEL_GROWTH_FUND = 22;
/*     */   public static final int TYPE_HALF_MONTH_CARD = 23;
/*     */   public static final int TYPE_MARKET = 24;
/*     */   public static final int TYPE_APOLLO = 25;
/*     */   public static final int TYPE_REDGIFT = 26;
/*     */   public static final int TYPE_BAITAN = 27;
/*     */   public static final int TYPE_GANG_SKILL = 28;
/*     */   public static final int TYPE_DOUBLE_POINT = 29;
/*     */   public static final int TYPE_GUIDE = 30;
/*     */   public static final int TYPE_MALL = 31;
/*     */   public static final int TYPE_ZHU_XIAN_QI_YUAN = 32;
/*     */   public static final int TYPE_KEJU = 33;
/*     */   public static final int TYPE_SIGN = 34;
/*     */   public static final int TYPE_LEVEL_AWARD = 35;
/*     */   public static final int TYPE_LOGIN_AWARD = 36;
/*     */   public static final int TYPE_ONLINE_AWARD = 37;
/*     */   public static final int TYPE_WATCH_MOON = 38;
/*     */   public static final int TYPE_WING = 39;
/*     */   public static final int TYPE_WING_ADD_EXP = 40;
/*     */   public static final int TYPE_WING_PHASE_UP = 41;
/*     */   public static final int TYPE_WING_PROPERTY_RESET = 42;
/*     */   public static final int TYPE_WING_SKILL_RESET = 43;
/*     */   public static final int TYPE_WING_DYE = 44;
/*     */   public static final int TYPE_WING_RESET = 45;
/*     */   public static final int TYPE_WING_OPEN_NEW = 46;
/*     */   public static final int TYPE_WING_ENABLE = 47;
/*     */   public static final int TYPE_WING_CANCEL = 48;
/*     */   public static final int TYPE_WING_CHANGE_VIEW = 49;
/*     */   public static final int TYPE_ZHENFA = 50;
/*     */   public static final int TYPE_WORLD_QUESTION = 51;
/*     */   public static final int TYPE_TMP_ACTIVITY = 52;
/*     */   public static final int TYPE_SHI_TU = 53;
/*     */   public static final int TYPE_COUPLE_DAILY = 54;
/*     */   public static final int TYPE_N_TIMES_AWARD = 55;
/*     */   public static final int TYPE_BAITAN_FIX_RECOMMEND_PRICE = 56;
/*     */   public static final int TYPE_EXCHANGE_USE_JIFEN = 57;
/*     */   public static final int TYPE_QMHW = 58;
/*     */   public static final int TYPE_GANG_ROBBER = 59;
/*     */   public static final int TYPE_SHENG_XIAO = 60;
/*     */   public static final int TYPE_LUAN_SHI_YAO_MO = 61;
/*     */   public static final int TYPE_ITEM_ABANDON = 62;
/*     */   public static final int TYPE_ITEM_EXCHANGE_GOLD_SILVER = 63;
/*     */   public static final int TYPE_ITEM_EXCHANGE_INGOT = 64;
/*     */   public static final int TYPE_ITEM_RECYCLE = 65;
/*     */   public static final int TYPE_EQUIP_MAKE = 66;
/*     */   public static final int TYPE_EQUIP_QILIN = 67;
/*     */   public static final int TYPE_EQUIP_XIHUN = 68;
/*     */   public static final int TYPE_EQUIP_ZHUAGHUN = 69;
/*     */   public static final int TYPE_EQUIP_CHUANGLIN = 70;
/*     */   public static final int TYPE_ITEM_EXCHANGE = 71;
/*     */   public static final int TYPE_BAG_EXTEND = 72;
/*     */   public static final int TYPE_EQUIP_FIX = 73;
/*     */   public static final int TYPE_GIVE_FLOWER = 74;
/*     */   public static final int TYPE_GIVE_ITEM = 75;
/*     */   public static final int TYPE_ITEM_COMPOUND = 76;
/*     */   public static final int TYPE_EQUIP_LOCK_HUN = 77;
/*     */   public static final int TYPE_MOVE_ITEM_INTO_STORAGE = 78;
/*     */   public static final int TYPE_MOVE_ITEM_INTO_BAG = 79;
/*     */   public static final int TYPE_OPEN_NEW_STORAGE = 80;
/*     */   public static final int TYPE_PUT_ON_AIRCRAFT = 81;
/*     */   public static final int TYPE_PUT_ON_FABAO = 82;
/*     */   public static final int TYPE_EQUIP_ON = 83;
/*     */   public static final int TYPE_USE_BAOTU = 84;
/*     */   public static final int TYPE_USE_DOUBLE_ITEM = 85;
/*     */   public static final int TYPE_USE_FABAO_RESET_ITEM = 86;
/*     */   public static final int TYPE_USE_FUMO_ITEM = 87;
/*     */   public static final int TYPE_USE_GANGFILE_ITEM = 88;
/*     */   public static final int TYPE_USE_GIFT_BAG_ITEM = 89;
/*     */   public static final int TYPE_USE_LOTTERY_ITEM = 90;
/*     */   public static final int TYPE_USE_MONEY_BAG_ITEM = 91;
/*     */   public static final int TYPE_USE_RIDDER_ITEM = 92;
/*     */   public static final int TYPE_USE_RIDDER_DYE_ITEM = 93;
/*     */   public static final int TYPE_USE_SELECT_BAG_ITEM = 94;
/*     */   public static final int TYPE_USE_ROLE_EXP_ITEM = 95;
/*     */   public static final int TYPE_YAO_SHOU_TU_XI = 96;
/*     */   public static final int TYPE_FABAO = 97;
/*     */   public static final int TYPE_ROLE_DYE = 98;
/*     */   public static final int TYPE_GANG_RACE = 99;
/*     */   public static final int TYPE_SWORN = 100;
/*     */   public static final int TYPE_SHANGHUI = 101;
/*     */   public static final int TYPE_PET = 102;
/*     */   public static final int TYPE_SKILL = 103;
/*     */   public static final int TYPE_XIULIAN = 104;
/*     */   public static final int TYPE_LIFE_SKILL = 105;
/*     */   public static final int TYPE_NEW_CLIENT = 106;
/*     */   public static final int TYPE_MARKET_SEARCH = 107;
/*     */   public static final int TYPE_BUFF = 108;
/*     */   public static final int TYPE_ONLINE_GIVE_AWARD = 109;
/*     */   public static final int TYPE_FASHION_DRESS = 110;
/*     */   public static final int TYPE_QING_FU_SAVE_AMT = 111;
/*     */   public static final int TYPE_QING_FU_TIME_LIMITED_SAVE_AMT = 112;
/*     */   public static final int TYPE_QING_FU_TIME_LIMITED_ACCUM_TOTAL_COST = 113;
/*     */   public static final int TYPE_QING_FU_RECHARGE_TIMES = 114;
/*     */   public static final int TYPE_TIME_LIMIT_GIFT = 115;
/*     */   public static final int TYPE_TIME_LIMIT_GIFT_FREE = 116;
/*     */   public static final int TYPE_CARNIVAL_ACTIVITY = 117;
/*     */   public static final int TYPE_MARKET_AUCTION = 118;
/*     */   public static final int TYPE_MARKET_CUSTOMIZED = 119;
/*     */   public static final int TYPE_PERSONAL = 120;
/*     */   public static final int TYPE_COMMON_EXCHANGE = 121;
/*     */   public static final int TYPE_TENCENT_PRIVILEGE = 122;
/*     */   public static final int TYPE_YI_XIAN_MI_BAO = 123;
/*     */   public static final int TYPE_BACK_GAME = 124;
/*     */   public static final int TYPE_ESPORTS = 125;
/*     */   public static final int TYPE_LBS = 126;
/*     */   public static final int TYPE_IOS_REPLAYKIT = 127;
/*     */   public static final int TYPE_MARRIAGE_PARADE = 128;
/*     */   public static final int TYPE_MARRIAGE_PARADE_ROB = 129;
/*     */   public static final int TYPE_MOSHOU_FRAGMENT_EXCHANGE = 130;
/*     */   public static final int TYPE_AWARDPOOL_PRECIOUS_DROP = 131;
/*     */   public static final int TYPE_QING_FU_RMB_GIFT_BAG = 132;
/*     */   public static final int TYPE_REPORT_ROLE = 133;
/*     */   public static final int TYPE_DAY_TARGET = 134;
/*     */   public static final int TYPE_CHAT_ROOM = 135;
/*     */   public static final int TYPE_HEART = 136;
/*     */   public static final int TYPE_SHI_TU_PAY_RESPECT = 137;
/*     */   public static final int TYPE_AWARD_GEM = 138;
/*     */   public static final int TYPE_OPEN_WELFARE = 139;
/*     */   public static final int TYPE_SNS = 140;
/*     */   public static final int TYPE_MULTI_XML = 141;
/*     */   public static final int TYPE_PET_STAGE_LEVELUP = 142;
/*     */   public static final int TYPE_PET_REPLACE_SKILL = 143;
/*     */   public static final int TYPE_OCC_MFV_RANK = 144;
/*     */   public static final int TYPE_ROLE_LEVEL_CHART_AWARD = 145;
/*     */   public static final int TYPE_HUN_HELP = 146;
/*     */   public static final int TYPE_ROLE_MULTI_FIGHT_VALUE = 147;
/*     */   public static final int TYPE_PET_YAOLI_VALUE = 148;
/*     */   public static final int TYPE_ROLE_FIGHT_VALUE_AWARD = 149;
/*     */   public static final int TYPE_QING_YUAN = 150;
/*     */   public static final int TYPE_ITEM_RESOURCE_CHECK = 151;
/*     */   public static final int TYPE_ROLE_EXP_AWARD_BARK = 152;
/*     */   public static final int TYPE_LOGIN_ACTIVITY = 153;
/*     */   public static final int TYPE_LOGIN_SUM_ACTIVITY = 154;
/*     */   public static final int TYPE_INVITE_FRIENDS = 155;
/*     */   public static final int TYPE_BIND_YUANBAO_WHITELIST_RESOURCE_CHECK = 156;
/*     */   public static final int TYPE_PET_TRANSFORM_PLACE_INFIGHT = 157;
/*     */   public static final int TYPE_AUTO_REPAIR_PAY_EXCEPTION_DATA = 158;
/*     */   public static final int TYPE_GROUP = 159;
/*     */   public static final int TYPE_MOUNTS = 160;
/*     */   public static final int TYPE_HOME = 161;
/*     */   public static final int TYPE_CAT = 162;
/*     */   public static final int TYPE_STORYWALL = 163;
/*     */   public static final int TYPE_MASSWEDDING = 164;
/*     */   public static final int TYPE_BANQUEST = 165;
/*     */   public static final int TYPE_CHATGIFT_ROLE = 166;
/*     */   public static final int TYPE_CHATGIFT_GANG = 167;
/*     */   public static final int TYPE_WORLD_GOAL = 168;
/*     */   public static final int TYPE_NORMAL_INSTANCE = 169;
/*     */   public static final int TYPE_CHATGIFT_GROUP = 170;
/*     */   public static final int TYPE_DOUBLE_POINT_SWITCH = 171;
/*     */   public static final int TYPE_COUNT_DOWN = 172;
/*     */   public static final int TYPE_USE_PLAY_EXPRESSION_ITEM = 173;
/*     */   public static final int TYPE_LUCKY_BAG = 174;
/*     */   public static final int TYPE_HOME_RANK_AWARD = 175;
/*     */   public static final int TYPE_TIME_DROP_AWARD = 176;
/*     */   public static final int TYPE_LOGIN_SIGN_ACTIVITY = 177;
/*     */   public static final int TYPE_LOG_ROLE_RANK_FV = 178;
/*     */   public static final int TYPE_LOG_ROLE_RANK_MFV = 179;
/*     */   public static final int TYPE_OCP_EQUIP_ON = 180;
/*     */   public static final int TYPE_OCP_EQUIP_OFF = 181;
/*     */   public static final int TYPE_OCP_EQUIP_TRANSFER_LIN = 182;
/*     */   public static final int TYPE_GANG_AUTO_DISSOLVE = 183;
/*     */   public static final int TYPE_MULTI_OCCUPATION = 184;
/*     */   public static final int TYPE_GIVE_FLOWER_RANK_AWARD = 185;
/*     */   public static final int TYPE_RECEIVE_FLOWER_RANK_AWARD = 186;
/*     */   public static final int TYPE_TEAM_VOIP_ROOM = 187;
/*     */   public static final int TYPE_LADDER = 188;
/*     */   public static final int TYPE_RECALL_FRIEND = 189;
/*     */   public static final int TYPE_LONGJING_TRANSFER = 190;
/*     */   public static final int TYPE_EQUIP_MAKE_SKIILL = 191;
/*     */   public static final int TYPE_PUSH_AWARD = 192;
/*     */   public static final int TYPE_ZHENYAO_FIFTY_AWARD = 193;
/*     */   public static final int TYPE_COMMENT_GUIDE = 194;
/*     */   public static final int TYPE_ADDICTION = 195;
/*     */   public static final int TYPE_MASS_EXP = 196;
/*     */   public static final int TYPE_LUCKY_STAR = 197;
/*     */   public static final int TYPE_PET_CHANGE_MODEL = 198;
/*     */   public static final int TYPE_GAIN_LOST_EXP = 199;
/*     */   public static final int TYPE_HULA = 200;
/*     */   public static final int TYPE_PAY_NEW_YEAR = 201;
/*     */   public static final int TYPE_GET_DAILY_GIFT = 202;
/*     */   public static final int TYPE_VISIBLE_MONSTER = 203;
/*     */   public static final int TYPE_MUSIC_GAME = 204;
/*     */   public static final int TYPE_FETUS_EDUCATION_MUSIC = 205;
/*     */   public static final int TYPE_MAGIC_MARK = 206;
/*     */   public static final int TYPE_INTELLIGENT_MATCH_ZHENYAO_GUAJI = 207;
/*     */   public static final int TYPE_GOLD_WATCH_DOG = 208;
/*     */   public static final int TYPE_CHILDREN = 209;
/*     */   public static final int TYPE_BUBBLE_GAME = 210;
/*     */   public static final int TYPE_PREPARE_PREGNANCY = 211;
/*     */   public static final int TYPE_GIVE_BIRTH = 212;
/*     */   public static final int TYPE_SHANG_GONG = 213;
/*     */   public static final int TYPE_QIU_QIAN = 214;
/*     */   public static final int TYPE_GUAN_YIN_SHANG_GONG = 215;
/*     */   public static final int TYPE_GUAN_YIN_QIU_QIAN = 216;
/*     */   public static final int TYPE_COMMON_GIFT = 217;
/*     */   public static final int TYPE_CHILD_FASHION = 218;
/*     */   public static final int TYPE_COMPETITION_MERCENARY = 219;
/*     */   public static final int TYPE_WORLD_GOAL_SNOWMAN = 220;
/*     */   public static final int TYPE_WORLD_GOAL_HUA_KAI_QING_NONG = 221;
/*     */   public static final int TYPE_CHILDHOOD = 222;
/*     */   public static final int TYPE_ADULT = 223;
/*     */   public static final int TYPE_AUTO_LUAN_SHI_YAO_MO = 224;
/*     */   public static final int TYPE_ADVANCED_LEVEL_GROWTH_FUND = 225;
/*     */   public static final int TYPE_MONTH_CARD_PHASE_2 = 226;
/*     */   public static final int TYPE_CONSTELLATION = 227;
/*     */   public static final int TYPE_AUTO_INVITE_WATCH_MOON = 228;
/*     */   public static final int TYPE_MAX_LEVEL_STORAGE_EXP = 229;
/*     */   public static final int TYPE_MEMORY_COMPETITION = 230;
/*     */   public static final int TYPE_ROMANTIC_DANCE = 231;
/*     */   public static final int TYPE_MONEY_TREE = 232;
/*     */   public static final int TYPE_PLANT_TREE = 233;
/*     */   public static final int TYPE_QILIN_ACCUMULATION_MODE = 234;
/*     */   public static final int TYPE_QILIN_DEFAULT_MODE = 235;
/*     */   public static final int TYPE_NEW_FUNCTION_VOTE = 236;
/*     */   public static final int TYPE_NEW_LADDER_SCORE_SELF = 237;
/*     */   public static final int TYPE_EQUIP_SKILL_REFRESH = 238;
/*     */   public static final int TYPE_FIGHT_PROP = 239;
/*     */   public static final int TYPE_GRC_BOX = 240;
/*     */   public static final int TYPE_WECHAT_INVITE_H5_ACTIVITY = 241;
/*     */   public static final int TYPE_FIGHTAI_TIANYIN = 242;
/*     */   public static final int TYPE_MENG_SHI = 243;
/*     */   public static final int TYPE_CHUN_FEN = 244;
/*     */   public static final int TYPE_CHUN_GUANG = 245;
/*     */   public static final int TYPE_AB_TEST = 246;
/*     */   public static final int TYPE_COMMON_EXCHANGE_BEI_LUO_SHI_MEN = 247;
/*     */   public static final int TYPE_COMMON_EXCHANGE_CHUN_SHEN_HUA_JUAN = 248;
/*     */   public static final int TYPE_COMMON_EXCHANGE_CHENG_ZHUANG_60 = 249;
/*     */   public static final int TYPE_COMMON_EXCHANGE_CHENG_ZHUANG_70 = 250;
/*     */   public static final int TYPE_COMMON_EXCHANGE_CHENG_ZHUANG_80 = 251;
/*     */   public static final int TYPE_COMMON_EXCHANGE_CHENG_ZHUANG_90 = 252;
/*     */   public static final int TYPE_COMMON_EXCHANGE_SHEN_MI_DAO_JU = 253;
/*     */   public static final int TYPE_COMMON_EXCHANGE_XIAO_DOU_MEI = 254;
/*     */   public static final int TYPE_COMMON_EXCHANGE_CHUN_NUAN_HUA_KAI = 255;
/*     */   public static final int TYPE_COMMON_EXCHANGE_ZHONG_GUO_JIE = 256;
/*     */   public static final int TYPE_COMMON_EXCHANGE_NIAN_SHOU_ZHI_YA = 257;
/*     */   public static final int TYPE_COMMON_EXCHANGE_JIN_FENG_MING_CHUN = 258;
/*     */   public static final int TYPE_COMMON_EXCHANGE_XUN_LU_SUI_PIAN = 259;
/*     */   public static final int TYPE_COMMON_EXCHANGE_SHEN_MI_LI_WU = 260;
/*     */   public static final int TYPE_COMMON_EXCHANGE_MI_BAO_ZHI_SHI = 261;
/*     */   public static final int TYPE_COMMON_EXCHANGE_MO_SHOU_LING_SHI = 262;
/*     */   public static final int TYPE_COMMON_EXCHANGE_DONG_JI_LIAN_GE = 263;
/*     */   public static final int TYPE_COMMON_EXCHANGE_XI_LE_YUAN_DAN = 264;
/*     */   public static final int TYPE_SUPPORT_HTTPS = 265;
/*     */   public static final int TYPE_BACK_GAME_BUY_GIFT = 266;
/*     */   public static final int TYPE_FREE_FLOW = 267;
/*     */   public static final int TYPE_TRUMPET = 268;
/*     */   public static final int TYPE_FOOLS_DAY = 269;
/*     */   public static final int TYPE_MEN_PAI_STAR = 270;
/*     */   public static final int TYPE_SIGN_PRECIOUS = 271;
/*     */   public static final int TYPE_WORSHIP_FACTION_MASTER = 272;
/*     */   public static final int TYPE_MARKET_AUCTION_GOODS_CUT_GOLD = 273;
/*     */   public static final int TYPE_FEI_SHENG_99 = 274;
/*     */   public static final int TYPE_HUA_SHENG_MINIMUM_GUARANEE = 275;
/*     */   public static final int TYPE_MOURN = 276;
/*     */   public static final int TYPE_EQUIP_DISASSEMBLE = 277;
/*     */   public static final int TYPE_NEW_OCCUPATION__CANG_YU = 278;
/*     */   public static final int TYPE_EQUIP_MAKE_N_LEVEL = 279;
/*     */   public static final int TYPE_PET_99_LEVEL = 280;
/*     */   public static final int TYPE_QMHW_CHANGE_1 = 281;
/*     */   public static final int TYPE_EXP_RELEASE_99 = 282;
/*     */   public static final int TYPE_FASHION_REPLACE = 283;
/*     */   public static final int TYPE_FABAO_AUTO_RANK = 284;
/*     */   public static final int TYPE_GUAJI_1 = 285;
/*     */   public static final int TYPE_GUAJI_2 = 286;
/*     */   public static final int TYPE_GUAJI_3 = 287;
/*     */   public static final int TYPE_GUAJI_4 = 288;
/*     */   public static final int TYPE_GUAJI_5 = 289;
/*     */   public static final int TYPE_GUAJI_6 = 290;
/*     */   public static final int TYPE_GUAJI_7 = 291;
/*     */   public static final int TYPE_GUAJI_8 = 292;
/*     */   public static final int TYPE_GUAJI_9 = 293;
/*     */   public static final int TYPE_GUAJI_10 = 294;
/*     */   public static final int TYPE_GUAJI_11 = 295;
/*     */   public static final int TYPE_GUAJI_12 = 296;
/*     */   public static final int TYPE_GUAJI_13 = 297;
/*     */   public static final int TYPE_GUAJI_14 = 298;
/*     */   public static final int TYPE_GUAJI_15 = 299;
/*     */   public static final int TYPE_GUAJI_16 = 300;
/*     */   public static final int TYPE_GUAJI_17 = 301;
/*     */   public static final int TYPE_GUAJI_18 = 302;
/*     */   public static final int TYPE_GUAJI_19 = 303;
/*     */   public static final int TYPE_GUAJI_20 = 304;
/*     */   public static final int TYPE_EXP_STORAGE_109 = 305;
/*     */   public static final int TYPE_EXP_RELEASE_109 = 306;
/*     */   public static final int TYPE_COMMON_EXCHANGE_CHENG_ZHUANG_100 = 307;
/*     */   public static final int TYPE_BOUNTY_BAO_DI = 308;
/*     */   public static final int TYPE_GENIUS = 309;
/*     */   public static final int TYPE_COMMON_EXCHANGE_JING_KE_CI_WANG = 310;
/*     */   public static final int TYPE_WING_SET_TARGET_SKILL = 311;
/*     */   public static final int TYPE_EXP_BOTTLE = 312;
/*     */   public static final int TYPE_DOUBLE_GENIUS_SERIES = 313;
/*     */   public static final int TYPE_AVATAR = 314;
/*     */   public static final int TYPE_DOUBLE_ITEM = 315;
/*     */   public static final int TYPE_MERGE_COMPENSATION = 316;
/*     */   public static final int TYPE_MARKET_RECYCLE = 317;
/*     */   public static final int TYPE_MARKET_SUPPLY = 318;
/*     */   public static final int TYPE_PLANT_TREE_HALF_YEAR_CELEBRATION = 319;
/*     */   public static final int TYPE_SINGLE_TASK__GU_YU = 320;
/*     */   public static final int TYPE_FACTION_CHAT_CONTENT_BUFFER = 321;
/*     */   public static final int TYPE_MYSTERYS_SHOP = 322;
/*     */   public static final int TYPE_LABOR_QUESTION = 323;
/*     */   public static final int TYPE_ADD_FRIEND_BAN = 324;
/*     */   public static final int TYPE_AXE_HE_SHEN = 325;
/*     */   public static final int TYPE_USE_AXE_ITEM = 326;
/*     */   public static final int TYPE_LABOR_TASK = 327;
/*     */   public static final int TYPE_THEME_FASHION_DRESS = 328;
/*     */   public static final int TYPE_BLESS = 329;
/*     */   public static final int TYPE_LADDER_SCORE_ALL_SERVER = 330;
/*     */   public static final int TYPE_BOUNTY_STAR_PROBABILITY = 331;
/*     */   public static final int TYPE_EXPLOIT = 332;
/*     */   public static final int TYPE_LADDER_SINGLE_MATCH = 333;
/*     */   public static final int TYPE_FACTION_PVE = 334;
/*     */   public static final int TYPE_COMMON_EXCHANGE_LUN_HUI_TIAN_SHU = 335;
/*     */   public static final int TYPE_MYSTERY_VISITOR = 336;
/*     */   public static final int TYPE_COURT_YARD_LEVEL_UP_AND_DISPLAY = 337;
/*     */   public static final int TYPE_ZOO = 338;
/*     */   public static final int TYPE_MOTHERSDAY = 339;
/*     */   public static final int TYPE_COMMON_EXCHANGE_FEI_TIAN_XIAO_XIANG = 340;
/*     */   public static final int TYPE_NPC_REWARD = 341;
/*     */   public static final int TYPE_GRC_BOX_RMB_COND = 342;
/*     */   public static final int TYPE_GRC_BOX_QING_YUN_ZHI_COND = 343;
/*     */   public static final int TYPE_GREETING_CARD = 344;
/*     */   public static final int TYPE_CROSS_BATTLE_SEASON_1 = 345;
/*     */   public static final int TYPE_DRAW_AND_GUESS = 346;
/*     */   public static final int TYPE_COMMON_EXCHANGE_ZHEN_XI_HAO_LI = 347;
/*     */   public static final int TYPE_CORPS = 348;
/*     */   public static final int TYPE_LONNG_BOAT_RACE = 349;
/*     */   public static final int TYPE_QING_YUN_YIN_YUE = 350;
/*     */   public static final int TYPE_CROSS_BATTLE_REGISTER_STAGE_SEASON_1 = 351;
/*     */   public static final int TYPE_CROSS_BATTLE_VOTE_STAGE_SEASON_1 = 352;
/*     */   public static final int TYPE_CROSS_BATTLE_ROUND_ROBIN_STAGE_SEASON_1 = 353;
/*     */   public static final int TYPE_CHILDREN_RATING_RANK = 354;
/*     */   public static final int TYPE_WO_AI_QI = 355;
/*     */   public static final int TYPE_CROSS_BATTLE_POINT = 356;
/*     */   public static final int TYPE_QING_YUN_YIN_YUE_2 = 357;
/*     */   public static final int TYPE_FABAOLINGQI = 358;
/*     */   public static final int TYPE_LUN_HUI_XU_KONG = 359;
/*     */   public static final int TYPE_LUN_1_5 = 360;
/*     */   public static final int TYPE_LUN_6_10 = 361;
/*     */   public static final int TYPE_LUN_11_15 = 362;
/*     */   public static final int TYPE_LUN_16_18 = 363;
/*     */   public static final int TYPE_CROSS_BATTLE_ROUND_ROBIN_STAGE_BET_SEASON_1 = 364;
/*     */   public static final int TYPE_FATHERSDAY = 365;
/*     */   public static final int TYPE_WORLD_QUESTION_RANDOM_AWARD = 366;
/*     */   public static final int TYPE_COMMON_AWARD = 367;
/*     */   public static final int TYPE_QING_HELP_AWARD = 368;
/*     */   public static final int TYPE_XUKONGBAOZANG = 369;
/*     */   public static final int TYPE_CROSS_BATTLE_SELECTION_STAGE_BET_SEASON_1 = 370;
/*     */   public static final int TYPE_CROSS_BATTLE_DRAW_LOTS = 371;
/*     */   public static final int TYPE_WORLD_QUESTION_NB_AWARD_MAX = 372;
/*     */   public static final int TYPE_CROSS_BATTLE_SELECTION = 373;
/*     */   public static final int TYPE_CROSS_BATTLE_FINAL_STAGE_BET_SEASON_1 = 374;
/*     */   public static final int TYPE_CROSS_BATTLE_ROUND_ROBIN_STAGE_BET_SEASON_TEST = 375;
/*     */   public static final int TYPE_CROSS_BATTLE_SELECTION_STAGE_BET_SEASON_TEST = 376;
/*     */   public static final int TYPE_CROSS_BATTLE_FINAL_STAGE_BET_SEASON_TEST = 377;
/*     */   public static final int TYPE_COMMON_EXCHANGE_LING_XIAO_FEI_ZHOU = 378;
/*     */   public static final int TYPE_CROSS_BATTLE_FINAl = 379;
/*     */   public static final int TYPE_AWARDPOOL_WEIGHT_CORRECTION = 380;
/*     */   public static final int TYPE_COMMON_EXCHANGE_LUN_HUI_JING_PO = 381;
/*     */   public static final int TYPE_SUPER_EQUIPMENT = 382;
/*     */   public static final int TYPE_DAILY_LIMIT_MALL = 383;
/*     */   public static final int TYPE_RMB_GIFT_BAG_18 = 384;
/*     */   public static final int TYPE_SUPER_EQUIPMENT_JEWEL = 385;
/*     */   public static final int TYPE_YUJIANJIUTIAN = 386;
/*     */   public static final int TYPE_SINGLE_TASK__ZAI_XIAN_LING_JIANG = 387;
/*     */   public static final int TYPE_JUQINGFUBEN_NORMAL = 388;
/*     */   public static final int TYPE_JUQINGFUBEN_ELITE = 389;
/*     */   public static final int TYPE_JUQINGFUBEN_HERO = 390;
/*     */   public static final int TYPE_JUQINGFUBEN_NIGHTMARE = 391;
/*     */   public static final int TYPE_JUQINGFUBEN_ACTIVITY = 392;
/*     */   public static final int TYPE_PROTECT_PET_EXPAND_SIZE = 393;
/*     */   public static final int TYPE_CROSS_BATTLE_WITNESS_BATTLE = 394;
/*     */   public static final int TYPE_CROSS_BATTLE_CALENDAR = 395;
/*     */   public static final int TYPE_CHESS_ACTIVITY = 396;
/*     */   public static final int TYPE_SUPER_EQUIPMENT_WUSHI = 397;
/*     */   public static final int TYPE_CROSS_FIELD = 398;
/*     */   public static final int TYPE_CROSS_FIELD_TIAN_KONG_ZHI_CHENG = 399;
/*     */   public static final int TYPE_CROSS_FIELD_HUANG_GU_YI_JI = 400;
/*     */   public static final int TYPE_SUPER_EQUIPMENT_JEWEL_AUTO_COMPOSE = 401;
/*     */   public static final int TYPE_SUPER_EQUIPMENT_JEWEL_BAG = 402;
/*     */   public static final int TYPE_SINGLE_TASK__ZHENG_JIU_TUAN_ZI = 403;
/*     */   public static final int TYPE_ITEM_COMPOUND_ALL = 404;
/*     */   public static final int TYPE_SQJNH_GUIDELINE = 405;
/*     */   public static final int TYPE_COMMON_EXCHANGE_SUMMER_VACATION = 406;
/*     */   public static final int TYPE_COMMON_EXCHANGE_ALPACA = 407;
/*     */   public static final int TYPE_CROSS_COMPETE = 408;
/*     */   public static final int TYPE_MULTI_ROLE_MOUNTS = 409;
/*     */   public static final int TYPE_LUN_HUI_XU_KONG__CHECK_RECORD = 410;
/*     */   public static final int TYPE_PK = 411;
/*     */   public static final int TYPE_WANTED = 412;
/*     */   public static final int TYPE_PRISON = 413;
/*     */   public static final int TYPE_SHITU_TASK = 414;
/*     */   public static final int TYPE_SHITU_ACTIVE_VALUE = 415;
/*     */   public static final int TYPE_SHITU_RECOMMEND = 416;
/*     */   public static final int TYPE_SHITU_TASK_GUIDE = 417;
/*     */   public static final int TYPE_SHITU_BAISHI_GUIDE = 418;
/*     */   public static final int TYPE_BACK_GAME_ACTIVITY = 419;
/*     */   public static final int TYPE_BACK_GAME_ACTIVITY_SIGN = 420;
/*     */   public static final int TYPE_BACK_GAME_ACTIVITY_POINT = 421;
/*     */   public static final int TYPE_BACK_GAME_ACTIVITY_EXP = 422;
/*     */   public static final int TYPE_BACK_GAME_ACTIVITY_AWARD = 423;
/*     */   public static final int TYPE_BACK_GAME_ACTIVITY_BUY_GIFT = 424;
/*     */   public static final int TYPE_NEW_OCCUPATION_LING_YIN_DIAN = 425;
/*     */   public static final int TYPE_CROSS_BATTLE_ROUND_ROBIN_STAGE_BET_SEASON_TEST_2 = 426;
/*     */   public static final int TYPE_CROSS_BATTLE_SELECTION_STAGE_BET_SEASON_TEST_2 = 427;
/*     */   public static final int TYPE_CROSS_BATTLE_FINAL_STAGE_BET_SEASON_TEST_2 = 428;
/*     */   public static final int TYPE_FLOOR_FIRST_BLOOD_AWARD = 429;
/*     */   public static final int TYPE_FLOOR_HELP_AWARD = 430;
/*     */   public static final int TYPE_QUESTION_VOICE_FEI_YU_QING = 431;
/*     */   public static final int TYPE_CROSS_BATTLE_HISTORY = 432;
/*     */   public static final int TYPE_PARTNER_YUANSHEN = 433;
/*     */   public static final int TYPE_RECALL_FRIEND_OPTIMIZE = 434;
/*     */   public static final int TYPE_LE_GOU_SHANG_CHENG = 435;
/*     */   public static final int TYPE_DOU_DOU_SONG_LI = 436;
/*     */   public static final int TYPE_ADD_CHIVALRY_ON_PVE_END = 437;
/*     */   public static final int TYPE_BEGINNER_LOGIN_SIGN = 438;
/*     */   public static final int TYPE_COMMON_EXCHANGE_TIE_JIA_XIAO_BAO = 439;
/*     */   public static final int TYPE_COMMON_FEN_XIANG_YOU_LI = 440;
/*     */   public static final int TYPE_SUPER_EQUIPMENT_JEWEL_TRANSFER = 441;
/*     */   public static final int TYPE_PET_SOUL = 442;
/*     */   public static final int TYPE_GOLD_STATUE = 443;
/*     */   public static final int TYPE_FACTION_CROSS_SERVER_CHAT = 444;
/*     */   public static final int TYPE_ACHIEVEMENT = 445;
/*     */   public static final int TYPE_SINGLE_INSTANCE_SAO_DANG = 446;
/*     */   public static final int TYPE_WING_SKILL_RESET_GUARANTEE = 447;
/*     */   public static final int TYPE_UPLOAD_PICTURE = 448;
/*     */   public static final int TYPE_MESSAGE_BOARD = 449;
/*     */   public static final int TYPE_RELEASE_DYNAMIC = 450;
/*     */   public static final int TYPE_FRIENDS_CIRCLE = 451;
/*     */   public static final int TYPE_GIVE_PRESENT = 452;
/*     */   public static final int TYPE_TREAD_CIRCLE = 453;
/*     */   public static final int TYPE_BUY_TREASURE_BOX = 454;
/*     */   public static final int TYPE_CHAINED_GIFT_BAG = 455;
/*     */   public static final int TYPE_AVATAR_FRAME = 456;
/*     */   public static final int TYPE_CHAT_BUBBLE = 457;
/*     */   public static final int TYPE_AT = 458;
/*     */   public static final int TYPE_CHINESE_VALENTINE = 459;
/*     */   public static final int TYPE_SURPRISE_ACTION_0 = 460;
/*     */   public static final int TYPE_SURPRISE_ACHIEVEMENT_0 = 461;
/*     */   public static final int TYPE_SURPRISE_ITEM_CON_0 = 462;
/*     */   public static final int TYPE_SURPRISE_USE_ITEM = 463;
/*     */   public static final int TYPE_TIME_LIMITED_THEME_FASHION_DRESS = 464;
/*     */   public static final int TYPE_ITEM_SPLIT = 465;
/*     */   public static final int TYPE_CHILD_FASHION_RENEWAL = 466;
/*     */   public static final int TYPE_MULTI_LINE_TASK__TEACHER = 467;
/*     */   public static final int TYPE_ACTIVITY_ACHIEVEMENT = 468;
/*     */   public static final int TYPE_FRIENDS_CIRCLE_CHART = 469;
/*     */   public static final int TYPE_FRIENDS_CIRCLE_ORNAMENT = 470;
/*     */   public static final int TYPE_FRIENDS_CIRCLE_CROSS_SERVER_TREAD = 471;
/*     */   public static final int TYPE_FRIENDS_CIRCLE_CROSS_SERVER_GIVE_GIFT = 472;
/*     */   public static final int TYPE_SINGLE_TASK__KAI_XUE_DAO_JI_SHI = 473;
/*     */   public static final int TYPE_SINGLE_TASK__KAI_XUE_KUANG_HUAN = 474;
/*     */   public static final int TYPE_COMMON_EXCHANGE_QI_XI = 475;
/*     */   public static final int TYPE_SINGLE_TASK__KAI_XUE_XIAO_LI_TANG = 476;
/*     */   public static final int TYPE_MENPAI_MFV_RANK_AWARD = 477;
/*     */   public static final int TYPE_CROSS_BATTLE_ROUND_ROBIN_STAGE_BET_SEASON_2 = 478;
/*     */   public static final int TYPE_CROSS_BATTLE_SELECTION_STAGE_BET_SEASON_2 = 479;
/*     */   public static final int TYPE_CROSS_BATTLE_FINAL_STAGE_BET_SEASON_2 = 480;
/*     */   public static final int TYPE_INTERACTION = 481;
/*     */   public static final int TYPE_XIAO_HUI_KUAI_PAO_ACTIVITY = 482;
/*     */   public static final int TYPE_FLOOR_SWEEP = 483;
/*     */   public static final int TYPE_COMMON_EXCHANGE_FENG_KUANG_XIAO_SHI_ZI = 484;
/*     */   public static final int TYPE_CROSS_BATTLE_BET_RANK = 485;
/*     */   public static final int TYPE_MINOR_CURFEW = 486;
/*     */   public static final int TYPE_MINOR_BAN_PLAY = 487;
/*     */   public static final int TYPE_USE_ALL_LOTTERY_ITEM = 488;
/*     */   public static final int TYPE_FRIENDS_CIRCLE_CROSS_SERVER_BLACK_LIST = 489;
/*     */   public static final int TYPE_SHARE__GUO_QING = 490;
/*     */   public static final int TYPE_GUO_QING_BIRTHDAY_PRAY = 491;
/*     */   public static final int TYPE_GUO_QING_BREAK_EGG = 492;
/*     */   public static final int TYPE_GUO_QING_WATCH_LANTERN = 493;
/*     */   public static final int TYPE_GUO_QING_MAKE_CAKES = 494;
/*     */   public static final int TYPE_REPORT_FEEDBACK = 495;
/*     */   public static final int TYPE_FORBID_SYSTEM_NOTICE = 496;
/*     */   public static final int TYPE_RECOMMEND_QQ_WECHAT_FRIEND = 497;
/*     */   public static final int TYPE_PET_HUA_SHENG_YUAN_BAO_MAKE_UP_VICE_PET = 498;
/*     */   public static final int TYPE_CROSS_SERVER_RECALL_FRIEND = 499;
/*     */   public static final int TYPE_SHANG_HUI_PRICE_FLOW_ITEM__MULTI_BUY = 500;
/*     */   public static final int TYPE_MULTI_TASK__QU_ZHU_DA_LU = 501;
/*     */   public static final int TYPE_AUTO_USE_ITEM_IN_BAG = 502;
/*     */   public static final int TYPE_FIGHT_FRIEND_OPTION_TIP = 503;
/*     */   public static final int TYPE_GROUP_SHOPPING = 504;
/*     */   public static final int TYPE_GROUP_SHOPPING_SMALL_GROUP = 505;
/*     */   public static final int TYPE_GROUP_SHOPPING_SMALL_SINGLE = 506;
/*     */   public static final int TYPE_GROUP_SHOPPING_BIG_GROUP = 507;
/*     */   public static final int TYPE_GROUP_SHOPPING_BIG_SINGLE = 508;
/*     */   public static final int TYPE_AIRCRAFT = 509;
/*     */   public static final int TYPE_CHANGE_MODEL_CARD = 510;
/*     */   public static final int TYPE_CLASS_RESTRICTION = 511;
/*     */   public static final int TYPE_CHAT_TEXT_FACE = 512;
/*     */   public static final int TYPE_GANG_TEAM = 513;
/*     */   public static final int TYPE_YUAN_BAO_2_BANG_GONG = 514;
/*     */   public static final int TYPE_RECALL_FRIEND_REBATE = 515;
/*     */   public static final int TYPE_ACTIVITY_POINT_EXCHANGE = 516;
/*     */   public static final int TYPE_CEO_RED_PACKET = 517;
/*     */   public static final int TYPE_FLOWER_PARADE = 518;
/*     */   public static final int TYPE_COMMON_EXCHANGE_BAI_BIAN_QING_LIANG_MAO = 519;
/*     */   public static final int TYPE_COMMON_EXCHANGE_GUO_QING = 520;
/*     */   public static final int TYPE_BACK_GAME_ACTIVITY_RECHARGE = 521;
/*     */   public static final int TYPE_INDIANA_JONES = 522;
/*     */   public static final int TYPE_BAITAN_ALL_ON_SHELF = 523;
/*     */   public static final int TYPE_CHILDREN_AUTO_BREED = 524;
/*     */   public static final int TYPE_FRIENDS_CIRCLE_REPAIR = 525;
/*     */   public static final int TYPE_MARKET_SHARE_GROUP_CHAT = 526;
/*     */   public static final int TYPE_LIFE_SKILL_ACTIVITY_SHENNONG = 527;
/*     */   public static final int TYPE_LIFE_SKILL_ACTIVITY_DUKANG = 528;
/*     */   public static final int TYPE_MONDAY_FREE = 529;
/*     */   public static final int TYPE_EQUIPMENT_BLESS = 530;
/*     */   public static final int TYPE_MAKE_UP = 531;
/*     */   public static final int TYPE_MULTI_TASK_QIU_RI_QU_MO = 532;
/*     */   public static final int TYPE_SINGLE_TASK_HUI_YI_WANG_XI = 533;
/*     */   public static final int TYPE_AUCTION = 534;
/*     */   public static final int TYPE_MAIN_UI_TOP_LEFT_BUTTON_GROUP_VISIBILITY = 535;
/*     */   public static final int TYPE_HALLOWEEN_VISIBLE_MONSTER_ACTIVITY = 536;
/*     */   public static final int TYPE_ALL_LOTTO = 537;
/*     */   public static final int TYPE_FIRE_WORK = 538;
/*     */   public static final int TYPE_SHAPE_SHIFT_ITEM = 539;
/*     */   public static final int TYPE_SHOW_SURPRISE_CLUE = 540;
/*     */   public static final int TYPE_CHAT_FRIEND_CHANNEL = 541;
/*     */   public static final int TYPE_CEO_RED_PACKET_2 = 542;
/*     */   public static final int TYPE_RECALL_FRIEND_BIND = 543;
/*     */   public static final int TYPE_ACTIVITY_COMPENSATE = 544;
/*     */   public static final int TYPE_XIAO_HUI_KUAI_PAO_OUTER_TURN_TO_POINT_ACTIVITY = 545;
/*     */   public static final int TYPE_NEW_OCCUPATION_YI_NENG_ZHE = 546;
/*     */   public static final int TYPE_FRIEND_REMARK_NAME = 547;
/*     */   public static final int TYPE_BANDSTAND = 548;
/*     */   public static final int TYPE_ROLE_MODLE_DYE_OPTIMIZATION = 549;
/*     */   public static final int TYPE_COMMON_EXCHANGE_ZHOU_NIAN_QING = 550;
/*     */   public static final int TYPE_COOK_CAKE = 551;
/*     */   public static final int TYPE_CROSS_BATTLE_AWARD_PREVIEW = 552;
/*     */   public static final int TYPE_COMMON_EXCHANGE_BA_GUA_FENG_LUN = 553;
/*     */   public static final int TYPE_COMMON_EXCHANGE_GUO_SE_TIAN_XIANG = 554;
/*     */   public static final int TYPE_FORBID_ADD_STORAGE_EXP = 555;
/*     */   public static final int TYPE_AUTO_TREAD = 556;
/*     */   public static final int TYPE_COMMON_EXCHANGE_SHEN_MI_DUI_HUAN = 557;
/*     */   public static final int TYPE_SURPRISE_RED_NOTICE = 558;
/*     */   public static final int TYPE_PET_FIGHT = 559;
/*     */   public static final int TYPE_LIFE_SKILL_RESET = 560;
/*     */   public static final int TYPE_TAKE_PHOTO = 561;
/*     */   public static final int TYPE_PET_ARENA = 562;
/*     */   public static final int TYPE_BIG_BOSS_REMOTE_CHART = 563;
/*     */   public static final int TYPE_SINGLE_TASK__DOUBLE_ELEVEN = 564;
/*     */   public static final int TYPE_PET_MARK = 565;
/*     */   public static final int TYPE_FRIENDS_CIRCLE_PAY_ATTENTION = 566;
/*     */   public static final int TYPE_FINAL_SERVER_BUFF_AWARD = 567;
/*     */   public static final int TYPE_FINAL_SERVER_MAIL_ITEM_AWARD = 568;
/*     */   public static final int TYPE_PET_ARENA_CHART = 569;
/*     */   public static final int TYPE_WING_OCC_PLAN = 570;
/*     */   public static final int TYPE_SINGLE_TASK_ICE = 571;
/*     */   public static final int TYPE_MULTI_TASK_ICE = 572;
/*     */   public static final int TYPE_FEI_SHENG_119 = 573;
/*     */   public static final int TYPE_SPIRIT_ANIMAL_ACTIVITY = 574;
/*     */   public static final int TYPE_CHILDREN_RECALL = 575;
/*     */   public static final int TYPE_PET_FIGHT_SKILL = 576;
/*     */   public static final int TYPE_LUN_19_23 = 577;
/*     */   public static final int TYPE_BALL_BATTLE = 578;
/*     */   public static final int TYPE_COMMON_EXCHANGE_PI_PI_LONG = 579;
/*     */   public static final int TYPE_SEVEN_SINS = 580;
/*     */   public static final int TYPE_CHRISTMAS_TREASURE_HUNT = 581;
/*     */   public static final int TYPE_CHRISTMAS_STOCKING = 582;
/*     */   public static final int TYPE_CHRISTMAS_STOCKING_HIDING = 583;
/*     */   public static final int TYPE_WITCH_SCROLL_ACTIVITY = 584;
/*     */   public static final int TYPE_TIME_LIMIT_GIFT_BAG_ACTIVITY_GIFT_TO_FRIENDS = 585;
/*     */   public static final int TYPE_MAKE_UP_NEW_YEARS_DAY = 586;
/*     */   public static final int TYPE_FU_BEN_ACTIVITY_TEST = 587;
/*     */   public static final int TYPE_FU_BEN_ACTIVITY_SAO_DANG_TEST = 588;
/*     */   public static final int TYPE_CROSS_BATTLE_ROUND_ROBIN_STAGE_BET_SEASON_3 = 589;
/*     */   public static final int TYPE_CROSS_BATTLE_SELECTION_STAGE_BET_SEASON_3 = 590;
/*     */   public static final int TYPE_CROSS_BATTLE_FINAL_STAGE_BET_SEASON_3 = 591;
/*     */   public static final int TYPE_DRAW_CARNIVAL = 592;
/*     */   public static final int MIN_TYPE_ID = 0;
/*     */   public static final int MAX_TYPE_ID = 592;
/*     */   public int moduleid;
/*     */   public int funid;
/*     */   public byte isopen;
/*     */   public LinkedList<Integer> params;
/*     */   
/*     */   public ModuleFunSwitchInfo()
/*     */   {
/* 613 */     this.params = new LinkedList();
/*     */   }
/*     */   
/*     */   public ModuleFunSwitchInfo(int _moduleid_, int _funid_, byte _isopen_, LinkedList<Integer> _params_) {
/* 617 */     this.moduleid = _moduleid_;
/* 618 */     this.funid = _funid_;
/* 619 */     this.isopen = _isopen_;
/* 620 */     this.params = _params_;
/*     */   }
/*     */   
/*     */   public final boolean _validator_() {
/* 624 */     return true;
/*     */   }
/*     */   
/*     */   public OctetsStream marshal(OctetsStream _os_) {
/* 628 */     _os_.marshal(this.moduleid);
/* 629 */     _os_.marshal(this.funid);
/* 630 */     _os_.marshal(this.isopen);
/* 631 */     _os_.compact_uint32(this.params.size());
/* 632 */     for (Integer _v_ : this.params) {
/* 633 */       _os_.marshal(_v_.intValue());
/*     */     }
/* 635 */     return _os_;
/*     */   }
/*     */   
/*     */   public OctetsStream unmarshal(OctetsStream _os_) throws MarshalException {
/* 639 */     this.moduleid = _os_.unmarshal_int();
/* 640 */     this.funid = _os_.unmarshal_int();
/* 641 */     this.isopen = _os_.unmarshal_byte();
/* 642 */     for (int _size_ = _os_.uncompact_uint32(); _size_ > 0; _size_--)
/*     */     {
/* 644 */       int _v_ = _os_.unmarshal_int();
/* 645 */       this.params.add(Integer.valueOf(_v_));
/*     */     }
/* 647 */     return _os_;
/*     */   }
/*     */   
/*     */   public boolean equals(Object _o1_) {
/* 651 */     if (_o1_ == this) return true;
/* 652 */     if ((_o1_ instanceof ModuleFunSwitchInfo)) {
/* 653 */       ModuleFunSwitchInfo _o_ = (ModuleFunSwitchInfo)_o1_;
/* 654 */       if (this.moduleid != _o_.moduleid) return false;
/* 655 */       if (this.funid != _o_.funid) return false;
/* 656 */       if (this.isopen != _o_.isopen) return false;
/* 657 */       if (!this.params.equals(_o_.params)) return false;
/* 658 */       return true;
/*     */     }
/* 660 */     return false;
/*     */   }
/*     */   
/*     */   public int hashCode() {
/* 664 */     int _h_ = 0;
/* 665 */     _h_ += this.moduleid;
/* 666 */     _h_ += this.funid;
/* 667 */     _h_ += this.isopen;
/* 668 */     _h_ += this.params.hashCode();
/* 669 */     return _h_;
/*     */   }
/*     */   
/*     */   public String toString() {
/* 673 */     StringBuilder _sb_ = new StringBuilder();
/* 674 */     _sb_.append("(");
/* 675 */     _sb_.append(this.moduleid).append(",");
/* 676 */     _sb_.append(this.funid).append(",");
/* 677 */     _sb_.append(this.isopen).append(",");
/* 678 */     _sb_.append(this.params).append(",");
/* 679 */     _sb_.append(")");
/* 680 */     return _sb_.toString();
/*     */   }
/*     */ }


/* Location:              D:\桌面\山海\gsxdbdebug.jar!\mzm\gsp\open\ModuleFunSwitchInfo1.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */